### ISSUE TITLE
Vimeoの埋め込み

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#10]

**Comment by KaseiKondo** [comment]
@jacopen こちら、テストするには何があればよいですか？とりあえず、Pk1のアカウントがあるので、それを使うことは可能ですが、いろんなイベントで使っているものなので、管理サイトの権限をお渡しすることはできません。

1. 近藤に必要な情報・設定内容を教えていただいて、近藤が作業する。
2. 管理サイトの権限がないとどうにもならないようでしたら、CNDT専用のアカウントを取得します。

1と2、どちらがよいですか？

**Comment by jacopen** [comment]
@KaseiKondo 
なるほど、それであれば2でお願いしたいです。
というのも、自分としてもDreamkast-Vimeoの連携で何がどこまで必要なのか見えてないので、アドホックに対応していく必要がありそうなので･･･

**Comment by KaseiKondo** [comment]
@jacopen かしこまりました。では、手配するようにいたします。 cc: @nabemasat
