### ISSUE TITLE
Archivesのイベントを時系列順に並べる

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/dreamkast#1010]
https://event.cloudnativedays.jp

- CNDT2021 (2021/11)
- CNDT2020 (2020/9)
- CNDO2021 (2021/3)
- CICD2021 (2021/9)

の順に並んでいる。時系列順に並べたい。

- CNDT2021
- CICD2021
- CNDO2021
- CNDT2020

![event-archives](https://user-images.githubusercontent.com/4710215/140732441-3e993127-47b3-4069-b595-20ca4a1b149f.png)

**Comment by oke-py** [comment]
viewはここ
https://github.com/cloudnativedaysjp/dreamkast/blob/31751f0bc5e64499cf4d9488c9bbaa4cfd215f86/app/views/home/show.html.erb#L18-L26

`@previous`がソートされているようにすればよさそう。
https://github.com/cloudnativedaysjp/dreamkast/blob/31751f0bc5e64499cf4d9488c9bbaa4cfd215f86/app/models/conference.rb#L31-L33

**Comment by oke-py** [comment]
やらなくても問題ない、ちょっとしたやつだと思うので、good first issueとして私やってみようかな。
環境構築からはじめるため、時間かかるかもしれませんが。

**Comment by jacopen** [comment]
おお、是非お願いします！

**Comment by oke-py** [comment]
```ruby
  scope :previous, -> {
    merge(where(status: 2).or(where(status: 3))).order(id: :desc)
  }
```
でもソートできるが、`conference_days`テーブルの`date`カラムをみるべし。
JOINをrailsで扱う方法を調べねば。
