### ISSUE TITLE
トップページに情報を追加

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#102]
現在のトップページ https://cndt-dreamkast.herokuapp.com/cndt2020/ 
は、あまりにも情報量が少なく、どんなイベントなのか初見の訪問者が判断するのが難しい。

イベントの主催者に関する情報やお問い合わせページ、そもそもバーチャルイベントである旨の記載、参加無料である記載などなど、初見の訪問者向け情報がなさ過ぎなことに気づいたので作っていく必要がある

**Comment by takaishi** [comment]
https://github.com/cloudnativedaysjp/dreamkast/pull/114 で対応済かな
