### ISSUE TITLE
スピーカーダッシュボードで動画や資料を非公開にしたものが反映されていない

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#1022]
動画を非公開にしたのに公開されてしまっているという連絡があった。

以前使っていたフラグが今は使われておらず、正しく反映されていない可能性がある

**Comment by takaishi** [comment]
まずは動画・資料の公開可否について現状の挙動を整理する

**Comment by takaishi** [comment]
まずはAs-isから。
## 動画の表示・非表示をどのように制御しているか

アーカイブ動画の埋め込みは以下のファイルで行っている。

- `app/views/talks/partial_show/_talk_video_block.html.erb` 
- `app/views/talks/partial_show/_talk_video_block_videojs.html.erb`

これらは `app/views/talks/partial_show/_col_main_pane.html.erb` から呼び出されている。

```ruby
      <% if (conference.closed? && @current_user) || (conference.opened? && @current_user) || conference.archived? %>
        <% if conference.abbr == 'cndt2021' %>
          <%= render 'talks/partial_show/talk_video_block_videojs', talk: talk %>
        <% else %>
          <%= render 'talks/partial_show/talk_video_block', talk: talk %>
          <% end %>
      <% end %>

```

* `conference.closed? && @current_user` : カンファレンスがクローズ状態、かつ閲覧者が参加者としてログインしている
* `conference.opened? && @current_user` : カンファレンスがオープン状態、かつ閲覧者が参加者としてログインしている
* `conference.archived?`: カンファレンスがアーカイブ状態

これらのいずれかを満たしている場合`talk_video_block_videojs`か`talk_video_block`をレンダリングする。

さらに、`talk_video_block_videojs`と`talk_video_block`の中でも制御している。

```ruby
<% if talk.video_published && talk.video.present? && talk.archived? %>
  [snip]
<% end %>
```

* `talk.video_published` : talkレコードのvideo_publishedカラム。Boolean。
* `talk.video.present?` : talkに紐付くvideoが存在するかどうか。
* `talk.archived?` : talkのend_timeから600sec経過したかどうか。

これらを全て満たしている場合動画の埋め込みがレンダリングされる。



## 資料の表示・非表示をどのように制御しているか

資料URLの表示は以下のファイルで行っている。

* `app/views/talks/partial_show/_col_main_pane.html.erb`

```ruby
      <% if talk.document_url.present? %>
        <div class="col-12 my-3 pt-2" style="border-top: 1px solid #CCC">
          <ul>
            <li><a href="<%= talk.document_url %>" target="_blank">発表資料</a></li>
          </ul>
        </div>
      <% end %>
```

* `talk.document_url.present?` : talkレコードのdocument_urlに値が入っているかどうか。

これらを満たしている場合、URLがリンクとして表示される。

**Comment by takaishi** [comment]
# To-be

### 従来の `talk.video_published`  を用いた制御に戻す

* pros
  * ProposalItemConfigまわりのややこしい仕様に引っ張られない
* cons
  * 資料の表示制御の実装も必要

### `whether_it_can_be_published` ラベルのProposalItemを制御に利用するように実装する

* pros
  * Conference毎に資料の表示制御を行うかどうかをProposalItemでコントロールできる
* cons
  * ProposalItem自体がややこしく、バグのもとになりそうな気もする

**Comment by takaishi** [comment]
修正方針悩むなー。

**Comment by takaishi** [comment]
whether_it_can_be_published を使う方向で実装しちゃうか。

**Comment by takaishi** [comment]
手元で触っていて、ProposalItemConfigはアーカイブ表示可否には使わない方がいいなと思い直したのでやはり従来の方法を用いた制御にもどしたい

**Comment by takaishi** [comment]
なおしました！
