### ISSUE TITLE
chat と mail のワーカーを同一のコンテナで起動させられるようにするか検討する

### ISSUE THREAD

**Issue by oshiro3** [cloudnativedaysjp/dreamkast#1026]
解決すべき課題は現時点で以下の通り

* 2プロセスを1コンテナで起動するにはバックエンドで走らせる必要があり、ログを標準出力に出せない(無理やり出したとして混在してしまう)
* 死活管理をプロセスごとに適用し、通知しないといけない
* 今後ワーカーを追加していくに当たって追加しやすいようにしたい。

https://github.com/cloudnativedaysjp/dreamkast/pull/1013

**Comment by oshiro3** [comment]
slack の流れをこちらに転記します

> その上で、おそらくコンテナ内で2プロセス起動する必要はないのではないか、と思っています。default queue的なSQSリソースを用意して、workerはそれを素朴に参照すればよいのかなと。
> なので、同じキューをMailとChatのジョブが流れて、同じワーカープロセスが順次処理するイメージですね。

**Comment by takaishi** [comment]
チャットもFIFOキューで足りるような気もするけど、分けておくほうが安全といえば安全ですかねえ。
そうすると、Deploymentとしてワーカーはわけるべきではありますね。原則として1コンテナ内で複数プロセス動かしてログや死活監視をがんばるというのは方向性としてよくないと思うので。
その場合、名前はmailやchatのような固有の機能名ではなくジェネリックなものにしておいて、用途に応じて使い分けられるようにするのがいいと思います。

**Comment by oshiro3** [comment]
なるほど、承知です。

FIFOキューのスループットは

> 1 秒あたり 300 件の送受信または削除

らしいので、チャットがしばらくの間含めて十分であれば default キューで処理した方が色々と楽そうなのでそうしたいのはあります。
Job の振り分けは ActiveJob がやってくれるので考えなくて良いという認識です。

悩ましいところではありますが、どうやって決めましょうか？

**Comment by takaishi** [comment]
1000FIFOでも高スループットを有効にすれば3000件/秒いけるので、イベントの時に有効にしてチャットの利用状況を見てみるのがいいかもしれないですね。

僕の意見としては

* 同じSQSキューを使うならワーカーはわけない
* 異なるQSSキューを使うならワーカーはDeploymentレベルでわける
* 特定のジョブに特化する必要が無ければ、キューの名前は汎用的な名前にしたい

というあたりです。

**Comment by oshiro3** [comment]
> FIFOでも高スループットを有効にすれば3000件/秒いけるので、イベントの時に有効にしてチャットの利用状況を見てみるのがいいかもしれない。

なるほどです！
承知しました。
この課題はその方向で進めたいと思います！

**Comment by takaishi** [comment]
はい！コメントはしますが、最終的には @oshiro3 の方で決めてもらって問題ないです
