### ISSUE TITLE
登壇者通知機能の外部通知機能の仕様検討

### ISSUE THREAD

**Issue by oshiro3** [cloudnativedaysjp/dreamkast#1040]
登壇者通知機能 #1018 に関して仕様の追加検討です。

Dk 上で通知を作成するだけでは弱いのでメールを送信するようにした方が良いかと考えています。
メールを送信する場合だと、どのタイミングで送信するかを決める必要があります。

1. 公開時と編集時の両方で送信する

- 誤った内容で公開した場合などでも登壇者に正確な内容で伝えることができる
- 編集時に編集である旨を明記する必要などを考慮すると予想される使用頻度に対して実装コストが高い
- 誤った通知を非公開にして修正された内容で再度公開するという運用も可能

2. 公開時のみ送信する
- 実装コストが低い
- 公開されたメールを編集した場合登壇者に誤解を生じさせたままの可能性がある

の２パターンがあるかと思います。

私見ではこれはパターン２が、もし誤って公開した場合は `誤った通知を非公開にして修正された内容で再度公開する` のが最も正しい運用かつ低コストの実装になるため良いのではないかと考えます。

**Comment by nabemasat** [comment]
>パターン２が、もし誤って公開した場合は 誤った通知を非公開にして修正された内容で再度公開する のが最も正しい運用かつ低コストの実装になるため良いのではないかと考えます。

はい、私もそちらで問題ないかと思います

**Comment by oshiro3** [comment]
ありがとうございます！
こちらで進めていきます。
