### ISSUE TITLE
全登壇者向け通知で CFP 不採択者を除外する機能の仕様検討

### ISSUE THREAD

**Issue by oshiro3** [cloudnativedaysjp/dreamkast#1041]
登壇者通知機能 #1018 に関して仕様の追加検討です。

Dkの管理画面から全登壇者向け通知を作成可能ですが、CFP完了以降だと採択者にのみ通知したいというケースがあるのではないかと思います。
これについて下記のパターンを検討しました。

1. CFP の採択状況を考慮しない
  - 実装コストは低い
  - 非採択の方でも登壇の流れがわかるので次回の応募につながるかも
  - 余分な通知をすることで不快さを覚える方がいる可能性もある
2. 通知作成時にチェックボックス等で送信範囲を選択できるようにする
- 実装コストやや高ではあるが、現実的な範囲
- メールの送信量を減らせる
- 非採択の方を考慮せずに文面を作成できる

これにつきましても、個人的にはパターン２が比較的現実的なように考えています。

**Comment by oshiro3** [comment]
ご確認ありがとうございます。
私の想定としては CFP 募集終了後、登壇に関する連絡などを非採択となった方には送信しないための機能となります。

>メールの送信量を減らせる

そのためこれは登壇準備を促すための promote や登壇に必要な情報を CFP 採択の方にのみ送信することを意味しているつもりです！

もちろん機能として非採択の方のみに送信するようにすることも可能です。
ただ、現状一括送信の場合には宛名や文言などを個別に適用することができないというのもあります。

全員一律の通知でも問題無さそうであれば

>採択の方、非採択の方別々に通知を作成することで、送り分けできる

ように実装していきますが、いかがでしょうか。

**Comment by oshiro3** [comment]
@nabemasat 
ご検討ありがとうございます。
一部認識のずれがあるかと思っていまして、現状の想定ではCFPの通知への特定機能ではないという想定です。
元々の目的としてはCFP採択後の登壇のご案内やURLの情報などを通知するための経路をDkに作成するというものでした。
この辺りの前提の説明を省いてしまい大変申し訳ありません。

そのためどちらかというと事務的な連絡に使用するという目的になるため CFP のご連絡について

> 自前のGASで採択/非採択の内容の送り分けと、宛名の反映はできているので
宛名の反映等がDk側でできないのであれば、無理に通知機能で採択の連絡をするより、
応募者の名前／セッション名／メールアドレス／採択・非採択の情報
をCSVで吐き出して頂いたほうが、運用上楽ではないかと感じました

ということであれば、そのように運用していただくのが良いかと思います。

その上で当初の目的に立ち返りますと、**登壇の案内であったり事前連絡といった全員に一律に送信する(宛名程度は動的に生成できると思いますが)お知らせを CFP の非採択の方にも送信すべきか？**というのが本 Issue の主たる論点になります。
論点がぼける書き方をしてしまい申し訳ございませんでした。
お忙しいところ大変恐縮ではありますが、こちら踏まえたうえで再検討いただけますでしょうか。

> （最初のCFP採択の連絡と、Dkからの通知が別のアドレスから届くという気持ち悪さはありますが…）

こちらにつきましては完全に考慮し忘れていましたが、如何ともしがたい話かと思いますので、Dk定例で議題として挙げさせてください。

> >現状一括送信の場合には宛名や文言などを個別に適用することができないというのもあります。
>
>こちらは実装コストが高いからでしょうか。それとも、連携できない理由があるのでしょうか。
>（中の仕組みを理解せずに書いているので、的はずれな事を言っていたらすみません、、🙇)
>
>（CFPの連絡は、一度しか使わない汎用性のない用途なので
>そのために場合分けなどで実装が複雑になるのは避けるべき、ということでしたら理解できます）

そうですね、今今の状況ではご指摘の通りになります。
別途の設計と実装が必要な要件になりますので、他タスクとの状況では厳しいかと思います。

**Comment by jacopen** [comment]
oshiroさんが書いてくれているように、この機能の発端はCNDT2021開催日直前にあった、ZoomのURLをいかに誤りが起きづらい形で登壇者に伝えるかという課題に対するものです。
メールでZoom URLを送るフローの場合、頻繁に訂正することが難しい&訂正してもちゃんと正しく最後のメールだけ参照してくれるとは限らない･･･といった、実際に直面した課題を解消する目的で作ったものですねー。
