### ISSUE TITLE
使っていないMediaLive Channelを削除する

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#1045]
Billingを確認したところ、すでに使っていないMediaLiveのチャンネルで費用が発生し続けているようだった。
無駄な出費となってしまうので、削除してしまおう

**Comment by takaishi** [comment]
バージニア北部と東京からは全部消した

**Comment by takaishi** [comment]
ほかのリージョンには作ってないと思うのでクローズ
