### ISSUE TITLE
一般申し込み開始前にもかかわらず登録画面に飛ばされてしまう

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#1050]
#1047 でディスカッションしているもの。

CFP開始したあと、エントリーすると以下のような挙動が起きてしまう。

- エントリー後にSpeaker dashboardからpublic session pageを表示するとregistrationに飛ばされてしまう
- エントリー後、かつAuth0のログインが生きている状態でsession listを表示しようとするとregistrationに飛ばされてしまう
- 先にLoginからAuth0ログインを行う(たとえばCNDT2021でログイン済みとか)、その後にエントリーを行おうとするとregistrationに飛ばされてしまう

これらはスピーカーからすると予期しない挙動なので、改善したい

**Comment by oshiro3** [comment]
#1066
