### ISSUE TITLE
docker-composeで使っているイメージ `roribio16/alpine-sqs` にarm64がない

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast#1062]
そのため、現状のままだとM1 Mac上でworkerを含む開発ができない。同等のイメージを自前で用意するか、開発時にもAWS上のSQSを使うかどちらかが必要。

**Comment by takaishi** [comment]
issue: https://github.com/roribio/alpine-sqs/issues/49
PRも一応でている: https://github.com/roribio/alpine-sqs/pull/50

**Comment by takaishi** [comment]
localstackを使うこともできるようだ

**Comment by oshiro3** [comment]
なるほどです。
ただメインの方でもエラー出ていて6月から触られていないっぽいのでしばらく時間かかりそうですね。
さしあたりだと
* ActiveJob 絡みの開発でなければ一時的に同期処理にする
* キューを local にする
* AWS に開発用キューを作る
* 代替イメージを使う
* arm/v8 でイメージをビルドして ECR でホストする（P/R を見る限りおそらく無理っぽい？）
などで対応する形になるかと思います。
SQSのイメージは他にもあると思うので M1 対応済みのものがあればぼくの方でも差し替えなど対応します

**Comment by jacopen** [comment]
- AWS に開発用キューを作る
案でいく

**Comment by jacopen** [comment]
↑の開発用キューを作る方法をドキュメント化したらこのissueはクローズ

**Comment by jacopen** [comment]
localstackのsqsも試してみていけそうならそっちにするかも
