### ISSUE TITLE
admin以外のユーザーが/admin以下にアクセスできないようにする

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast#118]
今はadminじゃない旨を表示しているだけだけど、アクセスできないようにしないといけない

**Comment by takaishi** [comment]
403 Forbidden を返すのがいいかなっと。

**Comment by takaishi** [comment]
is_adminメソッド内のコメントアウトしているコードだとトラック一覧にリダイレクトしているのか

**Comment by jacopen** [comment]
403にするのがいいとおもうます
