### ISSUE TITLE
ロゴの修正依頼

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#1184]
@MikiNakayama 
Googleさんはロゴが透過されていないので、透過版がないか聞いて貰いたいです

Oracleさんはロゴの解像度が低く、表示する際にぼやけてしまうので、もう少し高解像度のバージョンがないか問い合わせをお願いします

**Comment by cyberblack28** [comment]
oracleのロゴについては、私の方で確認します。

**Comment by jacopen** [comment]
おお、助かります！

**Comment by MikiNakayama** [comment]
@jacopenGoogle様のロゴデータ、 背景を透過させました、こちらでよろしいでしょうか？ご確認いただけますと幸いです。
https://drive.google.com/open?id=1wuwUkuQB943H7J3Iti9zisTq5ZPItywz&authuser=nakayama%40peak-1.tokyo&usp=drive_fs

**Comment by cyberblack28** [comment]
@jacopen 

以下格納しました。問題等あれば連絡ください。

https://drive.google.com/drive/folders/1c35CaPJ0MmZI2rwMN885IOnPjYzGK2c4

ファイル名：Oracle_cmyk_03_91_86_12.png

**Comment by jacopen** [comment]
@cyberblack28 ありがとうございます！ これCMYKなのでRGB版があればそちらを頂きたいです！

**Comment by jacopen** [comment]
@MikiNakayama ありがとうございます！

**Comment by cyberblack28** [comment]
@jacopen RGB版格納しました。

https://drive.google.com/drive/folders/1c35CaPJ0MmZI2rwMN885IOnPjYzGK2c4

ファイル名：Oracle_rgb_#c74634.png

**Comment by jacopen** [comment]
ありがとうございます、助かります
