### ISSUE TITLE
採択されたスピーカーにお知らせ機能でロゴ等のアセットを通知する

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#1221]
- ロゴ
- 仮想背景
- 上記アセットのライセンス

~~あたりをスピーカーダッシュボードに貼っておくと、登壇者がセルフサービスで利用できて便利(こちらも個別対応しなくていい)~~

アセットのリンク先をお知らせ機能で通知する

**Comment by jacopen** [comment]
よく考えたらこれ個別に項目を実装しなくても、お知らせ機能でリンクを通知するだで済むなと思ったので実装はしない。

**Comment by jacopen** [comment]
@nabemasat 
こちらのリンクを採択者全体通知で送ってもらえませんか？
https://assets.adobe.com/public/998604da-31b6-4fd9-4936-8c69a6015ab8

**Comment by nabemasat** [comment]
こちら遅くなり申し訳ありません。明日8:30公開で通知設定しました:bow:
