### ISSUE TITLE
CNSec2022/CNDJ2022 フォーム改修のご要望（インプレス）

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#1228]
インプレスさんから、次回のCNSec2022より、データ整備の都合、インプレス社の他のイベントと個人情報入力フォームの項目をできるだけ揃えられないかという相談が来ています。

改修案：
https://docs.google.com/spreadsheets/d/1F9pviKdm63tsqA5NPvMvuGy35EkIbn9Ay9s4KG265EQ/edit?usp=sharing
（最低限対応してほしい項目とのことです）

サンプル：
https://www.evt-entry.com/dif2022_sp/
（若干上記と異なる項目や、追加質問が多数あります）

対応可能かどうかと、可能な場合はスケジュールの目処についてお知らせいただけないでしょうか:bow:

**Comment by jacopen** [comment]
内容的に対応は可能です。郵便番号入力したときに自動的に住所を補完っていうのがよくありますが、そこは努力目標で・・・(フォーム要件的にはそこまではないので)

`データは配布つなぎで格納` ってありますが、これはハイフンで良いですよね？

スケジュールの目処については、『一般参加申し込み受付時までに必要』という以外に無い気がします。
だとすると7頭ということになります。旧仕様のままだとデータの整合性がとれないので参加申し込みは開始できない=7頭がデッドライン　という理解です。

それよりも早くに完成させる必要があればお知らせください

**Comment by jacopen** [comment]
あと
> （最低限対応してほしい項目とのことです）

とありますが、逆に最低限ではないオプショナルな項目があるということですか？

**Comment by nabemasat** [comment]
ありがとうございます。誤字すみません、こちらは確認しましたがやはり「ハイフンつなぎ」でした。
7月頭対応で問題ございません。

オプショナルな項目は、こちら側で必要があれば追加する質問とのことなので、上記の表の内容を対応いただくだけで問題ありません。

**Comment by takaishi** [comment]
@nabemasat これってどういう観点で揃えたいのでしょうか？フォームの項目レベルで揃えたいのか、それともリードとして出力されたデータの項目や内容を他イベントと揃えたいのかを確認したいです。

というのも、 郵便番号や電話番号、勤務先の住所の入力フォームを分けてほしいという要望が含まれているのですが、住所はある程度わかれていても利便性がありそうなのですが、郵便番号や電話番号はデータとして分かれている必要があるのかあまりわかってないためです（オートコンプリート的にもわかれていな方がいい気がします）

**Comment by jacopen** [comment]
@nabemasat 性別について必須項目となっていますが、世の中の流れ的にはあまり望ましくない項目と思われます。
出来るだけこれは実装しない方向で行きたいので、impress側に確認をお願いします。

どうしても必要と言う場合は、「回答しない」「ノンバイナリー」という選択肢を付け加えることは必須かと思われます

**Comment by nabemasat** [comment]
@takaishi 
もう一点の質問、回答漏れしていました:bow:

リードとして出力された項目や内容を他イベントと揃えたいというのが、先方のご要望の動機です。
確かにご指摘の、郵便番号や電話番号については、個人的にはハイフンでセルを分ける合理的理由が見当たりません。
これは一つにまとめちゃいたいですよね。

所属部署については、フリー回答欄は肩書きとしての所属部署、
選択肢式回答は所属部署が当てはまるカテゴリを入力する項目と理解しています。
ですので、聞き方を変えることで対応できると良いかもしれません。

@miyana0907 さんにも確認を取ってみます。

**Comment by miyana0907** [comment]
@takaishi 
ご返事が遅くなり申し訳ございませんでした。
以下、インプレスの希望をお伝えします。

【1】電話番号、郵便番号がハイフンごとに入力欄が区切られているのを、一つにまとめたい。
→「ハイフンなしで入力してください」といった注意書きを入れて頂ければ入力欄を1つにまとめても問題ございません。

【2】
所属部署をフリー記入欄とアンケート選択欄で二重に聞くのを、どちらかにしたい。
→インプレスの希望としてはアンケート選択を残して頂きたいです。

以上、ご検討くださいますようお願い申し上げます。
宜しくお願い致します。

**Comment by jacopen** [comment]
@takaishi 
> 【1】電話番号、郵便番号がハイフンごとに入力欄が区切られているのを、一つにまとめたい。
> →「ハイフンなしで入力してください」といった注意書きを入れて頂ければ入力欄を1つにまとめても問題ございません。

これはJSでバリデーション入れるのがよさそう

**Comment by jacopen** [comment]
#1262 が残っているがこの作業自体は終わっているため閉じ

**Comment by jacopen** [comment]
@miyana0907 @nabemasat 

このフォーム改修案だと
https://docs.google.com/spreadsheets/d/1F9pviKdm63tsqA5NPvMvuGy35EkIbn9Ay9s4KG265EQ/edit#gid=2052212509

- 役職区分(プルダウン)と役職(フリーフォーム)
- 所属部署(プルダウン)と所属部署名(フリーフォーム)

がダブっていますが、プルダウンを残してフリーフォームを削除で最終確定で良いですか？

またこれは追加で確認ですが、業種がチェックボックスとなっています。が、これはプルダウンのほうが向いていると思うのですが、プルダウンで実装して問題ありませんか？
