### ISSUE TITLE
Ruby/Railsじゃなくてもいい処理を切り出していきたい

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast#1239]
Goの方が書ける人が多いので、Goで切り出せるとよさそう。

- Rake Taskでやっているものなど

**Comment by jacopen** [comment]
早めにやりたいもの
- ViewerCount
- HarvestJob
-

**Comment by jacopen** [comment]
一旦切り出したのでこちらは閉じ
