### ISSUE TITLE
CNSec参加登録時の許諾文面の実装（日本マイクロソフト）

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#1249]
お疲れ様です。MSさんについて、参加フォームに下記の文面とチェックボックスを実装いただけないでしょうか。
（CNDT2021, CI/CD, CNDO2021などと同様のイメージです）

文面：

日本マイクロソフト株式会社から情報提供を希望される場合、申し込み者情報に記載いただいた内容を日本マイクロソフト株式会社へ提供させていただきます。利用目的は当該企業の製品・サービスに関する情報またはマーケティング活動に関する情報をお知らせすることです。個人情報の取り扱いにつきましては、日本マイクロソフト株式会社のプライバシーポリシーに準拠します。

□日本マイクロソフト株式会社への個人情報提供に同意する（[プライバシーステートメント](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprivacy.microsoft.com%2Fja-jp%2Fprivacystatement%2F&data=04%7C01%7Cakusaga%40microsoft.com%7C21fc00ed9eae4332200d08d98e180aca%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637697056183006368%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3OA9vG6nzAydMOp0o2qjaufaJIfXrVv6jgVwIGY7gk0%3D&reserved=0)）

**Comment by jacopen** [comment]
了解です。これも今のフォーム修正と同じタイミングで入れます

**Comment by nabemasat** [comment]
@jacopen @takaishi 

すみません、マイクロソフトさんからご連絡があり、文面を下記に修正してほしいとのことでした:bow:
ご対応よろしくお願いいたします:bow:

> 
> 文面：
> 
> 日本マイクロソフト株式会社への個人情報の提供にご同意いただける場合は、以下にチェックをお願いいたします。
> ご同意いただいた場合、申し込み者情報に記載いただいた個人情報を、日本マイクロソフト株式会社へ提供するものとし、日本マイクロソフト株式会社の製品・サービス、ウェビナー等に関する情報のご案内（電子メールよるお知らせのほか、記事等のコンテンツも含みます。）の目的ために利用いたします。なお、日本マイクロソフト株式会社は、提供された個人情報を、以下のプライバシーステートメントに準拠し、取り扱うものとします。
> 
> □日本マイクロソフト株式会社への個人情報提供に同意する（プライバシーステートメント）
> 
> 
> ※ □ はチェックボックスを設置
> ※最後の行の プライバシーステートメント に以下のリンクを付ける
> https://privacy.microsoft.com/ja-jp/privacystatement

インプレスさんから、個人情報フォームのキャプチャを要望されているので、レビューアプリを出すときに、すみませんが@nabemasat 
にもメンションいただけると助かります。

CC @miyana0907

**Comment by miyana0907** [comment]
@jacopen @takaishi 
度々で申し訳ございません。
4月からの個人情報保護法の改正でパーミッションの文言を変更する必要があり、ついては添付の内容に差し替えをお願い致します。
あわせてスポンサー社名に各社のプライバシーポリシーページのリンクを入れるため、事務局にURLを確認してもらっています。
確認でき次第、お伝えします。
恐れ入りますが宜しくお願いします。
[パーミッションの文言【イベント全体】個人情報の取り扱いについて.txt](https://github.com/cloudnativedaysjp/dreamkast/files/9017539/default.txt)

@nabemasat

**Comment by KaseiKondo** [comment]
> あわせてスポンサー社名に各社のプライバシーポリシーページのリンクを入れるため、事務局にURLを確認してもらっています。

こちらに回収したURLを記載しています。
https://docs.google.com/spreadsheets/d/1yYwGYjH_KuBmErNS2aFT6CYJMeSJ_C06Hq0oqEcZERo/edit#gid=0&range=AG:AG

**Comment by jacopen** [comment]
@KaseiKondo スプシ見えないですー

**Comment by nabemasat** [comment]
@jacopen @KaseiKondo すみません！URLこちらが正しいです。こちらのシートのO列になります:bow:
https://docs.google.com/spreadsheets/d/134oR72Uc6kEDwdCafPnyZB04fsVjXx3ExhQnSkMS7mE/edit?usp=sharing
