### ISSUE TITLE
CFPエントリー時のプライバシーポリシー文言の変更

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#1250]
青山さん経由で、エントリー時に威圧感がある（登壇者にセミナーなどの営業メールを送るよという印象）との指摘。
実際は、エントリーだけではリストには含まれないので、文言をもっと柔らかく実情に即したものに変更した方が良いかも知れない。
インプレスと相談の上、文言を検討。
```

「登壇者にCFPを登録してもらうページ」に書いてあるこの文言って、このセッションのタイトルとかを、宣伝メールに使うよってことですかね？
それとも登壇者にセミナーなどの営業メールを送るよって意味ですかね？
後者的な文言にとらえて微妙な感情を持ってる人もいるっぽかったので、少し変えても良いでした。
```

**Comment by nabemasat** [comment]
文言作成→Contentsチームに確認→インプレスさん（法務）確認→実装依頼へ

**Comment by jacopen** [comment]
@nabemasat これって急ぎではないと思うんですがずっと残っててもまた忘れそうなので、やれるときに確認して貰っていいですか

**Comment by nabemasat** [comment]
@ito-taka @miyana0907  こちらの内容で登壇者向けプライバシーポリシーを改正したいと思います。法務部への確認について連携できれば幸いです。

（旧）登壇者向け 個人情報保護方針(プライバシーポリシー)

ご登録いただきました個人情報は、イベントの運営会社である株式会社インプレスが管理し、電話/電子メール/郵送等による、各種サービスやセミナー開催情報などの情報提供に利用させて頂きます。インプレス社の詳しいプライバシーポリシーに関しましてはこちらをご覧下さい。

↓

（案）登壇者向け 個人情報保護方針(プライバシーポリシー)

ご登録いただきました個人情報は、イベントの運営会社である株式会社インプレスが管理し、電子メール/SNSによる、本イベントの準備に必要なご連絡にのみ利用させていただきます。インプレス社の詳しいプライバシーポリシーに関しましてはこちらをご覧下さい。

**Comment by nabemasat** [comment]
@jacopen お待たせしました。下記の文言でFIXしましたので、CNDT2022CFP時に反映をお願いできますか。

文面：

```
個人情報の取り扱いについて

ご登録いただきました個人情報は、本イベントの運営会社である株式会社インプレスが管理し、
電子メールまたはSNSのメッセージ機能により、本イベントご登壇に関する選考結果
その他のご連絡・お問合せ対応の目的のために利用させていただきます。
上記をあらかじめご同意の上、ご登録をお願いいたします。

```

> ▼以下、法務からのコメント
> 今回はインプレスが単体で管理し目的も連絡のみかと思いますので、インプレスのプライバシーポリシーへのリンクは省略しております。また「登壇者向け 個人情報保護方針(プライバシーポリシー)」というタイトルについては、全体のプライバシーポリシーと混同する可能性もあるため、単に「個人情報の取り扱いについて」という文言に変更しております。
