### ISSUE TITLE
ビデオファイル提出メールの対象Conferenceの修正

### ISSUE THREAD

**Issue by oshiro3** [cloudnativedaysjp/dreamkast#1260]
差し替え締め切りとConference名が変更の必要がありそうかと思います。
あと一部インスタンス変数の変更漏れがありそうに見えます（これは未検証です）

https://github.com/cloudnativedaysjp/dreamkast/blob/8406929a2cfb6adccf857117f18057cf7d536fd1/app/views/speaker_mailer/video_uploaded.text.erb#L1-L7

**Comment by jacopen** [comment]
#1275 によりこちらはメール送信が不要になるため、このIssueはクローズ
