### ISSUE TITLE
一度登壇者を登録して後日セッション情報を入力しようとすると「セッションを追加」が出てこないスポンサーセッション

### ISSUE THREAD

**Issue by KaseiKondo** [cloudnativedaysjp/dreamkast#1281]
F5さんから連絡があり、登壇者情報は入力が完了していて、セッション情報が入力できないということだったので、Zoomで画面共有してやり方をお伝えしようとしたところ、F5さんの画面で「セッション追加」が表示されていませんでした。
一度登壇者を登録して、後日セッション情報を登録しようとすると「セッション追加」が表示されない現象のように見えるのですが、何か対処策、あるいは正しい登録方法はありますでしょうか。

**Comment by KaseiKondo** [comment]
承知です。

**Comment by jacopen** [comment]
無事登録できたようなのでクローズ
