### ISSUE TITLE
ViewerCountをServerlessな形で切り出す

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#1298]
現在視聴者数をカウントするViewerCount機能はDkに実装している。
しかし、あまりDkのDBで管理するメリットは無い。Lambda + APIGatewayで実装した方が手軽。

なので、この機能を切り出してしまう

**Comment by ShotaKitazawa** [comment]
@ystkfujii 成果物のレビューに自分を加えてもらえると嬉しいです:pray:
管理するリポジトリについては、 mtg で話した通り正解はない (どこで管理してもつらそう) ので、fujii-san が一番作りやすいところでやってもらえればいいと思います！

**Comment by jacopen** [comment]
目的とハイレベルデザイン、既存の実装を以下のドキュメントに書きました
@ShotaKitazawa @ystkfujii 
https://docs.google.com/document/d/1FAO03iv3XavPqPhFbY4PtrgLB38GiUPrlGzvt7KM9Y4/edit#heading=h.64lh0i3s67jj

**Comment by ystkfujii** [comment]
@jacopen @ShotaKitazawa 
質問があります 🙇 
API Gatewayのパスはどのようなものを設定したら良いでしょうか？

既存APIと同様に`/api​/v1​/tracks​/{trackId}​/viewer_count`を作成したら良いのかなと考えています。    
この場合、lambdaとDynamoDB側で下記情報の紐付けを行う必要がある認識です。

-１）trackIdとchannel_arn（またはchannelユニークな値）
-２）channelとそのchannelのviewer_count

２つ目に関しては、ivsのlist-streamで存在するchannel全部取ってきて整形してDynamoDBに突っ込めばたぶん何とかなるかなと考えています。
ただ、１つ目の情報の紐付け方法が分からない状態です。

ここに関しては、現在の仕様では[LiveStreamIvs](https://github.com/cloudnativedaysjp/dreamkast/blob/28b39c343ee67a8fd956858662aa83371320c220/app/models/live_stream_ivs.rb)で紐付けを行っているかと思います。

上記のようなAPI Gatewayを作成する場合、talksIdで問い合わせてLiveStreamIvsに問い合わせをしてchannel_arn(またはchannelユニークな値)を返すAPIをDk側に生やす感じでしょうか？

**Comment by jacopen** [comment]
@ystkfujii 

trackIdに関しては、DreamkastのAPIを叩いて取得する形かなと思っています。

たとえば以下を叩くとcnsec2022のtrackIdを取得することができます。
https://event.cloudnativedays.jp/api/v1/tracks?eventAbbr=cnsec2022

channel_arnに関しては現時点では出てないので、こちらはDreamkast側に追加する必要がありますね。修正はわりとすぐに出来るので、↑のエンドポイントから帰ってくる値にchannel_arnが入る前提で進めて貰えればと思います！

**Comment by jacopen** [comment]
1点訂正
APIからくるキーは `channel_arn` ではなく `channelArn`　でお願いします.

**Comment by ystkfujii** [comment]
aws側の実装MR作りました

https://github.com/cloudnativedaysjp/viewer-count/pull/1

dreamkast側はまだです 😇

**Comment by jacopen** [comment]
ありがとうございます！
DkUIとかIVS側は一緒にやっていきましょうー

**Comment by ystkfujii** [comment]
@jacopen @ShotaKitazawa 
昨日、うまくviewer_countが取得できなかった件、修正しました。

今はこんな感じで見えてます。
出力情報は一旦最低限で作っています。必要な情報あればすぐ修正するので、コメントいただければと思います 🙇 
```
curl https://044c0qiv47.execute-api.us-east-1.amazonaws.com/v1/29/viewer_count
{"trackId": 29, "viewer_count": 0}
````

**Comment by ShotaKitazawa** [comment]
* viewer_count は Grafana で表示するのがゴールなので、`get_viewer_count` を API Gateway 越しに叩くと Prometheus フォーマットのメトリクスが返ってくるのが expected であるという認識です。
    * Python だと https://github.com/prometheus/client_python を使うことになると思います。
* 現在 `dreamkast_track_viewer_count` (track ごとの視聴者数) , `dreamkast_talk_viewer_count` (talk ごとの視聴者数) を開示しているので、こちらもそのようにお願いします。
    * [参考スレッド](https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1657209208642559)
    * [参考PR](https://github.com/cloudnativedaysjp/dreamkast/pull/1292)
    * metrics type が gauge なのにメトリクス名が `*_count` なのはベストプラクティスから外れていますが、ひとまずこのチケット内では現行のメトリクス名を変えない方針でお願いします。
        * もしふさわしい名前があれば、#observability チームと軽く相談した上で別チケットにて rename 作業をよろしくおねがいします:pray:

* 例
```
$ curl https://$DOMAIN/metrics
...
# TYPE dreamkast_track_viewer_count gauge
dreamkast_track_viewer_count{track_id="1",conference_id="1"} 30 <- この数字が viewer count
dreamkast_track_viewer_count{track_id="2",conference_id="1"} 40
...
# TYPE dreamkast_talk_viewer_count gauge
dreamkast_talk_viewer_count{talk_id="1",conference_id="1"} 20
...
```

**Comment by jacopen** [comment]
> viewer_count は Grafana で表示するのがゴールなので、get_viewer_count を API Gateway 越しに叩くと Prometheus フォーマットのメトリクスが返ってくるのが expected であるという認識です。

あ、これに関しては、まず実装して欲しいのはAPIでした
https://dreamkast-api-mock.dev.cloudnativedays.jp/docs/#/Track/apiV1TracksTrackIdViewer_countGET

このドキュメントのHigh Level StructureのDreamkast UI向けの値のためです。
https://docs.google.com/document/d/1FAO03iv3XavPqPhFbY4PtrgLB38GiUPrlGzvt7KM9Y4/edit#

ただ指摘されているとおり、Grafanaでのグラフ化に向けたexporterの実装も今後必要になりますが、それに関してはいったんこのIssueのスコープ外という形でもいいかもしれないです

**Comment by ystkfujii** [comment]
> Grafanaでのグラフ化に向けたexporterの実装も今後必要になりますが

私も最終的にはそこを目指すべきだと思います。  
ただ、今回は要件から外れるかと思い実装しなかった次第です。

> dreamkast_track_viewer_count (track ごとの視聴者数) , dreamkast_talk_viewer_count (talk ごとの視聴者数) を開示しているので

APIのみということであれば、こちらは対応しなくても良いでしょうか？  
対応するのであれば、Prometheusフォーマットを出力するようviewer_countを変更するしかないのかなと思ったりしています...

**Comment by ShotaKitazawa** [comment]
なるほど！勘違いしてましたごめんなさい🙇‍♂️

確かに talk id などは一度 dreamkast を経由しないと無い情報でした🙇‍♂️🙇‍♂️

**Comment by takaishi** [comment]
そういえば、Serverless化した際のコスト見積もりをやっておくとよさそうです。lambdaとapi gatewayはめちゃ雑に計算してかなり低コストそうでした。が、DynamoDBは計算してないのと、今後Railsから切り出してAWSを活用していくと徐々にコストが増えていきそうなので今のうちから見積もりする習慣をつけていくとよさそうかなと。


## lambda

UIが5分に1回get_viewer_countのAPIを呼び出すとする。1ヶ月のうち10時間viewer count apiが呼び出されるとする。UIを利用するのは2000ユーザー、トラック数は5とする


```
(60/5)*10*5*2000 = 1,200,000
```

また、EventBridgeによって5分に1回save_viewer_count functionが呼び出されるとする。1ヶ月の間、10時間EventBridgeが有効とする。

```
(60/5)x10 = 120
```

lambdaは毎月の無料枠があるので、かなり安く抑えられそう。

```
Unit conversions
Amount of memory allocated: 128 MB x 0.0009765625 GB in a MB = 0.125 GB
Amount of ephemeral storage allocated: 512 MB x 0.0009765625 GB in a MB = 0.5 GB
Pricing calculations
1,200,000 requests x 1,000 ms x 0.001 ms to sec conversion factor = 1,200,000.00 total compute (seconds)
0.125 GB x 1,200,000.00 seconds = 150,000.00 total compute (GB-s)
150,000.00 GB-s - 400000 free tier GB-s = -250,000.00 GB-s
Max (-250000.00 GB-s, 0 ) = 0.00 total billable GB-s
1,200,000 requests - 1000000 free tier requests = 200,000 monthly billable requests
Max (200000 monthly billable requests, 0 ) = 200,000.00 total monthly billable requests
200,000.00 total monthly billable requests x 0.0000002 USD = 0.04 USD (monthly request charges)
0.50 GB - 0.5 GB (no additional charge) = 0.00 GB billable ephemeral storage per function
Lambda costs - With Free Tier (monthly): 0.04 USD
```

## API Gateway

viewer count分のAPI呼び出しだけで1,200,000回。viewer count分だけであれば1ドル強だが、全APIをAPI Gatewayに集約していくと徐々にコストが増えるだろう。

```
34 KB per request / 512 KB request increment = 0.06640625 request(s)
RoundUp (0.06640625) = 1 billable request(s)
1.20 requests per month x 1,000,000 unit multiplier x 1 billable request(s) = 1,200,000 total billable request(s)
Tiered price for: 1200000 requests
1200000 requests x 0.0000012900 USD = 1.55 USD
Total tier cost = 1.5480 USD (HTTP API requests)
HTTP API request cost (monthly): 1.55 USD
```

**Comment by ystkfujii** [comment]
## dynamoDB料金ざっくり計算


### 前提

- regionは東京
  - IVSと同じリージョンに置く設計で、IVSが東京に行くと聞いているので
- オンデマンドを使用
  - 読み込み/書き込みリクエストの料金をviewr-countレベルでみるとオンデマンドが安そう（？）
- DynamoDB Standard テーブルクラスを使用
  - データ容量はそんなにないので
- Readはeventually consistent readを使用
  - 4KBのReadに0.5 unit必要
  - 一番安いので
- Writeはstandard writeを使用
  - 1KBのWriteに1 unit必要
  - 一番安いので

### 読み込みと書き込みリクエスト

東京リージョンの金額は以下
- 100万 Write request unit: 1.4269 USD
- 100万 Read request unit: 0.285 USD

仮に100万 WRUを30日で使い切るとしたら、
100万 WRU / 30 日 = 3.3万WRU / 1 日
                  = 1375 WRU / 1 時間
                  = 2 WRU/ 1分

RRUの場合、0.5 unitなのでWRUの倍になる

なので、料金は
- 書き込み：だいたい1KBのデータを1分間に2回書き込んで、1.4259 USD
- 読み込み：だいたい4KBのデータを1分間に4回読み込んで、0.289 USD
  
viewer-countの場合、
- 1分間隔で視聴者数をIVSから取得し保存する
- イベント時は少なくとも1分間隔でデータを取得する
なので、（100万 WRU + 100万 RRU ）/月で何とかなりそう

### データストレージ

- 東京リージョンは
  - 0.285USD/GB-月
  - 25GBまで無料

なので、25GBまでに抑えれば無料

viewer-countの場合、track数分のレコードが入るだけなので25GBは行かなそう 

### バックアップ

したとしても 0.228USD/GB

### まとめ

viewer-countレベルであれば、2 USD/月でくらいになりそう

参考：https://aws.amazon.com/jp/dynamodb/pricing/
