### ISSUE TITLE
Code Of Conductを掲載する

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#130]
Issue立てるまでもないかもですが、後で変更もあると思い、とりあえず立てました。
文面は昨年とほぼ同じですが、オンラインなのでTwitterでのやり取りがメインになると思い、連絡先は実行委員会のTwitterに変更しています。

本文：

イベント主催者は、参加者が人権侵害や差別を受けることのないよう努力しています。本イベントは技術情報の共有や技術者同士のコラボレーションを目指したものです。講演者、来場者、スポンサー、展示関係者、スタッフなどすべての参加者は、いかなる形でもハラスメントに関わってはなりません。ハラスメント行為を目撃したり懸念を感じた場合はCloudNative Days 実行委員会 [@cloudnativedays](https://twitter.com/cloudnativedays) まで速やかにお知らせください。（この行動規範はLinux Foundationのドキュメントを参考にしています）

容認できない行為

    ・性的な言語や画像の使用
    ・個人的な攻撃
    ・侮辱/軽蔑的なコメント
    ・公的または私的なハラスメント
    ・許可なく他人の個人情報を公開すること
    ・その他の非倫理的な行為

引用：https://cloudnativedays.jp/cndt2019/

**Comment by takaishi** [comment]
https://github.com/cloudnativedaysjp/dreamkast/pull/131 で追加
