### ISSUE TITLE
本番の幕間データを登録

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#1303]
幕間データをRakeタスクで登録する。

どういう幕間が今回は必要か確認する必要あり

**Comment by jacopen** [comment]
前回の幕間はこんな感じ
https://github.com/cloudnativedaysjp/dreamkast/blob/main/lib/tasks/add_talks_for_o11y2022.rake

- 開始までお待ちください
- オープニングセッション
- 休憩(必要な回数ぶん)
- Closing
- 終了しました

今回も同じでいいかな？ @Gaku-Kunimi @TakumaNakagame

**Comment by Gaku-Kunimi** [comment]
良いと思います！

**Comment by TakumaNakagame** [comment]
この内容でOKです！ありがとうございます！
