### ISSUE TITLE
CNSec2022: スピーカープロフィールが変更できない

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#1312]
スピーカーのSakiharaさんのから下記の問い合わせがありました。すみませんがご確認いただけると幸いです:bow:

・スピーカーダッシュボードで、登壇者プロフィールに自分の写真をアップロードしようと試しているが、一向に反映されない
・更新ボタンは押してプロフィール編集は正常に完了できるのだけど、その結果が反映されない

**Comment by jacopen** [comment]
@nabemasat 既知の問題にあたってるかもです
今取り急ぎ変更してみたので、再度試すよう伝えて貰えますか？

**Comment by nabemasat** [comment]
@nabemasat TEST

**Comment by nabemasat** [comment]
遅くなりすみません:bow:こちらもSakiharaさんにご連絡済みです:bow:

**Comment by oshiro3** [comment]
@jacopen 
とりあえず現象確認しました。

上が Admin の編集で下がスピーカーダッシュボードからの編集画面ですが、画像関連の CSS が当たっていません。
Admin の編集は通常通りできるので、恐らく画像 UL 系のセレクタの変更で cropping 用の JS が効いていないのではないかと思います。


![image](https://user-images.githubusercontent.com/40717789/179433087-0faa8f59-a838-4a3f-a136-3a84cd531e51.png)
![image](https://user-images.githubusercontent.com/40717789/179433117-f45d346d-0a78-409c-b5b2-e0b822f68a5b.png)

**Comment by jacopen** [comment]
むむ、なるほど？

**Comment by oshiro3** [comment]
スピーカーダッシュボードでも F5 リロードすると読み込まれているのでセレクタではなさそうですね

**Comment by jacopen** [comment]
ちょうど自分もF5リロードで読み込まれることを確認しました。
なんだ・・・？

取り急ぎのワークアラウンドはF5リロードでいける・・・ともいえるけど

**Comment by jacopen** [comment]
あーもしかしたらTurbolinksのせいかもしれない？
(よく分からない挙動はだいたいTurbolinksを疑ってしまう)

**Comment by oshiro3** [comment]
状況証拠的には完全に turbolinks がクロですね

**Comment by jacopen** [comment]
手元で `{ "data-turbolinks" => false }` 入れたら治った気がする。
PR出します

**Comment by oshiro3** [comment]
あ、かぶってしまいました（微妙に実装が異なっている）

**Comment by jacopen** [comment]
@nabemasat こちら根本原因が判明し、対処が完了しましたのでスピーカーに連絡よろしくお願いします
