### ISSUE TITLE
UIのトラックをURLから指定したい

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast#1318]
以下のようなことを実現したい

TrackBを開きたい → `https://event.cloudnativedays.jp/cnsec2022/ui#B`

これは、OBSから各Dkをモニタリングする際に利用したい。
現状では、/uiに入った後、個別にトラックの切り替えを行っており、OBS側での再読み込みが走ったりすると毎回操作しなければならない。
これを回避するために本機能がほしい。

**Comment by jacopen** [comment]
これについては必ずしもUIである必要は無い(むしろログインが無い方が嬉しい)
ということで、さっくり並べて閲覧できるくんを作ってvercelで動かすことにしました

https://github.com/cloudnativedaysjp/broadcast-ivs-monitor
https://broadcast-ivs-monitor-five.vercel.app/
