### ISSUE TITLE
swagger.ymlがそれぞれあるのをなんとかしたい

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#1321]
現時点でswagger.ymlが
https://github.com/cloudnativedaysjp/dreamkast-api-docs/blob/main/swagger.yml
https://github.com/cloudnativedaysjp/dreamkast/blob/main/schemas/swagger.yml
https://github.com/cloudnativedaysjp/dreamkast-ui/blob/main/schemas/swagger.yml

とそれぞれのリポジトリが抱えている。

基本的にはこれらのswagger.ymlは同一でないといけないが、コミット漏れ等によって差分が起きることがしばしばある。
これはあまり良い状態とはいえないので、改善したい

**Comment by jacopen** [comment]
今のところAPIの親玉はDkなわけで、そこにあるswagger.ymlを正にする。
んでdreamkast-api-docsリポジトリは廃して、そこで自動化しているswagger uiの生成をDk側のActionsに移植

とすればリポジトリを減らせる。Dreamkast-UIのswaggerはまた別の方法を考えないといけないけど、まずは副作用の少ない↑案がいいかなって思ってます。

もし何か意見あればください！ @takaishi @maktak1995

**Comment by takaishi** [comment]
良いと思う

**Comment by takaishi** [comment]
現在swaggerの定義ファイルは現在3つのリポジトリ上に存在している。

- https://github.com/cloudnativedaysjp/dreamkast-api-docs/blob/main/swagger.yml
- https://github.com/cloudnativedaysjp/dreamkast/blob/main/schemas/swagger.yml
- https://github.com/cloudnativedaysjp/dreamkast-ui/blob/main/schemas/swagger.yml

この3つのうち、[dreamkast-api-docsのswagger.yml](https://github.com/cloudnativedaysjp/dreamkast-api-docs/blob/main/swagger.yml) をマスターとしている。APIスキーマに追加したり更新する場合、まずdreamkast-api-docs上にPRを作ってswagger.ymlを更新、その後dreamkastとdreamkast-uiにコピーしている。また、dreamkast-uiではswagger.ymlを元にしてClientライブラリーを生成している ([openapi-generatorを使用](https://github.com/cloudnativedaysjp/dreamkast-ui#generate-client-from-openapi-schema) ）。

このとき、swagger.ymlの更新漏れがあったりするとdreamkastとdreamkast-uiで差が発生する可能性がある。また、dreamkast-ui側を更新していないとClientライブラリーが更新されないことになり、トラブルの元になる。

そこで、以下を行いdreamkast-api-docsを廃止する。

1. 現在swagger.ymlのマスターはdreamkast-api-docs上にあるが、これをdreamkastに移動する。具体的には、dreamkast-api-docs上のswagger.ymlをdreamkastにコピーして差分が確実にない状態とする。
2. dreamkast-api-docsのswagger.ymlを更新した時にapiのmockを提供するコンテナイメージをビルドするGithubActionがあるので、これをdreamkastに移動する。
4. dreamkast-api-docsをアーカイブする
5. dreamkastでswagger.ymlを更新した時、dreamkast-ui側のswagger.ymlの更新とClientライブラリーの自動生成を行いdreamkast-uiにPRを作るGithubActionをdreamkastに追加する

**Comment by hrk091** [comment]
@jacopen @takaishi 
dreamkast-api-docsをアーカイブしようと思ったのですが、権限がなくてできませんでした。アーカイブしていただけると助かります:bow:
