### ISSUE TITLE
PermalinkのTwitterアカウントを分けて表示してほしい

### ISSUE THREAD

**Issue by sharasoujyu** [cloudnativedaysjp/dreamkast#1337]
登壇者が複数名の場合も
Twitterアカウントを分けて複数登録したいというご要望をいただいています。
https://event.cloudnativedays.jp/cnsec2022/talks/1450

(現在、できない旨お伝えしています。優先順位は低くてよいそうですが、再度ご要望をいただきました。
ご検討よろしくお願いいたします。)

**Comment by jacopen** [comment]
こちら #590 との重複になりますので既存チケットのほうで対応しますねー

**Comment by sharasoujyu** [comment]
失礼しました。よろしくお願いいたします。closeします。
