### ISSUE TITLE
/talks のリクエストに失敗する

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast#1348]
talksの一覧を取得したく、次のコマンドを実行しても「サーバーエラーが発生しました」と出力されて失敗する。

`curl -X GET -H "Authorization: Bearer $TOKEN" "https://staging.dev.cloudnativedays.jp/api/v1/talks?eventAbbr=cnsec2022`

これについて、@jacopen さんからのアドバイスにより、以下のようにすることで動作することはわかった。

`curl -X GET -H "Authorization: Bearer $TOKEN" "https://staging.dev.cloudnativedays.jp/api/v1/talks?eventAbbr=cnsec2022&conferenceDayIds=16"`

ただ、2Days開催の場合などは投げ分けなければならず、本来であれば `conferenceDayIds` は不要とのことで修正してほしい。

ref: https://cloudnativedays.slack.com/archives/C0204MGK6V6/p1658772847689039

**Comment by takaishi** [comment]
これ、たぶんseed csvのtalkにconference_day_idがnullのデータがあるのが原因だと思う。
