### ISSUE TITLE
初回セッション登録後の画面が分かりにくい

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#135]
以下、触ってみて感じた改善点です。対応可能であればご検討ください:bow:

- 初回のセッション登録後、セッション一覧画面の下に表示される「セッションを登録する」ボタンが分かりにくい
    - 実際の挙動は、既に登録済みのセッションを変更することになるので、「セッションを変更する」としてはどうでしょうか？

- ナビゲーションのTimetableからも、登録済みのセッションを変更できますが、導線含めて分かりにくい気がします。何らかガイダンスやメッセージがあるとベターかと思いました。
   - 例えば「Timetableで、登録済みのセッションを変更できます」など

-「 登録情報変更」に、登録セッションの変更への導線があっても良いかも

**Comment by jacopen** [comment]
なるほどー、確かに。
一つ目は瞬殺なのでサクッと入れちゃいます。

二つ目はちょっといいやり方検討してみますね

**Comment by jacopen** [comment]
@nabemasat 
https://cndt-dreamka-improve-na-ymsdno.herokuapp.com/cndt2020　
にレビューアプリ上がっているので確認していただければ
