### ISSUE TITLE
セッションを変更したときに選択状態が切り替わらない

### ISSUE THREAD

**Issue by kyohmizu** [cloudnativedaysjp/dreamkast#144]
右上の「Timetable」をクリックしてタイムテーブルに遷移した場合、同時間帯の別のセッションを選択するとチェック状態は切り替わりますが、選択（セッションの色が濃くなっている）状態が切り替わりません。
マイページの「聴講予定セッションを変更する」から画面遷移した場合は正しく切り替わります。

**Comment by jacopen** [comment]
ありがとうございますー。こちら既知の問題なので、どこかで対応しますね
