### ISSUE TITLE
タイムテーブル変更時にキーノートの選択が一部外れる

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast#145]
タイムテーブルの初回登録時、キーノートを選択すると以下のようにすべてのキーノートが選択されている。
![image](https://user-images.githubusercontent.com/5129906/87666131-08d51380-c7a3-11ea-8b7d-8db266480a85.png)

これを保存し、変更を行うと次のようにキーノート4,5が選択されない
![image](https://user-images.githubusercontent.com/5129906/87666187-1f7b6a80-c7a3-11ea-8fee-3de5014cdce8.png)

**Comment by jacopen** [comment]
あぁー、なるほど・・・ ちょっと対策考えます(ちょっと難易度高め・・・)
