### ISSUE TITLE
新規登録する時に入力間違い(違反)があってもアンケートが表示されてしまう

### ISSUE THREAD

**Issue by makocchi-git** [cloudnativedaysjp/dreamkast#146]

**Comment by jacopen** [comment]
あ～～～なるほど

**Comment by MasayaAoyama** [comment]
@makocchi-git これってどのタイミングでしょうか？

例えばメアド間違いをした状態で
![image](https://user-images.githubusercontent.com/8783194/87693968-8fe8b280-c7c8-11ea-851a-294b0715bafa.png)

登録をおしてもページ遷移せずにKarteは表示されないのかなと思ったのですが
![image](https://user-images.githubusercontent.com/8783194/87693999-9840ed80-c7c8-11ea-888c-89243207af01.png)

**Comment by makocchi-git** [comment]
電話番号を string にした時に起きます
メアドはその場で validation されるんだけど、電話番号は違うぽいんだよね

<img width="1367" alt="スクリーンショット 2020-07-17 12 11 52" src="https://user-images.githubusercontent.com/1947929/87744574-c2c19380-c826-11ea-91bb-154235b8b20f.png">

**Comment by jacopen** [comment]
Blankもしくはメアドについてはブラウザの機能としてバリデーションが可能なんですが、電話番号についてはJSとかで実装するしかなくて、面倒なのでサーバーサイドでのバリデーションにしてます

なので、電話番号の形式違いのときは画面のリダイレクトが発生していて、そのタイミングで出てるんかなーと。
ただ、URLは変わらないはずなのでKarte側で除外されないのが謎

**Comment by MasayaAoyama** [comment]
ふむふむ。確認してみます。リダイレクトURLが厳密にはどっか挟んでるとかあるかもですねぇ　見てみます

**Comment by MasayaAoyama** [comment]
リダイレクト先が /registration じゃなくて cndt2020/profiles っぽい。
profiles も除外しちゃいます。

**Comment by MasayaAoyama** [comment]
@makocchi-git 
こちら確認済みです。
別のアカウント・別のブラウザ（またはシークレットウィンドウ）で確認いただけますか？

**Comment by makocchi-git** [comment]
こちらも修正確認できました
ってことでこちらは close しておきますね
