### ISSUE TITLE
勤務先役職が未入力のメッセージ

### ISSUE THREAD

**Issue by kyohmizu** [cloudnativedaysjp/dreamkast#148]
他の入力項目は未入力でエラーになりますが、勤務先役職は画像のメッセージが表示されます。

![image](https://user-images.githubusercontent.com/17077621/87672197-87cf4980-c7ad-11ea-8d63-1e0c976f5f89.png)

**Comment by jacopen** [comment]
ありがとうございます、ブラウザ側のバリデーションとRails側のバリデーションを2重がけしてたんですが、ブラウザ側のバリデーションがtypoにより役職のところしか有効になっていなかったです・。。
