### ISSUE TITLE
CFP投票ボタンを作る

### ISSUE THREAD

**Issue by ystkfujii** [cloudnativedaysjp/dreamkast#1486]
## Summary

`https://event.cloudnativedays.jp/cndt2022/talks`に投票ボタンを作る

## 投票ボタンの動作

- [投票用のAPI](https://github.com/cloudnativedaysjp/dreamkast-functions/issues/4)を実行する
- ボタン押下時にグローバルIPごとに１投票になります とかを表示するだけで良い？... 🤔 

## 修正箇所予想

- `talks/index.html.erb`にbuttonを作る
- buttonはgetElementByIdとかでidとってaddEventListenerで実装？
  - もっと良いやり方がありそう...
- API実行はfetchを叩けばよい？

**Comment by jacopen** [comment]
画面遷移のほう書いてみました！
https://miro.com/app/board/uXjVOb-gTrw=/?moveToWidget=3458764533801689597&cot=14
