### ISSUE TITLE
[Umbrella issue] CFP投票機能を実装する

### ISSUE THREAD

**Issue by ystkfujii** [cloudnativedaysjp/dreamkast#1487]
discussions: https://github.com/cloudnativedaysjp/dreamkast/discussions/1358

やること

- https://github.com/cloudnativedaysjp/dreamkast/issues/1486
- https://github.com/cloudnativedaysjp/dreamkast-functions/issues/5
- https://github.com/cloudnativedaysjp/dreamkast-functions/issues/4 

やらないこと

- 現在の投票数は表示しない

**Comment by jacopen** [comment]
イメージあってます！

**Comment by ystkfujii** [comment]
これも必要

- https://github.com/cloudnativedaysjp/dreamkast-functions/issues/9

**Comment by jacopen** [comment]
無事リリースされたのでクローズ！
