### ISSUE TITLE
IBM向け特殊要件の有無について確認する

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#1496]
CNDT2020では申込みフォームにIBM向けの特殊フォームがありました。

- IBMからのメールを希望する
- IBMからの電話を希望する
- IBMからの郵便を希望する

のチェックボックスを用意し、リードにこの項目のチェック有無について出力をするという要件でした。

今回そのような特殊要件があるかどうか、確認をお願いします

due: 2022/09/30

**Comment by nabemasat** [comment]
@jacopen 
ありがとうございます。今回、確認したところIBMがスポンサーに入ったため、フォームでの対応必要です。
文面などについては、宮奈さん @miyana0907 に確認して追ってコメントします。

**Comment by nabemasat** [comment]
@jacopen 
お待たせいたしました。宮奈さんに確認したところ、

- MS、IBM、レッドハットの3社で独自パーミッションが必要　※ レッドハットはIBMとは別になるので注意
- サイトのスクリーンショットを見せる必要（３社とも入っている必要）

とのことでした。

そこで、下記のスケジュールのスケジュールで進めたいのですが、お願いできますでしょうか:bow:
- 9/29までに各社の文面をDkチームに提出
- 10/5までにフォームに実装
- 10/5 インプレスから確認用スクリーンショット提出
- 10/7 スポンサー各社の確認期限

**Comment by jacopen** [comment]
ぉぉーなるほどレッドハット。
MSとIBMは既存実装があるのでそれを有効化するだけでいけます。レッドハットについては実装要ですが、まあやり方は一緒なのでよほど特殊な要求じゃない限りはそれほど時間かからないと思います。
なので、提案頂いているスケジュールでOKです

**Comment by nabemasat** [comment]
IBM・レッドハット：本日中に提出
日本マイクロソフト：「個別のパーミッションは不要」で確定（対応不要）

**Comment by nabemasat** [comment]
@jacopen お待たせしました。フォームに設置する文面が来ましたのでご確認ください。

- 文面はIBMとレッドハットでほぼ一緒だが、別々で設置が必要とのこと
- 日本マイクロソフトは個別のパーミッションが不要になったので、チェックボックスの設置は不要
- 文面確認後、若干修正が入る可能性あり

とのことです。

**Comment by nabemasat** [comment]
IBM文言

# 協賛企業の日本アイ・ビー・エム株式会社からのご案内方法について

IBMおよびIBMの[子会社、関連会社](https://www.ibm.com/ibm/jp/ja/keireki.pdf#subsidiaries)から、製品、サービス、オファリングに関する情報をお送りさせていただく場合があります。
ご希望の連絡方法を以下よりご選択下さい。
ご選択のない場合、以下のいずれかの方法により、上記情報をお送りさせていただく場合があります。

(チェックボックス）
□ 1.e-メールを希望する
■ 2.電話を希望する（←デフォルトでチェック）

マーケティングに関する同意は、[opt-out request](https://www.ibm.com/account/reg/jp-ja/signup?formid=urx-42537)を送信することにより、いつでも取り消すことができます。また、該当の E メール内の、購読を中止するためのリンクをクリックすることで、マーケティングに関する E メールの受信を中止することができます。
処理に関する詳しい情報は、[IBM プライバシー・ステートメント](https://www.ibm.com/jp-ja/privacy)をご覧ください。このフォームを送信することで、私は IBM プライバシー・ステートメントを読み、これを理解したものとします。

**Comment by nabemasat** [comment]
レッドハット文言

# 協賛企業のレッドハット株式会社からのご案内方法について

レッドハットおよびレッドハットの子会社、関連会社から、製品、サービス、オファリングに関する情報をお送りさせていただく場合があります。
ご希望の連絡方法を以下よりご選択下さい。
ご選択のない場合、以下のいずれかの方法により、上記情報をお送りさせていただく場合があります。

(チェックボックス）
□ 1.e-メールを希望する
■ 2.電話を希望する（←デフォルトでチェック）

マーケティングに関する同意は、レッドハットの[フィードバックフォーム](https://www.redhat.com/en/contact?contact=customer-service)を用いてレッドハットに連絡することで、いつでも取り消すことができます。また、該当の E メール内の、購読を中止するためのリンクをクリックすることで、マーケティングに関する E メールの受信を中止することができます。
処理に関する詳しい情報は、[RED HATプライバシーステートメント](https://www.redhat.com/ja/privacy-statement)をご覧ください。このフォームを送信することで、私は レッドハット プライバシーステートメントを読み、これを理解したものとします。

**Comment by jacopen** [comment]
@nabemasat 変えさせるのは難しいと思いますが、電話するにデフォルトチェックを入れるのは参加者からの不満が多そうです。せめてメール側をデフォルトにするよう交渉の余地はありますか？

**Comment by nabemasat** [comment]
@jacopen 遅くなりすみません🙇‍♂️本日事務局ミーティングがあるので相談してみます。

**Comment by nabemasat** [comment]
@jacopen 
IBM/レッドハットのチェックボックスの件、インプレスさんの両社の営業担当から担当者に確認中です。
明日にはお返事あると思いますので、しばしお待ちください。

折り返しですみません。レッドハットについて、文面を下記のように修正してほしいとの依頼が来ています。

------

（チェックボックス以降）
マーケティングに関する同意は、opt-out requestを送信することにより、いつでも取り消すことができます。また、該当の E メール内の、購読を中止するためのリンクをクリックすることで、マーケティングに関する E メールの受信を中止することができます。

------

opt-out requestのリンクは入手待ちです。すみません。二度手間になってしまうのですが、文面だけ実装くださいとのことです:bow:

**Comment by takaishi** [comment]
すみません、スケジュール見落としていました。一旦現状もらっている仕様で今日中に実装します。
