### ISSUE TITLE
SpeakerのSNSがどちらもTwitterに遷移する

### ISSUE THREAD

**Issue by kaedemalu** [cloudnativedaysjp/dreamkast#150]
`/speakers`にて、SNSアイコンがあるが、TwitterとGithubのアイコンをどちらクリックしてもTwitterに遷移する。
該当のソースはおそらくこれですかね。
(投入しているデータに依存しているものだったらすみません。。）
https://github.com/cloudnativedaysjp/dreamkast/blob/master/app/views/speakers/show.html.erb

**Comment by jacopen** [comment]
うっかりミスしてました
