### ISSUE TITLE
Dreamkastからのメール送信機能

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#151]
例えばセッション登録したら
『以下のセッションを登録しました』
的なメールが送られる機能

**Comment by jacopen** [comment]
SESがいいのかSendGridがいいのかちょっと情報収集する

**Comment by takaishi** [comment]
ビデオファイルの提出完了時の通知は https://github.com/cloudnativedaysjp/dreamkast/issues/443 で実施中

**Comment by takaishi** [comment]
ビデオファイル提出時の通知は実装済み
その他はまた次回必要なら実装かな
