### ISSUE TITLE
申込フォームへのMS専用項目の実装

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#155]
IBMに続き申し訳ないです。MSについても申込フォームに独自許諾の実装が必要になりました。。すみませんが、下記の項目の実装をお願いします:bow:

-----
### 日本マイクロソフトからの情報提供

日本マイクロソフト株式会社から情報提供を希望される場合、申し込み者情報に記載いただいた内容を日本マイクロソフト株式会社へ提供させていただきます。利用目的は当該企業の製品・サービスに関する情報またはマーケティング活動に関する情報をお知らせすることです。個人情報の取り扱いにつきましては、日本マイクロソフト株式会社のプライバシーポリシーに準拠します

□ 日本マイクロソフト株式会社への個人情報提供に同意する
[(プライバシーステートメント)](https://privacy.microsoft.com/ja-jp/privacystatement/)

------

(プライバシーステートメント)のリンク先：
https://privacy.microsoft.com/ja-jp/privacystatement/

※任意回答
※デフォルトではチェックは全て空欄、
オーディエンス側が能動的に✔を入れる形にする

**Comment by jacopen** [comment]
ぐえー

**Comment by jacopen** [comment]
@nabemasat Stagingで確認お願いします

**Comment by nabemasat** [comment]
@jacopen ありがとうございました！こちらで問題ございません！
