### ISSUE TITLE
スマホ・セッション詳細のCloseボタンは上にしたほうが良いかも

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#156]
※主観ですが、画面いっぱいに表示されるので、元の画面に戻そうとして一瞬戸惑う人もいるかなーと思いました。（見やすいので、フル表示自体は良いと思います！）

![IMG_7BBD2391D828-1](https://user-images.githubusercontent.com/31978147/87767697-fff14a00-c855-11ea-9efb-8980d7d45580.jpeg)

**Comment by jacopen** [comment]
@nabemasat Stagingで確認お願いします

**Comment by nabemasat** [comment]
ありがとうございます！
上部閉じるボタン、確認しました！
