### ISSUE TITLE
Twitter/GitHubの画面遷移

### ISSUE THREAD

**Issue by cyberblack28** [cloudnativedaysjp/dreamkast#157]
タイムテーブルでセッションの詳細情報を表示した状態で、TwitterまたはGitHubボタンをクリックして画面が遷移しますが、画面遷移後にブラウザの戻るボタンを押して戻るとリロードされてしまいます。

個人的な好みで恐縮ですが、Twitter/GitHubは別タブ起動の方が、タブ切り替えで登壇者の詳細情報とSNS画面を見ることができてUI的に良いと思いました。

**Comment by jacopen** [comment]
スマホでの使い勝手考慮すると、どっちが良いかは明確に判断が付かないのでペンディングにさせてください
