### ISSUE TITLE
Sign Up時に「戻る」とエラーになる

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#159]
Auth 0 にメールアドレスを登録し、申込フォームに進んだ際、うっかり戻ってしまうと、
Some body keys are invalid
とエラーになる。また元のサインナップ画面に戻ろうとしたり、再度ホームからログインしようとすると、このエラーが出る
![IMG_1144](https://user-images.githubusercontent.com/31978147/87769272-5e1f2c80-c858-11ea-9e89-c0174a7dc5bb.jpg)

戻り続けると、ログインした状態の画面に復帰したり、あるいはKARTEのアンケートに移ったりする

まとまってなくてすみませんが、Auth0でのログイン時 or 申込フォーム入力時などにブラウザバックすると、挙動が怪しくなります。

**Comment by jacopen** [comment]
うーん、これの対応は結構難しいですねぇ。エラー画面じゃなくてトップページにリダイレクトする感じかな・・・

**Comment by jacopen** [comment]
@nabemasat  ブラウザの戻るボタンで再現しないのですが、環境の情報を教えてもらえますか？

**Comment by nabemasat** [comment]
@jacopen 遅くなりすみません！
iPhone 11 Pro
iOS 13.5.1
Safari 13.1.1
となります。

**Comment by jacopen** [comment]
@nabemasat こちら治った可能性があるのでStagingで確認してもらえますか？

**Comment by nabemasat** [comment]
動作支障ありませんでした！
遅くなりましたがクローズします
