### ISSUE TITLE
セッション情報の管理

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#16]
紛らわしいけど発表のほうのセッション。

タイムテーブルで管理するんじゃなくてそれぞれの発表をDBのエントリとして管理して、そこからタイムテーブルを生成するようにしたほうがいい

**Comment by nabemasat** [comment]
複数登壇の場合の、写真／プロフィール／SNS情報掲載に対応頂けると助かります！
（多くて2人までで良さそう）

**Comment by takaishi** [comment]
https://github.com/cloudnativedaysjp/dreamkast/pull/41 でDBでセッション（トーク）を管理できるようになっているはず

**Comment by takaishi** [comment]
写真の表示を https://github.com/cloudnativedaysjp/dreamkast/issues/71 でやれば終わりだと思うのでクローズしておきまし
