### ISSUE TITLE
レスポンシブのブレークポイント

### ISSUE THREAD

**Issue by cyberblack28** [cloudnativedaysjp/dreamkast#160]
iPad,iPad miniの縦位置でのタイムテーブル表示がブレークポイントのギリギリ？左側が見切れて、スクロールもされない。

![IMG_0008](https://user-images.githubusercontent.com/6419022/87772205-5b263b00-c85c-11ea-9750-8bbd62215c57.PNG)

※iPad,iPad miniの横位置は問題ありません。

**Comment by jacopen** [comment]
なるほど、確認します

**Comment by jacopen** [comment]
@cyberblack28 iPadの世代教えてもらえますか？ iPad Proだと起きない様子

**Comment by jacopen** [comment]
あ、うそ、再現しました :p

**Comment by cyberblack28** [comment]
一応以下で確認しました。

11インチiPad Pro (第1世代)
iPad mini 2
