### ISSUE TITLE
同一時間帯の複数セッションの登録を許容するかどうか

### ISSUE THREAD

**Issue by suzukin** [cloudnativedaysjp/dreamkast#161]
現状、タイムテーブルでセッション登録する際に、同じ時間帯で1つしか選択できません。確かにライブ視聴は現実的には1つですが、オンライン化によって参加者の視聴スタイル（アーカイブ視聴含む）が変化している中で、事前登録を1つだけに絞る必要があるのか、個人的には再考の余地があると思っています。すでに議論済みだったらごめんなさい。

なお機能要件として正しく、同一時間帯は1つのみ選択とする場合も、問い合わせ軽減のためその旨の説明があると良いかもしれないです。

`例; セッション登録は同一時間帯1つのみとなります。選択していないセッションも一部を除きアーカイブ動画として視聴できるようになります。`

**Comment by jacopen** [comment]
こちら議論済みで、いったん1セッション選択という形で進めています。

説明については同意なのでどこかど入れる余地がるか考えてみますねー
