### ISSUE TITLE
/talk を取得する際に conferenceDayIds が必要

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast#1616]
タイトル通り。
詳細は以下にて。
https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1667455929479639

なお、急ぎではないので、本件の修正はCNDT2022終了後でOKです。

**Comment by takaishi** [comment]
swagger.yml上だとrequire=false。
また、実装的にもconferenceDayIdsがない場合は使わないようになっている。

```ruby
    @talks = Talk.includes([:conference, :conference_day, :talk_time, :talk_difficulty, :talk_category, :talks_speakers, :video, :speakers]).where(query)
    if params[:conferenceDayIds]
      @talks = @talks.where(params[:conferenceDayIds].split(',').map { |id| "conference_day_id = #{id}" }.join(' OR '))
    end
```

で、start_timeがないtalkが含まれるとエラーになるようだ。

**Comment by takaishi** [comment]
conference day idを指定しない場合、rejectedなtalkもレスポンスに含めようとしていて、そういうtalkはstart_timeとかもってないのでエラーになる。

**Comment by takaishi** [comment]
acceptedなセッションとintermission系のみ返すようにするか、rejectedなセッションの場合はstart_timeなどにnilをいれるようにするか。

**Comment by takaishi** [comment]
> acceptedなセッションとintermission系のみ返すようにする

こっちの方がいい。rejectedなものも必要な場合はproposals apiを用意してそっちを使うのが望ましいはず。
