### ISSUE TITLE
セッションごとのシェアボタンとOGPの設定

### ISSUE THREAD

**Issue by suzukin** [cloudnativedaysjp/dreamkast#162]
すでにセッションごとのパーマリンクがあるのでTwitter, FB等のシェアボタンの実装はそんなに問題ではない気がしました。

OGPに関しては最低限の素材（タイトル、登壇者名、顔写真）があれば、Photoshopのデータセット機能で実現できそうです。
https://www.tam-tam.co.jp/tipsnote/tool/post16079.html

**Comment by jacopen** [comment]
セッションごとのパーマリンクはちょうど同じことを想像してたところでした。
ただ実装にあたっては細々とした変更が必要なので、初期リリースに乗せるかどうかは要検討って感じです。次のバージョンには載せられるかな、、、

もしやるとするとOGPの設定は必要ですね。考慮から漏れていたのでありがとうございます
