### ISSUE TITLE
Co-located Handsonページ内のインデックスのアップデート

### ISSUE THREAD

**Issue by capsmalt** [cloudnativedaysjp/dreamkast#1628]
インデックス部分にRed Hatの部分を追記頂けますと幸いです。

<img width="1019" alt="Screen Shot 2022-11-08 at 13 23 25" src="https://user-images.githubusercontent.com/6401075/200474684-e8ccce87-fec4-4cac-9478-197031a495b2.png">

**Comment by takaishi** [comment]
https://github.com/cloudnativedaysjp/dreamkast/pull/1629 で対応済みなのでクローズします

https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1667881499216219
