### ISSUE TITLE
本番に休憩などのセッション情報を追加する

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast#1643]

**Comment by TakumaNakagame** [comment]
サイマル配信対象について、セッションタイトルを次のように作成していただきたいです。

| セッション | トラックA | トラックA以外 |
| --- | --- | --- |
| オープニング | オープニング | トラックAにてオープニングを実施中！ |
| キーノート | ※現状ママ | トラックAにてキーノートを実施中！ |
| クロージング | クロージング | トラックAにてクロージングを実施中！ |

- 各文言については具体的な指定はなく、以下の意図通りになっていればいいので多少変更してもOKです。
- オープニング、クロージング、キーノートについてはサイマル配信にする都合上、トラックB以降のタイトルのプレフィックスを、全体通して同一にしています（`トラックAにて.+`）
- よるイベについては確認します

**Comment by takaishi** [comment]
これはCNDT2022向けのIssueなのでクローズ
