### ISSUE TITLE
Redis Cacheを入れてDBの負荷を軽減する

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#169]
あちこちでDBからデータを取得しているが、頻繁に更新されないデータも多い(ConferenceやCategory, Difficultyなど)ので、Redis Cacheを活用して負荷を減らす

**Comment by takaishi** [comment]
👀

**Comment by takaishi** [comment]
Railsのキャッシュ、そもそもいろいろあるらしいということを知った：

https://railsguides.jp/caching_with_rails.html

**Comment by takaishi** [comment]
アクション内だとSQLキャッシュがRailsサイドで働いていることに気づいた。なので、あるアクション内で同じクエリが２回以上発行された場合、２回目以降はRDBにクエリが送られずにキャッシュが使われるようだ。

で、このissueのスコープは低レベルキャッシュで実現するのが良いのだろう。他にもアクションキャッシュやパーシャルキャッシュなどあるけど、ユーザーごとに内容が変わる動的なページが多いのでうまく使えないと意図しないページ表示がされる可能性がある。ユーザーによって内容が変わらないテーブルからやるのが良い、と

**Comment by takaishi** [comment]
📝 MySQLのクエリキャッシュは8.0で削除されたらしい。

**Comment by takaishi** [comment]
これ、キャッシュなしで事前のイベントでトライアルして、どのくらい負担になるか見てから着手する方がいいかもしれないな。可観測性を高めるのを先にやるのが良いのではないか？

**Comment by jacopen** [comment]
一旦これはペンディングにしてSponsorページ実装を優先かなー

モニタリングはClearDBのダッシュボードまかせ

**Comment by jacopen** [comment]
CNDTをやった結果これは無くて良さそうなので閉じ
