### ISSUE TITLE
IVS/Media*まわりの処理をRailsから剥がしたい

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast#1696]
今リソース作成・削除はDkから行っているのだが、ちょっと変更したい時にRailsのコードを触る必要があって複雑。作成削除の実行自体はDkのAdmin画面から行うのでよいが、処理自体はRailsの外でTerraformやCDKを使って行えるようにしたい。

**Comment by jacopen** [comment]
Dkで引き続きやる & 実装はリファインする とのことなのでこちらはクローズ
