### ISSUE TITLE
CoC/プライバシーポリシー表示時のログインボタンの取り扱い

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#174]
※優先度は低いので、サイトオープン後の対応でOKです

CoCとプライバシーポリシーのページでは
「参加申し込み／ログイン」ボタンが表示されているが、
既にログインしている状態だとエラーになってしまう

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/31978147/87867272-3bab2180-c9c6-11ea-8456-11975be14b8a.png">

<img width="777" alt="image" src="https://user-images.githubusercontent.com/31978147/87867283-554c6900-c9c6-11ea-93ce-bb6fe610e64f.png">

タイムテーブルと同様、ログイン時の表示に切り替わっていてほしい
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/31978147/87867305-9cd2f500-c9c6-11ea-89ff-0a4e829ea571.png">

**Comment by jacopen** [comment]
あ～、なるほど、これは考慮漏れですね。対応します
