### ISSUE TITLE
Production環境を構築する

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#177]
- [x] アプリのデプロイ
- [x] アドオンの設定
- [x] Auth0の設定
- [x] ドメインの設定(技術部に依頼)
- [x] Sentryの設定

**Comment by jacopen** [comment]
@nabemasat 

技術部のほうにDNSの設定を依頼していただければ

event.cloudnativedays.jp に CNAME   comparative-elderberry-iyhd7ola778ul9txea3u1fk8.herokudns.com
の設定をお願いします

**Comment by nabemasat** [comment]
インプレス技術部に、伊藤さん経由で依頼しました

**Comment by nabemasat** [comment]
@jacopen 

設定完了しました
伊藤様

お疲れ様です。IW 横田です。
DNS登録を行いましたのでご確認下さい。

# dig event.cloudnativedays.jp CNAME +noall +ans

; <<>> DiG 9.3.6-P1-RedHat-9.3.6-4.P1.el5_4.2 <<>> event.cloudnativedays.jp CNAME +noall +ans
;; global options:  printcmd
event.cloudnativedays.jp. 294   IN      CNAME   comparative-elderberry-iyhd7ola778ul9txea3u1fk8.herokudns.com.

よろしくお願い致します。

**Comment by takaishi** [comment]
https://cndt2020.cloudnativedays.jp/ からの導線を用意しないとだった。GitHub Pagesってリダイレクトしたりできるのかな
