### ISSUE TITLE
CICD2023: CFP採択結果が反映されない

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#1791]
すみません:bow: 下記ご確認をお願いできますか。

状況：
CFPの採択結果を保存したが、表示がセッションリストに反映されていない
https://event.cloudnativedays.jp/cicd2023/talks

関連する状況：
・Conference Statusは「CFPの結果公開: 公開」に設定されている
・念の為、ステージング環境でも試したが、同様にCFP採択結果が反映されない
・管理画面 https://event.cloudnativedays.jp/cicd2023/admin/timetables には、
　採択済みのセッションが反映されている

**Comment by takaishi** [comment]
@nabemasat 修正して、今は採択されたもののみが表示されていると思います。確認をお願いします。

**Comment by nabemasat** [comment]
@takaishi ありがとうございます！修正確認できました！
