### ISSUE TITLE
[2023/02/14 ~] CICD2023プレイベントのRaketask実施依頼

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast#1812]
## 概要
表題通り、プレイベント向けRaketaskの実施をお願いします。
2023/02/13 までにタイムテーブルが確定するようなので、以下の内容を含んだTalksの登録をお願いします。
※休憩または移動時間は、タイムテーブル次第でなくなる可能性があります。

- セッション
- 休憩・移動時間
- 開始までお待ち下さい

## 作業締め切り
2月17日頃まで（ざっくり目安なので調整可能です

ref: https://cloudnativedays.slack.com/archives/C04E97GMMJ7/p1675940840449379

**Comment by takaishi** [comment]
実行済み
