### ISSUE TITLE
/registration における業種等のカテゴライズに optgroup を使ってわかりやすくする。

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast#1832]
## 概要
現在、イベント登録時の業種登録などで、`～業種名～` にてカテゴライズをしている
これにインデント等を付与してわかりやすくしたい。

## 内容
HTMLの`optgroup`を使うことで、以下のようにグルーピングが可能なよう。
※ChromeのHTML編集でやってみた

![image](https://user-images.githubusercontent.com/5129906/221418535-a4317967-3a7b-43aa-ae17-636ee0876001.png)

```
<option disabled="disabled" value="1">選択してください</option>
    <optgroup label="～製造業関連～">
        <option value="3">電気機器製造業</option>
        <option value="4">通信機器関連製造業</option>
        <option value="5">電子部品/デバイス/電子回路製造業</option>
        <option value="6">自動車/輸送用機器製造業</option>
        <option value="7">産業用/事務用機器製造業</option>
        <option value="8">食料品/飲料製造業</option>
        <option value="9">医薬品/化学製品製造</option>
        <option value="10">素材関連製造業</option>
        <option value="11">IT関連製造業</option>
        <option value="12">その他の製造業</option>
    </optgroup>
<option disabled="disabled" value="13">～電気・ガス・水道業関連～</option>
```

現状では、カテゴリ名の目立ちが足りないと感じたので、ぜひ↑のような形で実装してもらえるとわかりやすくなると思います！

### 参考リンク
- https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1677423097934409
- https://developer.mozilla.org/ja/docs/Web/HTML/Element/optgroup

**Comment by jacopen** [comment]
現状この実装はこのへん
https://github.com/cloudnativedaysjp/dreamkast/blob/main/app/views/profiles/_form.html.erb#L59

このFormModelsでdisabledが付いているところは選択出来ないようにしてある。

ここを`grouped_collection_select` を使うようにすれば実現できそう
https://railsdoc.com/page/grouped_collection_select
