### ISSUE TITLE
前日準備のリハ向けにステージング環境にRaketaskを実行してほしい

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast#1850]
## 概要
表題通り、前日（3月19日）リハ向けRaketaskの実施をお願いします。
具体的には以下の2つの作業をお願いしたいです

1. B,Cトラックのセッション情報（本番相当）や休憩などがステージング環境に登録されること
2. リハで使ったステージングのAトラックのセッションの日付を前日に変更する

### 期待する結果
3月19日のセッションとして、本番と同様の内容のものが登録される（A~Cトラック全て）

### 1. B,Cトラックのセッション情報（本番相当）や休憩などがステージング環境に登録されること
以下の内容をステージングに追加して下さい
- トラック： B,C 
- イベント日時： 2023/03/19
- セッション： 本番と同一のタイトル（詳細などは不要）
- 休憩
- 開始までお待ち下さい
- よるイベ
- イベントは終了しました

### 2. リハで使ったステージングのAトラックのセッションの日付を前日に変更する
3月4日のリハーサルで使用した、トラックA用のセッションの日付を、3月4日から3月19日に変更して下さい

## 作業締め切り
3月17日頃まで

### 日付の根拠
 前日準備を迎える前に一度確認したいため

**Comment by takaishi** [comment]
@TakumaNakagame 追加済みです
