### ISSUE TITLE
セッションごとの現地参加者数・オンライン参加者数を確認できるようにする

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#1882]

**Comment by takaishi** [comment]
https://github.com/cloudnativedaysjp/dreamkast/issues/1857 でやる

**Comment by takaishi** [comment]
あ、やっぱりissueはわけよう

**Comment by takaishi** [comment]
セッション毎の登録者数はRegisteredTalkを数えたら分かる。現地・オンライン参加はちょっと手間というか、現状チケッットのタイトルで判別するしかないのでタイトルが変わると集計できなくなってしまう。

**Comment by takaishi** [comment]
1つのProfileにキャンセルされていないOrderが複数あったりして、Orderまわりのロジックがおかしそうなのでそこを正常にしてから進めた方がよさそう。
