### ISSUE TITLE
誤ったCSVデータをインポートしたら、ログイン不能になった

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#190]
申し訳ないです:bow:
以下経緯です。

- speakers.csv で、誤ってIDが重複する行を書いてしまう
    - このときは、既存のものを優先し無視
- その後、IDが重複する行を修正（ただし、順番は68->67と、逆になっていた）
- インポートしたら、エラーが出てログイン不能に

追記：しばらく経ったら復活しました

**Comment by jacopen** [comment]
えっ、しばらくしたら復活･･･誤ったデータが入っていて復活するってのはちょっと理由が分からないですが確認します

**Comment by jacopen** [comment]
ちなみに書かれている処理手順では特に問題は起きないはずですね。なんだろう・・・

**Comment by jacopen** [comment]
まずID重複にはこちらのSentryに記録がありました。
https://sentry.io/share/issue/a09a0d06b3394340af683cb23ce83a3b/

**Comment by jacopen** [comment]
その後、Mysql2::Error: User 'b576ab9b743660' has exceeded the 'max_questions' resource (current value: 3600)
が大量に出ていた。
https://sentry.io/share/issue/3ab0655cc1714db481941f96b58c050f/

**Comment by jacopen** [comment]
max_questionsって何だっけ？ と思ったけど、どうやら1時間あたりの

**Comment by jacopen** [comment]
別issueを建てたのでクローズ
