### ISSUE TITLE
CFP募集期間中、 /talks 上でプロポーザル一覧が見えない

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast#1903]
見えていないので見えるようにしないといけない。

- /talks にProposalが見えないの、条件分岐がややこしいので /proposals を追加してそれを表示するようにしたらいい気がした。
- 機能的にもセッション一覧とプロポーザル一覧は分かれていた方がわかりやすい
- それはそれで別途追加するキーノートとかややこしいかもしれないので要検証

**Comment by oshiro3** [comment]
Proposal と Talk で結構別物になってきているように思うのでこの辺り見直す余地がありそうだなと CFP の投票周りの実装してて思いました。

**Comment by takaishi** [comment]
https://github.com/cloudnativedaysjp/dreamkast/pull/1909 で見えるようになった
