### ISSUE TITLE
ClearDBの代替案を検討する

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#192]
Related #190 

ClearDBにはmax_questionsの制限があり、上限を超えてしまうと1時間接続不可になってしまう・・・本番でこれが起きたら死ぬ

なので早急に代替案を検討する

**Comment by jacopen** [comment]
max_questionsについてはこちらに記述あり。
https://w2.cleardb.net/faqs/#multi_7
![image](https://user-images.githubusercontent.com/79102/88206283-fcf8be00-cc88-11ea-8d7c-5b82892da579.png)

無料だと3600クエリ/hour、有償で高いプランでも最大18,000クエリ/hour
内部向けのクエリで3,600クエリ上限当たっているので、本番当日だと18,000は軽く超えちゃうんじゃないか

というかそんな制限があるならPlanのところに書いておいてくれよ・・・
https://elements.heroku.com/addons/cleardb

**Comment by jacopen** [comment]
一部を愚直に実装した結果、ActiveRecordが非効率なクエリを発行しているのは認識していて、高石先生が気づき次第修正してくれてはいる。
あと #169 を行うことでさらにクエリ数を削減することは可能。

しかしながら、どれだけクエリを減らしても18,000を上回らないと約束はできないし、予測も難しい。そして、実際に上限に当たってしまったときの影響が大きすぎる。

ということで、本番はClearDBではない選択肢がほぼ必須かなと思う。

現時点で一番有力なのはAWS RDSかな。
HerokuはAWSで動いているので、同一リージョンのRDSであればレイテンシが低く使えるし、実際そうしている例は多い。ドキュメントも存在する。
https://devcenter.heroku.com/articles/amazon-rds


RDSを第一選択肢として考えたいが、AWSアカウントを別途発行する必要がある。
これは鍋島さん(インプレス)とピークワンさんに相談となる。OKが出たとしても、ピークワンさん内での作業が必要になる上に4連休となるので、来週の公開までに移行するのはスケジュール的に難しい。

18,000query/hourであれば、普通の申し込み程度のトラフィックであれば問題なく捌けると思うので、まずはClearDBでS-inしつつ、どこかのタイミングでRDSにお引っ越しをするという流れになるんじゃないか。

**Comment by nabemasat** [comment]
@jacopen 調査ありがとうございます。発見のきっかけになってよかったです:now:
@Kondo こちら週明けご相談させてください:bow:
(Slackに通知いくかな？)

**Comment by jacopen** [comment]
引っ越し完了のため閉じ
