### ISSUE TITLE
ステージング環境へ検証用タイムテーブル登録依頼

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast#1950]
## 概要
Broadcastの検証会や、前日のリハーサルなど、各種検証のタイミングで利用する、ステージング環境用のタイムテーブル登録をお願いします。

なお、直近では22日のBroadcast検証会で1トラックの検証想定ですが、前日リハーサルでは3トラック同時で利用します。
そのため、作業工数などを鑑みて、今回3トラック分追加したほうが良い場合は、3トラック分追加をお願いします。
難しい場合は、Aトラック分のみ追加をお願いします。

### 締め切り
直近で大変申し訳無いのですが、Broadcast検証で利用するため以下でお願いします:bow:

`2023/06/22 18時`

### 環境
ステージング（staging.dev.cloudnativedays.jp）

### タイムテーブル構成
※キーノートのセットチェンジは念のため入れています。
Dk的に不要ということであれば外してしまって問題ありません。

#### トラックA
開始時間 | 終了時間 | 所要時間 | 内容
-- | -- | -- | --
11:50 | 12:00 | 0:10 | OP
12:00 | 12:20 | 0:20 | キーノート 1
12:20 | 12:25 | 0:05 | セットチェンジ
12:25 | 12:45 | 0:20 | キーノート 2
12:45 | 12:50 | 0:05 | セットチェンジ
12:50 | 13:10 | 0:20 | キーノート 3
13:10 | 13:15 | 0:05 | セットチェンジ
13:15 | 13:35 | 0:20 | キーノート 4
13:35 | 13:40 | 0:05 | セットチェンジ
13:40 | 14:00 | 0:20 | キーノート 5
14:00 | 14:20 | 0:20 | 休憩
14:20 | 15:00 | 0:40 | セッション 1
15:00 | 15:20 | 0:20 | 休憩
15:20 | 16:00 | 0:40 | セッション 2

#### トラックB
※工数的に可能なら、前日に使うので追加してください🙏

開始時間 | 終了時間 | 所要時間 | 内容
-- | -- | -- | --
11:50 | 12:00 | 0:10 | トラックAでOP実施中！
12:00 | 14:00 | 2:00 | トラックAでキーノート実施中！
14:00 | 14:20 | 0:20 | 休憩
14:20 | 15:00 | 0:40 | セッション 1
15:00 | 15:20 | 0:20 | 休憩
15:20 | 16:00 | 0:40 | セッション 2

#### トラックC
※工数的に可能なら、前日に使うので追加してください🙏

開始時間 | 終了時間 | 所要時間 | 内容
-- | -- | -- | --
11:50 | 12:00 | 0:10 | トラックAでOP実施中！
12:00 | 14:00 | 2:00 | トラックAでキーノート実施中！
14:00 | 14:20 | 0:20 | 休憩
14:20 | 15:00 | 0:40 | セッション 1
15:00 | 15:20 | 0:20 | 休憩
15:20 | 16:00 | 0:40 | セッション 2

**Comment by takaishi** [comment]
@TakumaNakagame https://github.com/cloudnativedaysjp/dreamkast/pull/1953 にデータ作成用のタスクを実装しているので、時間など確認をお願いします！
