### ISSUE TITLE
管理画面→Speaker画像登録後、Timetableを表示するとエラー

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#197]
>We're sorry, but something went wrong.
>If you are the application owner check the logs for more information.

エラーが出た操作
- 管理画面>Speakers>スピーカーの写真をアップロード>更新
- ブラウザバックして、Home>Timetableを表示すると上記のエラー
- Home>Speakersの一覧はちゃんと表示される

**Comment by jacopen** [comment]
確認します

**Comment by jacopen** [comment]
Production, Stagingどちらの環境も問題ないように見えますが、どちらの操作で起きましたか？
問題が起きたときは起きた環境と時間を書いていただけると助かりますー

**Comment by jacopen** [comment]
ちなみに管理画面でのブラウザのバックボタンのエラー処理はそこまで作り込んでいないので、あまり使わない方針でお願いしたいです

**Comment by nabemasat** [comment]
他に優先度の高いIssueがあるので、対応しない
