### ISSUE TITLE
Speaker画像のトリミング

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#198]
※運用でカバーできるので優先度は低いです

スピーカー画像が縦長／横長だと、1:1の正方形に圧縮される？
画像の拡大縮小ではなく、いい感じでトリミングしてくれる仕様だと、登録が楽になりそう

**Comment by jacopen** [comment]
ちょっとこちらは当面先でお願いします

**Comment by nabemasat** [comment]
運用で対応。
