### ISSUE TITLE
スピーカーのCSVエクスポート後、追記して再インポートすると画像が表示されない

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#199]
## エクスポート前
<img width="1426" alt="スクリーンショット 2020-07-26 13 18 45" src="https://user-images.githubusercontent.com/31978147/88471372-ab2f8c80-cf43-11ea-99e9-2eb36b8d30ec.png">

- テスト田太郎、SCP-11111に画像を設定している

## エクスポート後
<img width="1483" alt="スクリーンショット 2020-07-26 13 23 35" src="https://user-images.githubusercontent.com/31978147/88471377-bda9c600-cf43-11ea-8a28-36c651f1b043.png">
<img width="1551" alt="スクリーンショット 2020-07-26 13 22 34" src="https://user-images.githubusercontent.com/31978147/88471378-bf738980-cf43-11ea-803b-0e647932f190.png">

- テスト田太郎、SCP-11111設定した画像が表示されなくなっている

## 画像だけを表示すると、XMLでエラーメッセージが表示
<img width="586" alt="スクリーンショット 2020-07-26 13 28 46" src="https://user-images.githubusercontent.com/31978147/88471408-0792ac00-cf44-11ea-9ace-5158a5feda51.png">
<img width="894" alt="スクリーンショット 2020-07-26 13 28 57" src="https://user-images.githubusercontent.com/31978147/88471410-09f50600-cf44-11ea-8b5b-ca6a83df41de.png">

- エクスポートしたCSV
[speaker-2020-07-26-org.txt](https://github.com/cloudnativedaysjp/dreamkast/files/4977132/speaker-2020-07-26-org.txt)
- 追記したCSV
[speaker-2020-07-26-re.txt](https://github.com/cloudnativedaysjp/dreamkast/files/4977133/speaker-2020-07-26-re.txt)

**Comment by nabemasat** [comment]
S3っぽい？
https://www.it-swarm-ja.tech/ja/amazon-s3/%e3%82%ad%e3%83%bc%e3%81%8c%e5%ad%98%e5%9c%a8%e3%81%99%e3%82%8b%e5%a0%b4%e5%90%88%e3%81%a7%e3%82%82s3%e3%81%8b%e3%82%89nosuchkey%e3%82%a8%e3%83%a9%e3%83%bc%e3%81%8c%e8%a1%a8%e7%a4%ba%e3%81%95%e3%82%8c%e3%82%8b/833619676/

**Comment by jacopen** [comment]
こちら確認しますー

**Comment by jacopen** [comment]
@takaishi これ見る時間ある？
どうもDBのカラムだけだとダメっぽい？

**Comment by takaishi** [comment]
わ、なんだろうこれ…

**Comment by takaishi** [comment]
インポート時に既存のスピーカーレコードは削除されるのだけど、その際に画像そのものも削除されていた。その結果、csvを再度インポートした際に404になるようです

**Comment by takaishi** [comment]
なので、インポート時に削除するとまずそう…

**Comment by takaishi** [comment]
インポート時にバリデーションするPRがすでにあるので、これのマージ後に別途対策PRを作成するのが良さそうかな

ref: https://github.com/cloudnativedaysjp/dreamkast/pull/194

**Comment by jacopen** [comment]
そうねぇ。Speakerのほうはdeleteじゃなくてupsert_allでもいいかもなぁ。別PRでやりましょ

**Comment by nabemasat** [comment]
こちらご対応ありがとうございました。
エクスポート→インポートで画像をキープできるようになりましたのでクローズします
