### ISSUE TITLE
「OnAir all reset」ボタンを作る

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast#2000]
/admin/tracks ページにおいて、別日のOnAirが有効になっているケースがちょいちょいある。
この際に、各トラックすべてリセットしていくのは大変なため、これらをリセットするボタンがほしい。

## 実現してほしい機能
「すべてのトラックで、各日程でアクティブなOnAirを削除する」ボタン

## 用途
イベント開始前に本ボタンを実行することで、OnAirステータスが初期化される。
前回イベントや検証などで利用したOnAirステータスがリセットされるため、各日の各トラックのOnAirステータスを見て回る必要がなくなる。

**Comment by jacopen** [comment]
APIのほうが実装されたのでこれは要らない方向で
