### ISSUE TITLE
Proposal APIにKeynoteやスポンサーセッションが含まれてしまっている

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#2076]
スポンサーAPI
https://event.cloudnativedays.jp/api/v1/proposals?eventAbbr=CNDT2023

は、現状Keynoteやスポンサーセッションも情報を出してしまっている。
このAPIはツイートの自動化に使いたいので、これらの情報は省く必要がある

**Comment by takaishi** [comment]
TalkにKeynote/スポンサーセッション/通常セッションなどを識別するためのカラムを追加したほうがよさそう。
