### ISSUE TITLE
SNS登録されていないSpeakerにもアイコンが表示されていて、各SNSのトップページに飛ばされる

### ISSUE THREAD

**Issue by MasayaAoyama** [cloudnativedaysjp/dreamkast#209]
ユーザからの問い合わせがあったので、とりあえずIssueに起票しておきます。

例えば下記のページではTwitter/GitHubの登録はないが、アイコンは設定されていてトップページに飛ぶようになっているようです。
レンダリングの際にif 文で分岐する感じですかね。

https://event.cloudnativedays.jp/cndt2020/talks/53

**Comment by jacopen** [comment]
あー、あんまり考えていなかった・・・なるほど。
今の実装だと確かにユーザー名が空でぶっ込まれてSNSのトップに飛んじゃいますね。
修正はそんなに難しくないので対応します

**Comment by takaishi** [comment]
空の場合はリンクがはられないようになってるのだけどな

https://github.com/cloudnativedaysjp/dreamkast/blob/master/app/views/talks/show.html.erb#L53-L54

**Comment by takaishi** [comment]
なるほど、twitter_idがnilの場合に再現しますね…

**Comment by jacopen** [comment]
なるほど、空文字しか見てなかったのが敗因か。 `blank?` にすればそれだけで終わりかな
