### ISSUE TITLE
StatisticsのCSVエクスポートが機能していない

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#2100]
CSVエクスポートしようとすると、Internal Server Errorになります。
インプレスへの報告時のデータ加工用に必要なので、すみませんがお手すきの時に修正をお願いできますか:bow:

**Comment by takaishi** [comment]
@nabemasat こちら修正しましたので確認ください。

**Comment by nabemasat** [comment]
@takaishi ありがとうございます！問題なく動作しました！
