### ISSUE TITLE
申込者数（全体・セッション別の取得）

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#212]
管理画面で見れる必要はなくて、CSVとかプリミティブな形でOKなので、何らか情報見れると助かります:bow:

用途としては、2～3日に一回データを集計して、集客対策やスポンサーへの報告に使用します。

**Comment by jacopen** [comment]
なんと、２～３日周期だったんですか･･･ 終わった後にまとめて出すのかと思ってました・・・

**Comment by jacopen** [comment]
となると、第１回目のレポート提出がいつなのかが重要になってきますので、期限を決めて欲しいですー

**Comment by jacopen** [comment]
あとCSVだとしてもどういう情報があれば使いやすいか、項目をまとめていただければ。
DBをCSVでダンプするだけなら簡単なのですが、多分それでは厳しいと思うので、イメージするCSVの項目をいただければ

**Comment by nabemasat** [comment]
すみません！これまでも明確に決まっていたわけではないのですが、定期的に集客状況をチェックして報告していました。
第1回目は、来週8/4-5あたりではいかがでしょうか。

>イメージするCSVの項目をいただければ

- Auth0のアカウント作成数（CNDT2020申込者数と同義と見なす）

- talk_id / セッション名 / 登録人数

上記の項目です！

**Comment by jacopen** [comment]
Auth0のアカウント作成数より、ログイン後プロフィール情報を入力したユーザーの数としたいです。
Auth0でログインを試みるとアカウントが作られるんですが、これだけではCNDTには参加できず、プロフィール情報を入力して初めてセッションの閲覧が可能になるので、プロフィール情報数を数えた方がより正確かなと。

ついでにAuth0のユーザー数を取りに行くのが面倒くさいってのも理由としてあります

**Comment by nabemasat** [comment]
なるほど！はい、それで大丈夫です！
