### ISSUE TITLE
特定の条件でevent idが差し替わってしまう？

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#214]
Sentryをみるとちょくちょく `ActionView::Template::Error ` が出ている。
その際のリクエストを確認すると、` /<ユーザー名っぽいもの>/timetables` みたいな形式になっている。

また、CoCページでも  `ActionView::Template::Error ` が出ることがあるようだ。

この原因を調べる

**Comment by takaishi** [comment]
このissueに関係して、`/<ユーザー名っぽいもの>/timetables` へのアクセスは404を返すように https://github.com/cloudnativedaysjp/dreamkast/pull/216 で変更を加えておきます〜。

**Comment by jacopen** [comment]
404は正しく出るようになった。

あと他のTemplate Errorを改めて確認したが、いずれも #291 に起因するものだった。
ということで一旦こちらは閉じ
