### ISSUE TITLE
Adminからユーザーのチェックインの編集が出来るようにする

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#2158]
スマホチェックイン出来なかった人は、事務局側でメモって後からフラグ立てしている。
フラグ立てした情報はリード作成時にCSVをマージしているが、これは手間がかかる作業だ。

Dk側で代理でチェックインにフラグを立てられるようになったら、この手間が減るので助かる

**Comment by takaishi** [comment]
https://github.com/cloudnativedaysjp/dreamkast/pull/2171 で実装済み
