### ISSUE TITLE
録画忘れ防止機能 (事前収録セッション・harvestjob 録画)

### ISSUE THREAD

**Issue by Gaku-Kunimi** [cloudnativedaysjp/dreamkast#2184]
録画したかどうかAPIでとれるようにしたり、Slackに通知して録画忘れ防止機能をつけたい

また、後から公開要望や録画データ要望が上がることが多いので、全セッション録画自体はしておいて公開可能なものだけ公開するようにすることも検討

**Comment by takaishi** [comment]
- 未アーカイブの場合(video_urlが空の場合) slackに1日1回登録するようにした
- ストリーミングリソース削除時に未アーカイブのセッションがある場合ダイアログで確認するようにした
