### ISSUE TITLE
スポンサー募集をトップページとフッターに掲載する

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#2228]
https://cloudnativedays.slack.com/archives/C067YTR2NT0/p1710252352446019

現状DKにスポンサー募集へのリンクがないため、掲載する。

今後のことを考えると、Eventモデルにスポンサーリンクのプロパティを1つ追加して、管理画面から登録できるようにしておくのがよさそう。

登録されていない場合は表示せず、値が入っていたら出すロジックで

**Comment by takaishi** [comment]
表示済み
