### ISSUE TITLE
現地参加の自社セッション参加者チェックインについて

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#2234]
現状：セッション登録フラグ、受付通過フラグのみ
要望：現地セッションの参加フラグを追加

スポンサー企業から、実際に自社のセッションに参加したかどうかも分かるようにしてほしいとの要望。以前は、セッション終了後に、部屋から退出してもらい、部屋に入る際に参加証のバーコードを読み取っていた（デブサミも同様の方法）

具体的には、レッドハット、F5、グーグル・クラウド、New Relic、セールスフォース、Sysdig、Snyk、ジール、データドッグ、mablから。

事務局側としては対応するとしても冬からだと考えていたが、インプレス営業チームからは、CNDSの営業にも影響するので、夏から実装してほしいとのこと。

デメリットは参加者体験が著しく悪化すること。機能開発だけでなく、参加者に負担を掛けないオペレーションも検討する必要。

**Comment by takaishi** [comment]
こちら設計をすすめています
