### ISSUE TITLE
パーマリンクのTwitterシェアで画像が出力されない

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#229]
Slackより
> セッション個別ページで、プロフィール画像を置いているS3のrobots.txtの設定によってog.imageが取得できなくなっているようです。これ直ると嬉しいのでよろしくお願いします……！(cloud-cube？側の制約でどうしようもなかったりするのかな？)

![image](https://user-images.githubusercontent.com/31978147/89138355-4d6bf780-d576-11ea-915f-f50cd7cde1ea.png)

**Comment by takaishi** [comment]
cloud-cubeバケットのrootに置かれたrobots.txtで制御されているようです。このrobots.txtはコントロールできないので、どうしたものか…

```
~ $ curl https://cloud-cube.s3.amazonaws.com/robots.txt
User-agent: *
Disallow: /⏎ 
```

**Comment by jacopen** [comment]
うーむ。
方法としては普通のS3に引っ越すしかないかなぁ。オブジェクトまで引っ越すのは大変なので画像設定し直しになると思うけど・・・

#192  でRDS化も考えないといけなくって、そうなるとAWSアカウントが必要になるので、そのアカウントでS3バケット作る感じかなぁ

**Comment by jacopen** [comment]
CNDOに向けてS3移行は必須なので、それでこれは解消かな。
なので、S3移行後に画像をお引っ越しというのが必要な作業になる。

**Comment by jacopen** [comment]
#429 で解消する見込みなのでこちらは閉じちゃう
