### ISSUE TITLE
ソーシャルログインしているサービスのメールアドレスを変更すると新規登録扱いになる

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast#236]
## 事象
- GitHubでソーシャルログインして登録
- その後GitHubの登録メールアドレスを変更（Primaryアドレスの変更と旧アドレスの削除）
- GitHubのソーシャルログインでログインできず、登録画面が表示される。

## 期待する動作
- GitHub（ソーシャルログイン）のアカウントが同一であれば、メールアドレスを変更しても変わらず利用できる

## 対応
- GitHubに登録していた旧アドレスのGoogleアカウントでソーシャルログインしたところ無事以前の登録内容が表示された

## その他
- ソーシャルログイン時のメールアドレスをKeyにしているため、そのアドレスが変わった関係から本事象が発生した。
  - ref: https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1596642158107300

**Comment by jacopen** [comment]
この問題は、新規ユーザーかどうかの判断をメールアドレスに頼っているのが原因
https://github.com/cloudnativedaysjp/dreamkast/blob/master/app/controllers/concerns/secured.rb#L19

なぜメアドにしたかというと、Auth0のAccount Linkingを無視って複数のソーシャルログインから別ユーザーとして登録した場合にメールアドレスが重複してしまうケースを避けたかったため。

が、確かにソーシャル側のメールアドレスを変更するケースって少なからずあると思うので、ちょっと対策を考えたほうがいいかもしれない。

Auth0のAccount Linking (issue #43) はメアドをキーにして動作するため、ソーシャル側のメアドが変わったときにどういう挙動を示すのかも要調査。

**Comment by jacopen** [comment]
複数ソーシャルログインをしないのであれば、Auth0のAccount Linkingを無効にして、

https://github.com/cloudnativedaysjp/dreamkast/blob/master/app/controllers/profiles_controller.rb#L81-L83
や
https://github.com/cloudnativedaysjp/dreamkast/blob/master/app/controllers/concerns/secured.rb#L19

を sub をキーに検索するようにすれば直せる。が、複数ソーシャルログインできないのも微妙なので、この選択肢はとれない。

**Comment by iaoiui** [comment]
> この問題は、新規ユーザーかどうかの判断をメールアドレスに頼っているのが原因 https://github.com/cloudnativedaysjp/dreamkast/blob/master/app/controllers/concerns/secured.rb#L19
> 
> なぜメアドにしたかというと、Auth0のAccount Linkingを無視って複数のソーシャルログインから別ユーザーとして登録した場合にメールアドレスが重複してしまうケースを避けたかったため。
> 
> が、確かにソーシャル側のメールアドレスを変更するケースって少なからずあると思うので、ちょっと対策を考えたほうがいいかもしれない。
> 
> Auth0のAccount Linking (issue #43) はメアドをキーにして動作するため、ソーシャル側のメアドが変わったときにどういう挙動を示すのかも要調査。

ソーシャル側のメールアドレスを変更するケースでは、Auth0上で直接emailを変えてあげるみたいな人手の対応が必要とAuth0の人が回答しているようです
多くないケースではあるので、発生したら問い合わせてもらうという対応が無難そうです。
https://community.auth0.com/t/best-practice-for-changing-email-for-linked-accounts/61939

**Comment by jacopen** [comment]
システム問い合わせフォームをGoogle Formsでさっくり用意してもいいかも

**Comment by jacopen** [comment]
フォームで対応するためこちらは閉じ
