### ISSUE TITLE
セッション以外のイベント対応

### ISSUE THREAD

**Issue by MasayaAoyama** [cloudnativedaysjp/dreamkast#241]
下記のようなイベントに対応するページを作成する。
基本的に外部へのリンクへの誘導のため、説明文が書ける枠があればOK

* Upstream Training
* Kontest
* Miroのお悩み相談ボード

## プラン1
セッションの登録可能不可能を制御
セッション詳細からconnpassなどへの導線を貼って、募集自体はそちらでやる

## プラン2
TimetableのようにEventsタブを切ってそこに新しいページを作成する。
イベントページにはペライチで書く感じでもいいかも。
イメージ：
https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/program/colocated-events/#cloud-native-roost-hack-a-thon

**Comment by takaishi** [comment]
これどうやるのがいいかなー。物によってはセッションと時間がかぶることもあると思うので、タイムテーブル上に表示できるといいんだけどセッションとそれ以外で登録方法が違うのでややこしい気もしています

**Comment by takaishi** [comment]
あと、イベントという単語がシステム的にCNDT2020のレイヤを差すので、他の呼び方にしたいです。コンテンツ、とか

**Comment by MasayaAoyama** [comment]
コンテンツいいですね。
タイムテーブル上で表示したときに、どんどん横になっちゃうのと、終日イベントが増えると辛いかなぁという気も
