### ISSUE TITLE
hervestjobが成功しても /talks の vimeo url にm3u8のURLが挿入されない

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast#2460]
Dkの事前検証を行っている際に見つけました。
Hervest Jobを実行しても、/talksのvimeo urlに埋め込まれませんでした。

## 情報

- 環境： Prod（https://event.cloudnativedays.jp/cndw2024）
- イベント： CNDW2024
- TalkID: 2403
- HervestJobId: 143
- m3u8 url: https://d3pun3ptcv21q4.cloudfront.net/mediapackage/cndw2024/talks/2403/143/playlist.m3u8

## 手順
以下の手順に従いました
https://www.notion.so/pfem/Hervest-Job-b8b3969bc03c4dc281ce6a33789d93bb

- セッションをOnAir状態で映像を流し、10分ほど放置
- 次のセッション（2423）にOnAirステータスを切り替える
- 録画ボタンをおして、Hervest Jobを実行する
- Hervest JobページでSUCCESSEDを確認する
- /talksページを確認する → 埋込されていない

**Comment by takaishi** [comment]
イベント当日以外はharvest jobのチェック用cron jobが無効になっているため、video_urlにURLが保存されなかった。
