### ISSUE TITLE
ブース情報が正しく登録されず、欠落が生じる

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#256]
複数点の画像、またはPDFを登録すると、最後に入力したものしか保存されないようです。
Firefox、Chromeで同じ現象を確認しています。

例：
フォームへの入力内容
![screencapture-cndt-dreamkast-herokuapp-admin-sponsors-5-edit-2020-08-24-15_05_58](https://user-images.githubusercontent.com/31978147/91009460-96feae00-e61b-11ea-8e2d-e48c60054241.png)

実際の表示画面
- 画像が1点、PDFが1点しか登録されていない
![screencapture-cndt-dreamkast-herokuapp-admin-sponsors-5-2020-08-24-15_06_24](https://user-images.githubusercontent.com/31978147/91009542-bbf32100-e61b-11ea-8e4b-db5804a49541.png)

再度Editした時の登録データ
![screencapture-cndt-dreamkast-herokuapp-admin-sponsors-5-edit-2020-08-24-15_06_44](https://user-images.githubusercontent.com/31978147/91009608-dfb66700-e61b-11ea-9870-617ed652b096.png)

**Comment by takaishi** [comment]
@nabemasat 修正したので、stagingで確認していただけますか？

**Comment by nabemasat** [comment]
@takaishi 
ありがとうございます！画像・PDF掲載は直りました！
一点、Booth: Textについては引き続き入力したデータが消えてしまいます。やり直して二回目に登録すると、掲載されるのですが…すみませんがご確認ください。
![Screenshot_2020-08-25 CloudNative Days Tokyo 2020](https://user-images.githubusercontent.com/31978147/91124107-785eec80-e6d9-11ea-9132-0a80ac0d99e5.png)
![Screenshot_2020-08-25 CloudNative Days Tokyo 2020](https://user-images.githubusercontent.com/31978147/91124111-7ac14680-e6d9-11ea-9a6a-c8f6b34e697d.jpg)

**Comment by takaishi** [comment]
おっと、テキスト。確認します！

**Comment by takaishi** [comment]
@nabemasat テキストについても修正済みです

**Comment by nabemasat** [comment]
@takaishi ご対応ありがとうございます！夜に確認します！

**Comment by nabemasat** [comment]
@takaishi 
登録を試してみたのですが、こちらのページに入力したところ、エラーになってしまいました。https://cndt-dreamkast.herokuapp.com/admin/sponsors/6

他のページは編集できるようなので、確認をお願いできないでしょうか:bow:
![image](https://user-images.githubusercontent.com/31978147/91294622-cb699a00-e7d4-11ea-94c8-dd5414cbad35.png)

**Comment by takaishi** [comment]
むむむ

**Comment by takaishi** [comment]
わ、レコードに格納されてるjsonがサイズオーバーしてパースできなくなってる

**Comment by nabemasat** [comment]
すみません、ファイル名見たら176文字（拡張子含む）でした・・・
通常の運用ではまず考えられないので、こちらはスルーで良いかと思います:bow:
別の内容で入力して、正常動作を確認しました！

**Comment by nabemasat** [comment]
@takaishi
