### ISSUE TITLE
ブースの概要文でリンクを貼れるようにする

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#258]
度々のご相談ですみません！
Sponsor's Description / Booth: Text で、リンクを貼れるようにできますか？
多分URLの自動変換は面倒だと思うので、<a>タグを貼れるようにして頂けると…！

（スポンサーが概要ページにリンクを貼ろうとしているケースが多いので・・・）

**Comment by takaishi** [comment]
@nabemasat URLは自動的にリンクになるようになったはずですー

**Comment by nabemasat** [comment]
@takaishi 確認遅くなってしまい申し訳ありません！Booth:Textについてはバッチリです！
Sponsor's Description については、リンクを書いても動作しなかったのですが、これはなにか意図がありますか？

**Comment by takaishi** [comment]
あ、見落としていました。手間ではないので直しておきます

**Comment by takaishi** [comment]
@nabemasat 修正ずみでっす

**Comment by nabemasat** [comment]
@takaishi  動作確認しました！ありがとうございます！
