### ISSUE TITLE
スポンサーページへの導線

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#262]
下記のような導線をイメージしています。ご検討お願いします！
@jacopen @takaishi 
![ブース導線](https://user-images.githubusercontent.com/31978147/91408942-a716c780-e87f-11ea-8cfc-c81e0170f45d.jpg)

**Comment by takaishi** [comment]
👀

**Comment by takaishi** [comment]
@nabemasat 導線追加したのでご確認ください〜！

**Comment by nabemasat** [comment]
@takaishi 
ありがとうございます！バッチリです！

これからデザイン入れると思うのですが、最後のコミュニケーション用のリンクが空白の場合、ボタンを非表示にすることって手間でしょうか？他に優先度もあるので、可能ならで構わないのですが…軽めでしたらIssue立てます:bow:

**Comment by takaishi** [comment]
できます！

**Comment by takaishi** [comment]
リンク空白時にボタンを非表示にするのは https://github.com/cloudnativedaysjp/dreamkast/pull/274 で実施

**Comment by jacopen** [comment]
終わってそう
