### ISSUE TITLE
SPECIAL COLLABORATION枠の新設

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#269]
Sponsorの上に「Special Collaboration」枠を作る
CNCFはSpecial Collaborationに掲載し、Goldからは削除

添付：掲載イメージ
<img width="949" alt="image" src="https://user-images.githubusercontent.com/31978147/91673002-be4e0180-eb6c-11ea-83b9-a4434bbcd0ec.png">

**Comment by jacopen** [comment]
うーん、この修正は面倒･･･
スポンサーと違う理由って何ですか？ @nabemasat

**Comment by jacopen** [comment]
スポンサーの"中"にSpecial Collaboration枠を作るのではなく、別枠にする必要あり？

**Comment by nabemasat** [comment]
スポンサーの中にSpecial Collaborationでも構いません:bow:
諸事情で、他のスポンサーとは別格であることを示す必要があります:bow:
