### ISSUE TITLE
Talk一覧のフィルタリング機能があるとうれしい

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast#287]
Talkの数多くて探すの大変なのでフィルタリングしたい。JSを使うイメージ。

**Comment by takaishi** [comment]
https://qiita.com/yun_bow/items/d845a2b3389fc8ca7ae1
https://examples.bootstrap-table.com/

**Comment by jacopen** [comment]
これはもう不要かな

**Comment by takaishi** [comment]
不要になった
