### ISSUE TITLE
On Airコントロールの改善余地を検討

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#288]
発端 9/1のミーティング

Dreamkast側で運用を楽に出来ないか？ 特にCM切り替え周り

**Comment by takaishi** [comment]
📝 OnAir/Waitingを切り替えた後に保存し忘れる可能性があるので、何か策を打ちたい

**Comment by takaishi** [comment]
保存し忘れの検知、結構難しい。明日中にはできそうだけど間に合わないかも

**Comment by takaishi** [comment]
保存し忘れの検知は時間足りず断念。目的は達成しているのでクローズ
