### ISSUE TITLE
sli.doのIDがないときに視聴画面が下にスクロールしてしまう

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#316]
sli.doのIDがないとき、視聴画面を表示すると下にスクロールしてしまう。結構違和感・・・

![image](https://user-images.githubusercontent.com/79102/92354835-085f5600-f11e-11ea-946e-4fc446d0d807.png)

ブレークアウトセッションはいいんだけど、キーノートはslidoがないから対策考えないと微妙。

・ダミーのslido入れる
・slidoがあっても飛ばないような仕組みを考える

のどちらか、あるいは両方の対処を入れる必要がある

**Comment by takaishi** [comment]
手元だと一回スクロールした後に上に戻ってる気がするな 🤔

**Comment by takaishi** [comment]
なるほど、sli.doのIDがなくてsli.doのフォームが見えていないとスクロールしてるのでは
