### ISSUE TITLE
複数登壇者のセッションで、発表資料リンクの表示が変

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#336]
スピーカーごとに同じ資料リンクが表示されてしまっている。
例のURLはhttps://event.cloudnativedays.jp/cndt2020/talks/21
対応優先度は低め。意図した仕様でしたらクローズでOKです。

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/31978147/92673103-43979a00-f355-11ea-831e-c87a12963cfb.png">

**Comment by jacopen** [comment]
ありゃ
