### ISSUE TITLE
アーカイブサイトのブースページの復活

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#341]
具体的な社名等は別途ご連絡しますが、スポンサーさんから下記の要望がありました:bow:
可能な範囲で対応をお願いできればと思うのですが、いかがでしょうか。。

------

1) アーカイブサイト（https://event.cloudnativedays.jp/cndt2020） にBoothへの導線を設置する
- 1.ナビゲーションバー
- 2.各セッション視聴ページ
    - Zoom等のリンクはデータ更新して外す

2)アーカイブサイトで常時スポンサー一覧を表示

理由
・主催者から参加者に対するBoothの説明が不足しており、導線も乏しかった
・ログインした後、スポンサーの一覧がなくて協賛企業が目立たない形となった
・せめてアーカイブでの露出を増やしたい

--------

**Comment by jacopen** [comment]
@nabemasat これ大分時間経っちゃいましたがまだ必要ですか？

**Comment by nabemasat** [comment]
@jacopen いえ、対応の必要はありません。
