### ISSUE TITLE
エントリーフォームへのプライバシーポリシーの表示

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#355]
**個人情報保護方針(プライバシー ポリシー)**

ご登録頂きました個人情報はイベントの運営会社である株式会社インプレスとGAFA株式会社が管理し、電話/電子メール/郵送等による、各種サービスやセミナー開催情報などの情報提供に利用させて頂きます。 インプレス社の詳しいプライバシーポリシーに関しましては<a href="https://www.impress.co.jp/privacy.html" target="_blank">こちら<a>をご覧下さい。

**案1）登壇者と一般参加者を分ける**
なお、今回ご登録いただきました個人情報は、本イベントの運営に必要な範囲でのみ利用致します。業務委託先または提携先へ業務預託する場合がございますが、個人情報をお客様の承諾なしに目的外利用すること、及び第三者に提供することはございません。あらかじめご了承の上、お申し込みをお願いいたします。

**案2）区別しない**
なお、今回ご登録いただきました個人情報は、本イベント協賛企業（各種スポンサー）へ提供いたします。各種スポンサーからご登録者の皆様に、直接電子メールや郵送でご案内をさせていただく場合がございます。

業務委託先または提携先へ業務預託する場合がございますが、個人情報をお客様の承諾なしに目的外利用すること、及び第三者に提供することはございません。なお、開催日までに各種スポンサーが追加となりました場合は、イベントWebサイトに公開しますとともに、追加となりました協賛企業ともご登録情報を共有させていただきます。あらかじめご了承の上、お申し込みをお願いいたします

**Comment by takaishi** [comment]
done
