### ISSUE TITLE
エントリーフォームで、セッション概要をDeleteすると登録ボタンが作動しなくなる

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#362]
以下の動作で症状が出た。

> セッション情報を記入
> ↓
> 誤ってセッションを追加
> ↓
> ２番目のDeleteすると、登録ボタンが作動しなくなる

セッション概要を何も記入せずにDeleteボタンを押すと、やはり登録ボタンを押しても何も起きない
（セッション概要がないなどエラーメッセージを期待していたが、出なかった）

下記環境で確認
Firefox 84.0.1
Chrome 87.0.4280.88
MacOS Catalina 10.15.7

**Comment by nabemasat** [comment]
@takaishi 
すみません:bow:こちら再度確認したのですが、直ってないみたいです、、、

**Comment by jacopen** [comment]
あ、紐づけ間違いだ

**Comment by takaishi** [comment]
あれ、確認します。

**Comment by takaishi** [comment]
こういうエラーがでている：

```
An invalid form control with name='speaker[talks_attributes][1609054935146][title]' is not focusable.
An invalid form control with name='speaker[talks_attributes][1609054935146][talk_category_id]' is not focusable.
An invalid form control with name='speaker[talks_attributes][1609054935146][talk_time_id]' is not focusable.
```

**Comment by takaishi** [comment]
なるほど、Deleteを押したときにフォームを非表示にしているのだけどrequireフラグは残っているからバリデーションが走る。
