### ISSUE TITLE
製品紹介セッションの取り扱いについてエントリーページに追記してほしい

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#363]
「事前審査はありますか？ また、内容に制限はありますか？」の項目に下記の一文を付け加えられないでしょうか:bow:

**自社製品のセールスを目的とするセッションについては、動画投稿ではなくCNDO2021への協賛をご検討ください。**

**Comment by jacopen** [comment]
#364 で対処済み
