### ISSUE TITLE
リード作成機能の実装

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast#370]
CSV出力する

**Comment by takaishi** [comment]
イベント後にやる必要がある

**Comment by jacopen** [comment]
From slack

```
イベント終了後にスポンサーに提供するリード提出のスケジュール、フォーマットについて、インプレス側の希望をお伝えします。
==================================================
・リードデータの提出日：3月18日
・フォーマット：エクセルデータ
・スポンサーごとに登録リストにセッション視聴フラグ、ブース訪問フラグ、ブースの資料ダウンロードフラグを付ける
・事前登録なしでスポンサーセッションを視聴した場合もリストに入れる
・視聴フラグはセッション視聴連続何分以上で設定（視聴時間は別途お伝えします）
==================================================
上記の内容で一度ご検討頂けますでしょうか。
アーカイブ配信分のリード提供については、追ってご連絡します。
宜しくお願い致します。
```

**Comment by nabemasat** [comment]
宮奈さんから頂いたリード情報のサンプル（必要な項目）を整理しました。
https://docs.google.com/spreadsheets/d/19FXz4-JsJNJfJ_Rs2Lrs2dRa6mMX3VccqeTgks34RTU/edit?usp=sharing

以下のポイントについて、宮奈さんも交えてディスカッションできればと思います。

いくつか注意が必要なポイント
- スポンサー種別によって、提供する要素・範囲が異なる
    - ダイヤモンド：イベント申込者全員のリスト
    - プラチナ：セッション登録者全員
    - ゴールド：セッション視聴者のみ
    - ブース：ブース訪問者のみ
    - ダイアモンド＋ブース、プラチナ＋ブースのパターンもあり

決めないといけないこと：
- どこまでをシステムで出力し、どこまでを手動でやるか
     - 例えば、プラチナ＋ブースなどの複雑なパターンは、プラチナ、ブースそれぞれのリストを出して手作業で統合してもらった方が手間が少ない
- セッション視聴フラグを立てる視聴時間（何分以上か）
- ブース訪問フラグを立てる滞在時間（何分以上か）
- アーカイブ期間のリスト
     - 会期中のリストと取り扱いが異なる
         - 例えば、セッション登録という概念があるのは会期中だけ
     - アーカイブ期間の（１ヶ月間）リストをいつ提出が必要か

**Comment by jacopen** [comment]
プラチナ：セッション登録者全員
の仕様の確認なんですが、これって登録者+視聴者じゃないかと思うんですがその認識はあっていますか？(セッション登録しないまま視聴している人も多いので)

**Comment by MasayaAoyama** [comment]
@nabemasat 
アーカイブ中のリード情報と会期中のリード情報などは同じタイミングで渡しますかね？
会期中の情報はもう出そうと思えば出せそうですが

**Comment by nabemasat** [comment]
@jacopen 失礼しました。ご指摘の通りセッション登録者＋視聴者です

@MasayaAoyama アーカイブは1ヶ月後なのですが、リアルタイム配信期間のリードは別でお渡しする必要があります

**Comment by jacopen** [comment]
@nabemasat 決めなきゃ行けないところを決めるのって誰担当になりそうですか？ これは実行委員会側では決められないものが多いと思うのですが

**Comment by nabemasat** [comment]
@jacopen 
お待たせしてすみません。会期中のリストについては

- セッション視聴フラグを立てる視聴時間（何分以上か）
10分以上
- ブース訪問フラグを立てる滞在時間（何分以上か）
2分以上

となります。アーカイブ期間のリストについては、提出は１ヶ月先なので、宮奈さんに取り扱い確認します。

**Comment by takaishi** [comment]
リード自体は提出済み。今後どうリード作成を楽にするかは要検討…
