### ISSUE TITLE
HerokuからAWSへ移行する

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast#373]
* Herokuで動かしているアプリとDBをAWSに移行する
* ECS + RDSベース
* CDパイプラインの変更
  * merge => staging => production (by promote)できる
  * herokuのreview app的なものがほしい
    * review appはherokuを使うのでもいい？要検討

**Comment by jacopen** [comment]
こちら着々とインフラ側の準備は進んでいて、残るはDreamkast本体の移行を残すのみって感じになった。

## 残作業

### GitOpsフロー

**完了**

✅ PullReqが上がったらReview Appsを立ち上げる
✅ mainにマージされたらmain用のアプリに反映する

**未完了**

- [ ] Stagingで確認して、問題なければProductionに適用するフロー作り
- [ ] Review Appsがpurgeされないことがある

### Dreamkastのk8s移行

- [ ] MySQLのRDB移行
- [ ] RedisのElastiCache移行
- [ ] DNS切り替え
- [ ] 環境変数等の追加 (Sentryとか)

**Comment by jacopen** [comment]
inductorに確認したところ、どうやらDBのスムーズな移行は難しそうなので、えいやでk8sに切り替えることにする
https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1613915876086000

**Comment by jacopen** [comment]
ProductionメンテナンスモードIN
![image](https://user-images.githubusercontent.com/79102/109004330-fda87580-76eb-11eb-8279-9b451dffced9.png)

**Comment by jacopen** [comment]
DB操作用コンテナ作成
```
kubectl run --rm -it --image jacopen/aws-cli-mysql test /bin/bash
```

ClearDBからdump
```
mysqldump --single-transaction -h us-cdbr-east-02.cleardb.com -u bda97692b27757 -p --skip-column-statistics heroku_08ecafa8a197a0e > production20210224.dump
```

dreamkast dbが無かったのでcreate database
```
 CREATE DATABASE dreamkast CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
 use dreamkast;
 
 mysql> show variables like '%char%';
+--------------------------+-------------------------------------------+
| Variable_name            | Value                                     |
+--------------------------+-------------------------------------------+
| character_set_client     | latin1                                    |
| character_set_connection | latin1                                    |
| character_set_database   | utf8mb4                                   |
| character_set_filesystem | binary                                    |
| character_set_results    | latin1                                    |
| character_set_server     | utf8mb4                                   |
| character_set_system     | utf8                                      |
| character_sets_dir       | /rdsdbbin/mysql-8.0.21.R8/share/charsets/ |
+--------------------------+-------------------------------------------+
```

dumpしたファイルをimport
mysql -h dreamkast-prd-rds.c6eparu1hmbv.ap-northeast-1.rds.amazonaws.com -u admin -p dreamkast < production20210224.dump

**Comment by jacopen** [comment]
Productionも移行完了。特に問題ないようなのでクローズ
