### ISSUE TITLE
スポンサーページの実装

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#4]

**Comment by nabemasat** [comment]
バーチャル展示スポンサーのみ
・動画埋め込み
・PDF資料ダウンロード（1点〜数点）※ダウンロード者の情報取得込み
を提供したいです

バーチャル展示スポンサーか否かは、更新担当者が運用でカバー
動画埋め込みは機能じゃなくて、iframe埋め込みで良いかと思います。

**Comment by KaseiKondo** [comment]
> バーチャル展示スポンサーのみ
> ・動画埋め込み
> ・PDF資料ダウンロード（1点〜数点）※ダウンロード者の情報取得込み
> を提供したいです
> 
> バーチャル展示スポンサーか否かは、更新担当者が運用でカバー
> 動画埋め込みは機能じゃなくて、iframe埋め込みで良いかと思います。

@jacopen cc: @nabemasat スポンサーから資料PDFと動画ファイルをもらうにあたって、スペックを決めておきたいです。
■動画：

- アスペクト比：16：9推奨 ←ありものの動画だと思うので、あくまで推奨で。

- 解像度等：1920*1440 ←ありものの動画だと思うので、あくまで推奨で。

- 動画のファイルサイズの上限：？？？

- 動画のファイル形式：MP4のみとしますか？

■PDF資料DL

- ファイル数：上限3つまで

- ファイル形式：PDFのみ

- PDFファイルサイズの上限：？？？

■アピール文

- テキスト300字程度

■キーイメージ画像

- 点数：2点まで

- ファイル形式：JPG or PNG 形式

- ファイルサイズの上限：？？？

- ファイルの縦横サイズの上限：？？？

**Comment by jacopen** [comment]
スペック決めいいですね。

**Comment by jacopen** [comment]
スペック決めるのいいですね

基本近藤さんが書かれているものでいいと思います。

気になる点と？？？のところに追記すると


■動画：
解像度等：1920*1080 ←16:9だとタテは1080ですね。これ以外のアスペクト比や解像度だと、画質の低下や動画に帯が出る可能性がありますと注釈つける感じで

動画のファイルサイズの上限: Vimeoにアップロードする形なのでこの制限は無くてよさそう(ビットレート調整はVimeoがしてくれるはず)
動画のファイル形式: Vimeoがサポートする形式=受け付ける形式　でいいかなと

動画の長さ: 幕間差し込み用動画 ○分以内　スポンサーページ掲載用動画: ○分以内　← この指定は追加した方がいいかなと。具体的な長さの指定、アイディアありますか？ @nabemasat 

■PDF資料DL
PDFファイルサイズの上限：　← どこかのオブジェクトストレージに上げる形になるので、常識外れ(数GBとか) でない限りは特に指定無くていい気がします。

■ キーイメージ画像
ファイルの縦横サイズの**下限** : 大きい分にはこちらで縮小できるので、むしろ品質低下を避けるための下限を決めたいです。 縦横比16:9の1280×720以上、かなあ。画像と同じ16:9にしてもらうことでレイアウトしやすいかなと。
ファイルサイズの上限： 大きすぎる場合はこちらで調整できるのでこれは無くていいです

**Comment by nabemasat** [comment]
@jacopen @KaseiKondo 
ありがとうございます。
幕間差し込み用動画は最大2分間としています。
スポンサーページ（バーチャルブース）掲載用動画は企画書上長さは決めていなかったのですが
10分以内で、それを超える場合は個別対応（運営側で）ではいかがでしょう。

**Comment by jacopen** [comment]
いいとおもいます！

**Comment by KaseiKondo** [comment]
@jacopen @nabemasat ありがとうございます！
◼︎動画
幕間CM: 2分
スポンサーページに掲載する動画: こちらもVimeoにアップするのですね。
16:9 1920×1080 推奨、ファイル形式ファイルサイズはVimeoを確認。長さは10分程度でお願いします。

◼︎資料pdf: 
1GB以内、としましょう。

◼︎キーイメージ
これ少し考えた方がいいかもしれないです。どんな感じでページが見えるのかを例示しないとなにを作ればいいのか？という質問が来そうです。

鍋島さん、具体的なイメージってありますか？？
どこかですでにイメージ共有してされてたらすみません…。

**Comment by nabemasat** [comment]
@KaseiKondo @jacopen

こんな感じで絵を描いてみました。いかがでしょうか？
（見れますでしょうかm(__)m)
 
https://miro.com/welcomeonboard/EZDtGjpvOolTHSLE10zxjZu27G3cY5cgowOrlOxGepLh6USYwJvkRRYGpy4qMN36

**Comment by KaseiKondo** [comment]
@nabemasat レス遅れ大変失礼いたしました。こちらで問題ないと思います。
@jacopen @nabemasat スポンサーロゴはこちらのフォルダに入れてあります。
https://drive.google.com/drive/folders/1GYpVbeMyxgbR62ZDYZaKtwxOrttOkhDa?usp=sharing

**Comment by TomikoTerayama** [comment]
@KaseiKondo test

**Comment by takaishi** [comment]
@nabemasat ブースを管理できるようになりました。stagingのadminページから触れるので、見てもらえますか？デザインはまだ暫定です。

**Comment by nabemasat** [comment]
@takaishi 遅くなりすみません！承知しました！ありがとうございます！

**Comment by nabemasat** [comment]
@takaishi  
遅くなりすみません:bow:
いくつか掲載を試してみましたが、
- キーイメージを複数枚掲載すると、片方が表示されない場合がある
- ブース紹介文も表示されない
- PDF資料を複数点掲載すると、一つしか掲載されない
- また、フォームに入力したはずのデータが、再度Editすると消えてしまっている
など、いくつか不具合があります。

ちなみにVimeoのURLはどのような形式で埋め込めばよいのでしょうか？

**Comment by nabemasat** [comment]
あとすみません、スポンサー指定のZoom等のリンク埋め込みも仕様に入っているので、ご対応をお願いできないでしょうか:bow:
https://docs.google.com/presentation/d/19DEL7w2pVKZqPUrCnyuAvLdfyqrnXMWtlsK-X_L1skc/edit#slide=id.g88aa681be3_0_0

**Comment by takaishi** [comment]
確認＆対応します！

**Comment by takaishi** [comment]
@nabemasat 

>キーイメージを複数枚掲載すると、片方が表示されない場合がある
ブース紹介文も表示されない
PDF資料を複数点掲載すると、一つしか掲載されない
また、フォームに入力したはずのデータが、再度Editすると消えてしまっている
など、いくつか不具合があります。

不具合が発生しているスポンサーのURLを教えてもらえますか？

**Comment by takaishi** [comment]
> ちなみにVimeoのURLはどのような形式で埋め込めばよいのでしょうか？

`https://player.vimeo.com/video/XXXXXXXXXXX` の形式です！

**Comment by nabemasat** [comment]
@takaishi 
ありがとうございます！まず、Vimeoの埋め込み形式了解です！！

不具合は以下の二社の登録で確認しました（もちろんステージングです）

GMOペパボ
https://cndt-dreamkast.herokuapp.com/admin/sponsors/17

LegalForce
https://cndt-dreamkast.herokuapp.com/admin/sponsors/20

**Comment by takaishi** [comment]
@nabemasat うーん、画像・PDFなどはDB上には1つしか登録されていないですね…ちょっとステージング触ってみてみます。

**Comment by takaishi** [comment]
@nabemasat ペパボに `test` という名前でテスト用のPDFを追加しましたが、ちゃんと追加されています。鍋島さんの手元だと、何度やっても再現しますか？

**Comment by nabemasat** [comment]
@takaishi ありがとうございます。何度か試してみましたが再現されました。ブラウザの可能性もあるので、もう少し試してみてIssueを立てます:bow:

**Comment by nabemasat** [comment]
@takaishi 
詳しい症状をこちらに記載しました:bow:
（キャプチャ貼りまくってるので重いです…すみません:bow:)
https://github.com/cloudnativedaysjp/dreamkast/issues/256

**Comment by nabemasat** [comment]
@takaishi 
度々すみません:bow:こちらもご検討をお願いできないでしょうか。。
 ブースの概要文でリンクを貼れるようにする
https://github.com/cloudnativedaysjp/dreamkast/issues/258

**Comment by takaishi** [comment]
確認します！

**Comment by takaishi** [comment]
@nabemasat スポンサーページ、不備などなさそうでしょうか?

**Comment by takaishi** [comment]
ブースのデザインは https://github.com/cloudnativedaysjp/dreamkast/pull/274 で修正します
