### ISSUE TITLE
セッションの登壇者プロフィールを改行してほしい

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast#418]
## 要望
- 登壇者プロフィールのテキストで改行をしてほしい
- 元データでは改行しているが、Dkに反映されると改行されず悲しい感じになる

例↓
![image](https://user-images.githubusercontent.com/5129906/106707612-d9013680-6634-11eb-8481-31446a151409.png)

## ユースケース
- 複数人で登壇する場合、各登壇者ごとにプロフィールを連続して書いている

## その他
- 改行対応ではなく、複数の登壇者登録に対応するのも良さそう

**Comment by takaishi** [comment]
取り急ぎ、 https://github.com/cloudnativedaysjp/dreamkast/pull/419 で改行を反映します。
talk自体は複数のスピーカーに関連付けられる（CNDT2020の時に実装した）のだけど、CNDOの仕組みでうまく関連づける機能が今のところない状況です…
