### ISSUE TITLE
CNDO版プライバシーポリシーの確認

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#424]
申し込み受付開始するにはプライバシーポリシーを更新しないといけない。前回のような各社ごとのチェックボックスの有無について確認する

![image](https://user-images.githubusercontent.com/79102/107109132-e6aafc00-6880-11eb-8c94-ad0ebe763811.png)

**Comment by nabemasat** [comment]
下記でお願いします！MSさんはチェックボックスありです。

-----
### リスト提供企業社名一覧
CircleCI合同会社
New Relic株式会社
GMOインターネットグループ
JFrog Japan株式会社
SUSE ソフトウエア ソリューションズ ジャパン株式会社
アクイアジャパン合同会社
LINE株式会社
SCSK株式会社
Datadog Japan 合同会社
ヴイエムウェア株式会社
レッドハット株式会社
F5ネットワークスジャパン合同会社
日本マイクロソフト株式会社

### 日本マイクロソフト株式会社/Microsoft Corporationからの情報提供

日本マイクロソフト株式会社/Microsoft Corporationから情報提供を希望される場合、申し込み者情報に記載いただいた内容を日本マイクロソフト株式会社/Microsoft Corporationへ提供させていただきます。利用目的は当該企業の製品・サービスに関する情報またはマーケティング活動に関する情報をお知らせすることです。個人情報の取り扱いにつきましては、日本マイクロソフト株式会社/Microsoft Corporationのプライバシーポリシーに準拠します

□ 日本マイクロソフト株式会社/Microsoft Corporationへの個人情報提供に同意する
[(プライバシーステートメント)](https://privacy.microsoft.com/ja-jp/privacystatement/)

------

(プライバシーステートメント)のリンク先：
https://privacy.microsoft.com/ja-jp/privacystatement/

※任意回答
※デフォルトではチェックは全て空欄、
オーディエンス側が能動的に:heavy_check_mark:を入れる形にする

**Comment by nabemasat** [comment]
株式会社クラウドネイティブのプラチナスポンサーでの協賛が決定しました。
リスト提供企業社名一覧に、「株式会社クラウドネイティブ」を追記お願いします！

**Comment by jacopen** [comment]
@nabemasat スポンサーロゴ、リンク先等の情報はありますか？出来ればそのあたりの情報を纏めて別Issueとして上げて欲しいです。これはプライバシーポリシーそのものを作るIssueなので
