### ISSUE TITLE
スポンサーロゴの掲載

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#430]
@jacopen @takaishi 
現時点でのスポンサー一覧とロゴ・リンク先になります。こちらをDreamkastに掲載お願いします。
（未提出の企業は、入手し次第ご連絡しますので、掲載無しでOKです）

https://docs.google.com/spreadsheets/d/1vhXSy2_ckYgWcI1sYnJz9cONBKSNGUhbzNYFbb8pgEs/edit?usp=sharing

**Comment by jacopen** [comment]
着手中

**Comment by jacopen** [comment]
@nabemasat 
JFrogのロゴが黒背景のみでちょっと使いづらいです
去年のJFrogロゴは白背景だったので、できれば去年と同じモノを使いたいです。先方に確認してもらえませんか？

**Comment by nabemasat** [comment]
@jacopen 
お返事遅くなりすみません:bow:
こちら確認中です。

JFrog公式のメディアキットには白背景の画像が用意されているので、多分問題ないと思いますが…
https://jfrog.com/brand-guidelines/
https://drive.google.com/drive/u/0/folders/1Icey3FWa2XjV3mIAY0fjR1_8H_SXxdxd

**Comment by nabemasat** [comment]
@jacopen 
お待たせしました:bow:
JFrogのロゴ、前回の白背景の流用で問題ないと確認取れました。

**Comment by nabemasat** [comment]
@jacopen 株式会社クラウドネイティブのプラチナでの協賛が決定しました。
表に追記しましたので掲載をお願いできますでしょうか。
