### ISSUE TITLE
登壇者問い合わせフォームを設置

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#442]
9:19
登壇者エントリーとかビデオアップロード周りはS-inした後もちょっと不安に思うところはあるから、GoogleFormsあたりでさっくり問い合わせフォーム作ってリンク載せておくほうが安心なのかも知れない

**Comment by MasayaAoyama** [comment]
karte的にはこんなフォームなら有効化できますね。
![スクリーンショット 2021-02-15 13 13 33](https://user-images.githubusercontent.com/8783194/107904648-bf92af80-6f8f-11eb-9765-cce02885765c.png)

![スクリーンショット 2021-02-15 13 09 45](https://user-images.githubusercontent.com/8783194/107904497-4f842980-6f8f-11eb-823c-a00a747f3172.png)
![スクリーンショット 2021-02-15 13 09 51](https://user-images.githubusercontent.com/8783194/107904499-501cc000-6f8f-11eb-8205-46813a6218c5.png)
![スクリーンショット 2021-02-15 13 10 00](https://user-images.githubusercontent.com/8783194/107904500-50b55680-6f8f-11eb-91b7-e7113f3fb37a.png)

![スクリーンショット 2021-02-15 13 14 03](https://user-images.githubusercontent.com/8783194/107904654-c3becd00-6f8f-11eb-8ce7-569afcb8c214.png)

**Comment by jacopen** [comment]
あ、めっちゃいい、神じゃん

**Comment by jacopen** [comment]
Karte様々。
実現されたので閉じます
