### ISSUE TITLE
デフォルトブランチをmainに揃える

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#444]
masterがデフォルトのリポジトリ
- dreamkast
- dreamkast-api-docs

mainがデフォルトのリポジトリ
- dreamkast-ui
- dreamkast-infra

たまにミスりそうになるし、いつか事故る気がするので早めに揃えておいたほうがいいかなと。
今後のことを考えるとmainに揃えた方がよさそう。

**Comment by jacopen** [comment]
api-docsは変えてもそんなに影響無いと思う(CIの指定変えるくらい？)
dreamkastのほうはHeroku側の設定をちゃんと見直す必要あり

**Comment by takaishi** [comment]
👍

**Comment by takaishi** [comment]
dreamkastのデフォルトブランチはmainに変更済み。
Herokuのdreamkast-staging、dreamkastのブランチもmainに自動的に切り替わっていた

![image](https://user-images.githubusercontent.com/107187/107591682-833d1780-6c4e-11eb-8708-ed1213cdf08a.png)

**Comment by takaishi** [comment]
dreamkast-api-docsも変更済み

**Comment by takaishi** [comment]
`Enable Automatic Deploys` を押して有効にしないといけなかったのか！

**Comment by takaishi** [comment]
Promoteまでできたので一通り移行完了しました
