### ISSUE TITLE
Amazon WorkMailでcloudnativedays.jpのメールボックスを建てる

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#445]
今後のこと考えるとcloudnativedays.jpのメアド要るんじゃないー？
ということで、WorkMailを使ってメアド作る

**Comment by takaishi** [comment]
メール送信自体はSESだけで実現できてWorkMailは不要なので、受信が必要になったら導入を検討

**Comment by takaishi** [comment]
今のところ受信の必要は無いので閉じておきます。必要になったら再オープンする
