### ISSUE TITLE
必要なアカウントを作成し、Impressと共有する

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#45]
現状各個人のアカウントを使って開発を進めているが、Beta1公開までに共通で使えるアカウントを作成して、そっちにホストする必要がある。

現在必要なアカウントは以下

- Heroku
- Auth0
- Vimeo

Karteは #15 で対応。

上記アカウントの作成のためにGoogle Groupsを作成し、そのメールアドレスでアカウントを開設する。

また、上記アカウント作成後、有料プラン契約のためクレジットカード情報を入力してもらう必要がある。
Impressの人にアカウント情報を共有して入れてもらう？ 鍋島さんに確認。

各種アカウントの情報(パスワード等)はLastPassで共有

## Tasks

- [x] Google Groups作成
- [x] Herokuアカウント作成
- [x] Auth0アカウント作成
- [ ] Vimeoアカウント作成
- [x] LastPassでアカウント情報共有
- [ ] Impressに情報共有

**Comment by nabemasat** [comment]
金曜日の夜に、クラウドインフラのコスト負担について事務局で話し合いを持つので、その後回答します。
お待たせしてすみません。

（最悪時間かかっちゃう場合は、鍋島建て替えます）

**Comment by jacopen** [comment]
ありがとうございますー。とりあえずアカウント作成だけ先にやっちゃって、支払い方法は回答待ちします

**Comment by jacopen** [comment]
あー、Beta1より後だけどVimeoもいるな

**Comment by jacopen** [comment]
無事アカウントも発行されたのでこちらクローズ
