### ISSUE TITLE
ログ基盤を決める

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#46]
Dreamkastのアプリログやアクセスログ、Auth0のAudit logなどを流し込むログ基盤が欲しい

選択肢

## SaaS
- Loggly
- Papertrail
- Logz.io

など

## 自前
- ELK
- Loki

**Comment by inductor** [comment]
Sentryを試してみよう

**Comment by jacopen** [comment]
ログが流れてしまって調査に困るケースがちょくちょくあるので、HerokuのアドオンからさっくりプロビジョニングできるPapertrailをぶっ込んでみたほうがよさそう。

良さそうならStagingとProductionに有償版くっつける感じで。予算的にはたぶん問題ないはず

**Comment by jacopen** [comment]
#373 に伴ってCloudWatch Logging使えるようになるのでそちらで
