### ISSUE TITLE
Facebookのシェアボタンが「シェア」という文字列になってしまうケースが存在する

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast#468]
## 概要
タイトル横に配置されたシェアボタンのうち、Facebookのボタンが`シェア`と表示されるケースが存在するよう。
私の環境で（Windows10/Chrome）で確認した所、特に問題がなかったのでユーザ環境または特定の動作に起因するもの？

↓ 私の環境
![image](https://user-images.githubusercontent.com/5129906/107870893-088b2b00-6ee0-11eb-9193-f069689d871f.png)

↓ユーザの環境
![image](https://user-images.githubusercontent.com/5129906/107870859-a7635780-6edf-11eb-898e-03da86f75a40.png)

### ref
> Share ボタン、"シェア" が Facebook だとわかりづらいので画像のほうがよさそうです、フィードバックしておきます

https://twitter.com/chaspy_/status/1360845380930314249?s=20

**Comment by TakumaNakagame** [comment]
とりあえず聞いてみた
https://twitter.com/kameneko1004/status/1360850893596336129?s=20

**Comment by jacopen** [comment]
Dremakast外の問題なのでこちらクローズします

**Comment by jacopen** [comment]
ちなみに該当のコードはこちら
https://github.com/cloudnativedaysjp/dreamkast/blob/main/app/views/talks/partial_show/_facebook_share_button.html.erb#L2

Aタグでぶっ込んでいるだけ(FB側から提供されているコード)　なので、こちらからはこれ以上のコントロールはやりづらい感じです
