### ISSUE TITLE
申し込みフォームの項目変更（可能であれば）

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#470]
@jacopen @takaishi 
インプレスさんから申し込みフォームについて下記の要望がありました。
DBをいじることになると思うのですが、対応可能でしょうか。
優先度はスケジュールのほうが高いです。

> 改善可能でしたら
> 以下の点をご検討いただけますと助かります。
> ・勤務先住所
> 都道府県部分を選択式にして回答枠の分割を希望　※必須選択で
> （市町村以降はこのまま自由入力形式＝必須入力で構いません）
>

**Comment by jacopen** [comment]
んーと、要望としては結局どっちも必須選択だけど、県名はプルダウン選択&データとしても分けてほしい　という認識であってますか？

データとしても分けてほしいというニュアンスを感じはしますが明文化されてないので、要件をクリアにしたいです

**Comment by jacopen** [comment]
要望の主眼がリード納品の際に件名を別カラムにしたいというモチベーションから来ているのであれば、そのリード作成時に分割する=必ずしもインターフェイスを変える必要はない

とも言えるので、目的をクリアにしたいですね。

**Comment by jacopen** [comment]
@nabemasat これなにか進展ありました？

**Comment by nabemasat** [comment]
@jacopen お返事遅くなりすみません。こちらはこのまま変更なしということになりました。
