### ISSUE TITLE
セッション登録ミスが発生しやすい（スマホ）

### ISSUE THREAD

**Issue by capsmalt** [cloudnativedaysjp/dreamkast#475]
機能改善要望ぐらいの位置づけです。

[テスト環境] スマホ(iPhone11Pro), iOS 14.4
「タイムテーブル上の "文字" をクリック」=>概要へ
「タイムテーブル上の "空白" をクリック」=> セッション登録用に選択された状態へ

==> 画面が小さいスマホ(iphone 11 pro)とかだと，やや操作が難しいかもしれない。

[解決策候補]
A: セッション選択方法の注意書きを入れる
B: 長押しでセッション概要へ。タップで選択状態へ

![IMG_0736](https://user-images.githubusercontent.com/6401075/107961596-753e1c80-6fe9-11eb-8d28-f5e4f7121135.jpg)

**Comment by jacopen** [comment]
クリックできる余地を左側に設けてみました

![image](https://user-images.githubusercontent.com/79102/107968612-eb468180-6ff1-11eb-83e2-ddda1bee0e1d.png)

**Comment by capsmalt** [comment]
操作性あがって良さそうです。
