### ISSUE TITLE
タイムテーブルを見ただけなのにアンケートが表示された

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#478]
ログインせずにタイムテーブルを表示したところ、アンケートが表示された。
申込するか迷っている人だと、若干鬱陶しく感じるかも。

新規申込時にアンケートが表示されるのが正しい挙動だと思いますので
優先度低めですが、対応頂けると助かります:bow:
<img width="1408" alt="スクリーンショット 2021-02-16 10 06 17" src="https://user-images.githubusercontent.com/31978147/108006425-c62c3000-703e-11eb-840e-5b03a89c2816.png">

**Comment by jacopen** [comment]
タイムテーブルに表示しないようにして貰ったので閉じ
