### ISSUE TITLE
新規登録でFaceBook利用した際、開発モードのためログインできない

### ISSUE THREAD

**Issue by rururu3** [cloudnativedaysjp/dreamkast#479]
CLOUDNATIVE DAYS SPRING 2021 ONLINEに聴講者として申し込む際に
![image](https://user-images.githubusercontent.com/21966302/108017152-86be0d80-7057-11eb-8e40-3666f092e446.png)
上記画面の通りログインが必要になるため

![image](https://user-images.githubusercontent.com/21966302/108017173-92a9cf80-7057-11eb-98c2-f601fb5895b5.png)
この画面でContinue With FaceBookでログインしたら

![image](https://user-images.githubusercontent.com/21966302/108017195-9d646480-7057-11eb-8016-113b36ea7b63.png)
のように開発モードになっているためアクセスできませんと出てきてログインできない。

**Comment by jacopen** [comment]
こちらの設定ミスと思われます。確認しますー

**Comment by jacopen** [comment]
@rururu3 お手数おかけしました、修正しましたのでご確認お願い致します！

**Comment by rururu3** [comment]
ログインできるの確認できました！
