### ISSUE TITLE
AdBlockが有効だとスポンサーロゴが表示されない

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#483]
スピーカーからの指摘を受け追試したところ再現しました。
ブラウザ：Chrome 88.0.4324.150
OS: macOS Catalina 10.15.7
Adblock 4.28.5

<img width="1576" alt="スクリーンショット 2021-02-16 16 33 29" src="https://user-images.githubusercontent.com/31978147/108031889-ee368600-7074-11eb-853c-9158781e599d.png">
<img width="917" alt="スクリーンショット 2021-02-16 16 34 05" src="https://user-images.githubusercontent.com/31978147/108031895-f098e000-7074-11eb-861b-caf1e2cf43fd.png">

**Comment by jacopen** [comment]
んー、これって対処しようがあるんですかね？

**Comment by jacopen** [comment]
特に広告感ださずimgタグで貼っているだけなので、それをAdと判断するAdBlockある意味すごいなぁと思いつつ、こちらではこれ以上対処するのは難しい感です。ブロックしているのはこちら側では無いので･･･

もし対処するとなると
- AdBlockしないようなメッセージを出す
- (AdBlockが対応しているのであれば) Altを入れて文字で出す

という手はあるかと思いますが、1つめは反感買うだけなのでやりたくないですね。2つめはAdBlockの仕様がよく分からないので、検証のコスト高いなぁという感じです

**Comment by jacopen** [comment]
Bugではないと判断しiceboxとしますー

**Comment by nabemasat** [comment]
なるほど…調べてみたら、他でも同じような現象が起きてるみたいですね。。承知しました！
https://qiita.com/chige/items/81fdc54d0f4400bc2472
