### ISSUE TITLE
新規スポンサー掲載（株式会社クラウドネイティブ）

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#485]
株式会社クラウドネイティブさんがプラチナスポンサーで協賛決定しました。
お手数ですが、ロゴの掲載とプライバシーポリシーへの追記（末尾で可）をお願いします。
https://docs.google.com/spreadsheets/d/1vhXSy2_ckYgWcI1sYnJz9cONBKSNGUhbzNYFbb8pgEs/edit#gid=1638690568

**Comment by nabemasat** [comment]
@jacopen すみません！こちら明日金曜日までに掲載をお願いできますか。

**Comment by takaishi** [comment]
@nabemasat PRで確認依頼されていると思うので、確認お願いします。鍋島さんの確認待ちの状態のはずです

**Comment by takaishi** [comment]
確認用のReviewAppがInactiveになっていたので再度起動中

**Comment by nabemasat** [comment]
@takaishi 失礼しました！:bow:直ちに確認します！
