### ISSUE TITLE
申込者数（各セッション別）のCSVダウンロードを復活させて欲しい

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#488]
>申込者数とセッション登録者数をCSVファイルでエクスポートできるようにする
>https://github.com/cloudnativedaysjp/dreamkast/pull/219

こちらをV2.0でも復活して頂けないでしょうか。
用途は、スポンサー企業への報告、及び運営会社での確認のためです。
2/21までに情報が取れるようになると助かります。

**Comment by takaishi** [comment]
復活というか、正しく動いてなかったようです。

**Comment by nabemasat** [comment]
@takaishi ご対応ありがとうございます:bow:
404とでていたので、単純に未実装だと思っていました。すみません。
