### ISSUE TITLE
申込者メールアドレスのエクスポート機能

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#489]
以下の2つの用途のため、申込者のメールアドレスをエクスポートする機能をお願いしたいです。
（もしくは手動で都度お頼いする形でもOKです。その場合はクローズします）

(1) ThinkIT集客メールから、既に申込んでいる人を配信先から除外したい（運営会社のインプレスからの要望）
(2) 参加直前のリマインドメール、事後のサンキューメールの配信　※Dreamkast側にメール送信機能がつくなら不要

(1)の用途のため、毎週1回〜2回ペースで出力が必要になる見込みです。
2/22週の集客メール（日程は調整中）から実施したいとのことですので、ご検討よろしくお願い致します。

**Comment by jacopen** [comment]
@nabemasat 
AdminページのUsersから見られるようになっています
![image](https://user-images.githubusercontent.com/79102/108511152-d70cc800-7302-11eb-83b8-e224086280eb.png)
