### ISSUE TITLE
ロゴ差替依頼（Datadog様）

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#490]
Datadog様から、DIAMOND、BOOTHの2箇所を横長のロゴに変更依頼が来ております。
データは下記のフォルダです。
https://drive.google.com/open?id=1pKwPx9hr3EHJljhmDedqyx6HzS7D2B0Q&authuser=terayama%40peak-1.tokyo&usp=drive_fs

**Comment by nabemasat** [comment]
@jacopen @takaishi 
こちら、急ぎで対応をお願いできますか:bow:
クライアントから催促が来ているとのことです。

**Comment by takaishi** [comment]
いつまででしょうか？今日中？

**Comment by takaishi** [comment]
日付と時間まで指定してもらえると助かります！

**Comment by nabemasat** [comment]
@takaishi 
本業もあるので、本日21時までにご対応お願いします！

**Comment by takaishi** [comment]
う、今日は22時くらいからじゃないと作業できないんですよね。 @jacopen できます？
もしくは、来週月曜までの対応じゃ駄目でしょうか？

**Comment by nabemasat** [comment]
@takaishi

了解です！すみませんが、来週月曜AMまでにご対応お願いします:bow:

**Comment by jacopen** [comment]
自分やりまっす

**Comment by nabemasat** [comment]
@jacopen ありがとうございます！
