### ISSUE TITLE
動画アップロードの有無を管理画面で確認したい

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#491]
誰が提出済みで誰が未提出かが管理画面で確認できると助かります。
2月末までには確認ができる状態になっているとありがたいです。

（動画それ自体の確認作業も必要ですが、そちらはストレージへのアクセス権など、別途ご相談させてください）

**Comment by takaishi** [comment]
- /admin/talksにアップロードされたビデオを確認するためのカラムを追加する
- ビデオファイルダウンロード用のリンクも表示する

**Comment by jacopen** [comment]
こちら完了済みなので閉じます
後で動作確認してもらって、問題があるようであればこちら再オープンでお願いします @nabemasat
