### ISSUE TITLE
動画のアップロードが止まってしまうケースがある

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#521]
サポートチャットから連絡あり。アップロードが99%で止まってしまうとのこと。

**Comment by MasayaAoyama** [comment]
auth0|5ff7b07866a0420069c33741

Chrome
バージョン: 88.0.4324.182（Official Build） （64 ビット）

**Comment by MasayaAoyama** [comment]
OSはWindows10です。
Firefoxで再度やってみましょうか

**Comment by jacopen** [comment]
自分の環境も同じWin10  Chrome 88.0.4324.182だったので、800MBほどの動画を上げてみたけど現象再現せず。ブラウザやOS要因ではなさそう

**Comment by takaishi** [comment]
- 2/27~2/28 3 AM頃は発生していた
- 2/28午前中の時点では再現せず（productionでもアップロードに成功している方がいる）
- アップロードについては別ルートを用意済みなので、再発した場合はそちら経由でアップロードしてもらう
- 再発した場合は速攻でログを見に行く & 手元で再現を試みる

アップロード失敗する人には https://docs.google.com/forms/d/1OwMdCEASlsqZOx7b4mMzhr7u5Q9xk3Lpvep30qWGVzk/edit を紹介する

**Comment by takaishi** [comment]
アップロード機能自体を消す（ https://github.com/cloudnativedaysjp/dreamkast/issues/634 ）ので、このチケットは閉じます
