### ISSUE TITLE
リハーサルからのフィードバック

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#525]
リハーサル、プレイベントで出た意見をまとめておくIssueです

UI/Dreamkast関係なくこちらにまとめます

**Comment by jacopen** [comment]
チャットリアクションボタンが機能していない

**Comment by jacopen** [comment]
チャットで空行が送れてしまう

**Comment by jacopen** [comment]
タブの切り替えで動画の自動再生が止まってしまう

**Comment by jacopen** [comment]
ウィンドウ幅を狭くするとスポンサーロゴが被ってしまう

**Comment by jacopen** [comment]
登壇者からのコメントは登壇者と分かるようにしてほしい

**Comment by jacopen** [comment]
スポンサーロゴの速度が変わったり逆流したりする

**Comment by MasayaAoyama** [comment]
ダッシュボード（リアルタイム配信画面）への導線がヘッダーにないため、ログイン後の下記の画面でタイムテーブルに飛んだあと、
ダッシュボードへ行くには下記のトップページに戻ってきてからダッシュボードへ行く必要がある。

![image](https://user-images.githubusercontent.com/8783194/109157491-6dcefe00-77b5-11eb-90ca-b2089f48125e.png)

**Comment by nabemasat** [comment]
チャットの読み込みが止まることがある。リロードすると直って、最新の投稿を取りに行ってくれた。

**Comment by cyberblack28** [comment]
Discordへのリンクボタンが無い。

**Comment by cyberblack28** [comment]
CNDTの時はTwitterへシェアリンクボタンがありましたが、今回は有り？

**Comment by MasayaAoyama** [comment]
プレリハ時、Bが始まった次点で、始まりが1分ほど切れてた模様

**Comment by MasayaAoyama** [comment]
Bで見てたのに急にAのチャットになったりチャットがトラックごとに頻繁に切り替わってしまう

**Comment by jacopen** [comment]
ここで出た問題で未解決のものは個別にIssueを切りました
https://github.com/cloudnativedaysjp/dreamkast/issues/538
https://github.com/cloudnativedaysjp/dreamkast/issues/537
https://github.com/cloudnativedaysjp/dreamkast/issues/536
https://github.com/cloudnativedaysjp/dreamkast/issues/535
