### ISSUE TITLE
講演者動画の確認用URL、別の人の動画が表示されている

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#527]
※プレイベント終了後の確認で構いません

表題の件、管理画面>Talks＞Video Fileで、jacopenさんの欄に別の人（岩崎 英俊さん）の動画リンクが表示されています。CloudNative(Hexabase).mp4というところです。

<img width="1544" alt="スクリーンショット 2021-02-25 22 07 39" src="https://user-images.githubusercontent.com/31978147/109164402-bb4f6900-77bd-11eb-9086-4c032d0acac5.png">

**Comment by takaishi** [comment]
これはプレイベントの運営の関係でアップロードしているはずで、問題はないです

**Comment by nabemasat** [comment]
なるほど。ありがとうございます！
支障ないとのことでしたら、後でクローズします！

**Comment by jacopen** [comment]
これは #521 のトラブルの切り分けのために動画をもらって自分のセッションに上げたからです

このあたりの会話でやってます
https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1614222978237500

**Comment by takaishi** [comment]
あ、そっちか。
