### ISSUE TITLE
プレイベントで見つかった問題点

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast#534]

**Comment by takaishi** [comment]
オンエアの切り替え時にInternalServerErrorになって切り替えができなかった

**Comment by takaishi** [comment]
Conferenceをオープンした際、uiではなく旧Dkの配信画面に自動遷移してしまっていた

**Comment by jacopen** [comment]
From discord
"うっかりTIMETABLEをクリックすると、別タブが開いてくれないので、また1からやり直しなのはちょっとつらぽよ"

**Comment by tsukaman** [comment]
別チャンネルにチャット最新書き込みがあると、表示が切り替わってしまう。

AチャンネルにいるのにBチャンネルのチャットがでる。

**Comment by tsukaman** [comment]
「このトラックのセッション」内の2つ目のタイトルをクリックすると、再生が開始される。

**Comment by takaishi** [comment]
デバッグログが大量に流れている（ログレベル設定のミス？）

**Comment by takaishi** [comment]
ログやメトリクスを見たりk8sクラスタなどのリソースにアクセスする方法を整理しておく

**Comment by jacopen** [comment]
![image](https://user-images.githubusercontent.com/79102/109289726-f6a77180-7869-11eb-8ae2-346ea1a4b13b.png)

**Comment by ShotaKitazawa** [comment]
非常時に RDS へアクセスするための手順か何かを整理しておく
(RDS が private インスタンスなので手元から mysql コマンドは実行できない)

**Comment by jacopen** [comment]
スポンサーロゴ逆流は気になるとの意見が多い

**Comment by jacopen** [comment]
From discord:
下のプライバシーポリシー、クリックしたら別タブがいいですね

**Comment by takaishi** [comment]
コメントにたいしてリアクションしたい

**Comment by maktak1995** [comment]
プライバシーポリシー、タイムテーブルなどのリンクは別タブで開きたい

**Comment by takaishi** [comment]
チャットメッセージ内のURLはクリッカブルにしたい

**Comment by maktak1995** [comment]
未発表のプレゼンに関しては発表時間が終了するまで閲覧不可能にしておく
videoPublishedで確認？

**Comment by maktak1995** [comment]
スポンサービューの動きがきになりすぎる

**Comment by maktak1995** [comment]
チャットの更新タイミングと返信の投稿タイミングがかぶると通常の書き込みとして投稿されてしまう

**Comment by maktak1995** [comment]
コメントの削除機能がほしい

**Comment by takaishi** [comment]
`質問を送る` チェックボックスがわかりにくい気がする。`質問を送る` ボタンをもうけるほうがいいかも？

**Comment by takaishi** [comment]
スピーカーがメッセージを書いた場合はそれがわかるようにしたい

**Comment by tsukaman** [comment]
仕方ないのかも知れないけど、Vimeoの「Live」と人数の表示位置がスライドのタイトルに被ったりしている。
マウスオーバーすると消えるが、シークバーとかが代わりにでてしまうのでどちらにせよ少し邪魔になる。

**Comment by maktak1995** [comment]
アーカイブでもチャットが投稿できてしまう

**Comment by takaishi** [comment]
アーカイブに切り替えた際にチャットに投稿できないようにしたい。ただしスピーカーは投稿できる、とか必要そう

**Comment by jacopen** [comment]
Discord / Twitterリンク復活

**Comment by jacopen** [comment]
休憩時間中のDreamkastのチャットとか設定枠も考えないといけない

**Comment by jacopen** [comment]
諸々切り直したので個別のIssueをご覧ください

**Comment by jacopen** [comment]
https://github.com/cloudnativedaysjp/dreamkast-ui/issues/65
https://github.com/cloudnativedaysjp/dreamkast-ui/issues/66
https://github.com/cloudnativedaysjp/dreamkast-ui/issues/67
https://github.com/cloudnativedaysjp/dreamkast-ui/issues/68
https://github.com/cloudnativedaysjp/dreamkast-ui/issues/69
https://github.com/cloudnativedaysjp/dreamkast-ui/issues/70
https://github.com/cloudnativedaysjp/dreamkast-ui/issues/71
https://github.com/cloudnativedaysjp/dreamkast-ui/issues/72
https://github.com/cloudnativedaysjp/dreamkast-ui/issues/73
