### ISSUE TITLE
イベント当日に運用するための情報やコマンド、ツール

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#542]

**Comment by takaishi** [comment]
- prod/staging環境が使っているリソースの一覧とアクセス方法の整理
- dreamkastやUIなどのログフィールドだけをストリームで見たり、検索できるようにする
- 本番イベント中、各種リソースのスケールアウトやスケールアップが必要になった場合になにをすればいいか整理する

**Comment by jacopen** [comment]
## DBのメンテツール

### MySQL CLI

作業用Podを立ち上げて行う。このイメージにはMySQL CLIとAWS CLIがインストール済み。
バックアップが必要なときはmysqldumpコマンドを使う

```
kubectl run --rm -it --image jacopen/aws-cli-mysql test /bin/bash

mysql -h dreamkast-prd-rds.c6eparu1hmbv.ap-northeast-1.rds.amazonaws.com -u admin -p dreamkast

mysqldump --single-transaction -h dreamkast-prd-rds.c6eparu1hmbv.ap-northeast-1.rds.amazonaws.com -u admin -p --skip-column-statistics dreamkast > production20210227.dump
```

### phpmyadmin

一時的にphpmyadminを立ち上げ、ブラウザからGUIでメンテを行う。phpmyadminへはport-forwardを利用して接続する。serviceで外部公開は厳禁

```
kubectl run myadmin  --env PMA_HOST=dreamkast-prd-rds.c6eparu1hmbv.ap-northeast-1.rds.amazonaws.com --image=phpmyadmin
kubectl port-forward pod/myadmin 8081:80
kubectl delete pod myadmin  
```

**Comment by jacopen** [comment]
## 各環境の利用リソース

Dreamkastの主要コンポーネントは以下

- dreamkast
- dreamkast-ui
- redis
- mysql

このうち、StagingとProductionのMySQLのみがRDSを利用している。Stagingは `dreamkast-dev-rds` Productionは `dreamkast-prd-rds`

dreamkast, dreamkast-ui, redisはいずれもk8s上のPodとして動いている。Review appsのmysqlもPodとして動いている。
Manifestは以下のリポジトリを参照のこと
https://github.com/cloudnativedaysjp/dreamkast-infra

## その他リソース

### Secrets Manager

k8s上から利用するsecretの実体は、AWS Secret Managerに保存しており、これをexternal-secretを使って取得している。

- RDSのCredential
- RailsのMaster key
- Auth0のsecret

などを格納しているので、直接確認する必要がある場合はAWS Secret Managerから確認すること

## モニタリング・ロギング

モニタリング、ロギングともにCloudWatchを利用している。

外形監視としてSynthetics, ロギングにCloudWatch Loggingを利用。

## k8sリソースのスケールアップ/スケールイン

k8s上のPodで利用しているリソースのスケールアップが必要な場合は、dreamkast-infraのManifestを更新しpushを行う。

dreamkast
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/main/manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml#L8

dremakast-ui
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/main/manifests/app/dreamkast/base/deployment.yaml#L37

ArgoCDによって自動的に適用される。 **kubectl editやkubectl scaleコマンドを利用して直接replica数を変更しても、ArgoCDによって元に戻されてしまう** ので注意。

**Comment by takaishi** [comment]
書いてもらったので閉じとく

**Comment by takaishi** [comment]
dreamkast-clusterのパフォーマンスモニタリング https://ap-northeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-1#dashboards:name=EKS-Dreamkast-PRD
https://ap-northeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-1#container-insights:performance


RDSのモニタリング
https://ap-northeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-1#dashboards:name=RDS
