### ISSUE TITLE
セッション削除依頼（講演ご辞退）

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#549]
本体の改修でお忙しい中すみません！下記のセッションについて、講演ご辞退のため
掲載の取り下げをお願いできますか。
削除後、Dreamkastのお知らせ、Twitter等でご案内したいと思います。

bells17 さん

 [仮] CRIかコンテナランタイムに関するなにか | 
https://event.cloudnativedays.jp/cndo2021/talks/261

 [仮] KubernetesのAPI Serverについて 
https://event.cloudnativedays.jp/cndo2021/talks/251

齊藤 愼仁さん

Cloud NativeにおけるZero Trust Architecture（仮）
https://event.cloudnativedays.jp/cndo2021/talks/1101

**Comment by jacopen** [comment]
@nabemasat こちら対処完了済みです
