### ISSUE TITLE
中止セッションを扱えるようになったらよさそう

### ISSUE THREAD

**Issue by TakumaNakagame** [cloudnativedaysjp/dreamkast#557]
ただの提案です。

中止になったセッションが、それ自体が丸々消えてしまうのではなく、ある程度残り続けて中止であることが分かると良さそう。
以下みたいなのとか

- セッション詳細に中止バッヂがつく
- タイムテーブルや視聴リンクは消える
- セッション詳細ページのみ残る（外部からのリンク切れ対策）

**Comment by jacopen** [comment]
現状こちら達成されている認識なのでクローズ
