### ISSUE TITLE
ロゴ掲載依頼（LPI・LF)／取り下げ依頼（ブース：GMO）

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#562]
ロゴ掲載（ロゴスポンサー）：
The Linux Foundation
LPI-Japan

ロゴ取り下げ（ブースやらない）：
GMO Internet（ブースのみ）

となります。
急ぎですみませんが、明日3/2の夜までに本サイトへの反映をお願いします:bow:
https://docs.google.com/spreadsheets/d/1vhXSy2_ckYgWcI1sYnJz9cONBKSNGUhbzNYFbb8pgEs/edit#gid=1638690568

**Comment by jacopen** [comment]
@nabemasat 
> ロゴ取り下げ（ブースやらない）：
> GMO Internet（ブースのみ）

がどっちなのか分からないです！

**Comment by jacopen** [comment]
エクセルシートと付き合わせると、GMO Internetは『ブースから外し』『DIAMONDとしては残す』で良いですか？

**Comment by jacopen** [comment]
とりあえず↑↑の認識が合っているという前提でPullReq投げたので確認のお願いします
認識が違っていれば教えてください
