### ISSUE TITLE
参加者同士のコミュニケーション機能

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#57]

**Comment by jacopen** [comment]
Vimeoチャット機能で要件満たすか試す　
related #11

**Comment by jacopen** [comment]
6/30のディスカッションより

ユーザー情報を表示する機能を載せるのであれば
"属性・強さシールを作る(緑・黄色・赤のKubeconにあるやつ)　"

みたいな機能も載せる

**Comment by takaishi** [comment]
これ、 https://github.com/cloudnativedaysjp/dreamkast/issues/374 に統合しよう
