### ISSUE TITLE
セッション削除依頼（講演ご辞退）

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#570]
下記のセッションについて、講演ご辞退のため
掲載の取り下げをお願いできますか。
削除後、Dreamkastのお知らせ、Twitter等でご案内したいと思います。

morimorikunさん
熱いぜ、CloudNative！
https://event.cloudnativedays.jp/cndo2021/talks/381

DAEBUM LEEさん
仮）Flask application dockerization best practices for production
https://event.cloudnativedays.jp/cndo2021/talks/271

泉 将之さん
gRPC でつくる GraphQL - CloudNative とモダンフロントエンドをつなぐ Schema Driven Development
https://event.cloudnativedays.jp/cndo2021/talks/871

**Comment by jacopen** [comment]
こちら対処済みです @nabemasat
