### ISSUE TITLE
スケールアウト対応

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#63]
そういえばセッション情報を内部に持たせているので今のままだとスケールアウトできない

**Comment by inductor** [comment]
Redisとかどうするかなー。

**Comment by jacopen** [comment]
それねー。今の段階ではなくてもいけるけど、そのうち欲しくなってくる可能性もあるなぁとは思ってました。

**Comment by jacopen** [comment]
で、Herokuの場合はHeroku redisがあるのでお金さえ払えば有効化するのは一瞬
https://elements.heroku.com/addons/heroku-redis

**Comment by jacopen** [comment]
Herokuを2Dynoにスケールして確認。ログでもちゃんとリクエストが分散しているが、セッションはきちんと維持されていることを確認した。
![image](https://user-images.githubusercontent.com/79102/86385239-e6cf9180-bcca-11ea-96fa-b6fbf7e3d629.png)
