### ISSUE TITLE
全員登壇ではないイベントでスピーカー・セッションの登録方法を決めて実装する

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast#640]
CNDT2020ではCSVで流し込んだのだけど、CNDO2021移行Speakerという概念が導入され、登壇者はログインして登録するようになった。
しかし、プロポーザルを審査・採択するタイプのイベントだと登壇者をどう登録するかの方法が固まっていない。

- 登壇が決定したスピーカーを登録 or 招待する
- 登録 or 招待した後にセッションデータを登録する

ようなロジックが必要。

**Comment by takaishi** [comment]
Dk上でプロポーザルの審査まで行うのであればいいのだけど、そうじゃないので悩ましいな。

**Comment by takaishi** [comment]
1. エントリーフォームへの導線は隠しておいて、URLをスピーカーに置くってログインしてもらう
2. ログインしてもらったら運営側でトークデータを登録する

というのがいいのではないかなあ。
subフィールドが空のspeakerデータを事前に入力しておいて、スピーカーログイン時に紐付けるという手も考えたけど、例外的すぎるのでよくないと思う

**Comment by takaishi** [comment]
@jacopen なんかよさげな方法思いついてたらコメントplz

**Comment by jacopen** [comment]
> エントリーフォームへの導線は隠しておいて、URLをスピーカーに置くってログインしてもらう
> ログインしてもらったら運営側でトークデータを登録する
> というのがいいのではないかなあ。
> subフィールドが空のspeakerデータを事前に入力しておいて、スピーカーログイン時に紐付けるという手も考えたけど、例外的すぎるのでよくないと思う

そうねぇ、実装コストを低くやるならこれかなぁ・・・

**Comment by takaishi** [comment]
ではそれで。ドキュメントとして用意しておこうかな

**Comment by takaishi** [comment]
これ、CFPをサポートするので考える必要なくなったかな。
