### ISSUE TITLE
CI/CDカンファレンスのCFP受付ページを作る

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#673]

**Comment by jacopen** [comment]
CI/CDカンファレンスに向けてCFPフォームを作っていく必要がある。

CFP受付のランディングページやベースデザインは以下のPRで提出済み。
https://github.com/cloudnativedaysjp/dreamkast/pull/677

また、一部のフォームは上記PRで修正している。
主に複数選択可能な部分について追加実装が必要。

ランディングページの文言はこちら
https://docs.google.com/document/d/1rFOFB0kJFizkx9U4Umdt3-Oha3cpSS_oQqPtjbMbN88/edit#

CFPの項目はこちら
https://docs.google.com/forms/d/1Zv8x-fzE-aV5PLlwlv4hkH2ZxdNHdo2p210mad-_32Q/edit

**Comment by jacopen** [comment]
これまでtalkモデルには複数選択可能な値は無かった(はず)

今回『想定受講者』や『実行フェーズ』で複数選択可能な項目がある。

愚直に実装すると想定受講者や実行フェーズ向けの項目マスターを作って1:n:1のリレーショナルなモデルを実装することになるが、今後同様の項目が増えるたびにマスターのためのテーブルが増えてしまう。それが良い実装なのかどうかは、うーん。

1つのトークに複数の値を紐付けられるということは、タグと同じ概念として扱うことが出来ると言える。となると、既に世の中にあるタグ実装向けgemを使うといいのかもしれない。

acts-as-taggable-onというgemがあるようだ。

https://qiita.com/ddd555/items/e1caa8b73d118822a0a2
https://qiita.com/you8/items/b2394104c6f9865f5d46

**Comment by takaishi** [comment]
proposl_item_configというテーブルを追加して、ここに各項目毎の設定をレコードとして記録する。項目毎にテキストフィールドだったりラジオボタン、チェックボックスと性質が異なるがSTIを使って吸収する。これにより、DB上でプロポーザルの項目を動的に設定できる。
スピーカーがフォームから登録した各項目のデータはproposal_itemというテーブルに保存していく。これもSTIでうまく吸収できるはず。

**Comment by takaishi** [comment]
DB的にはうまく吸収できてるけどRails的にここをうまくやるのがめちゃ難しいな。動的にattributes or associationを設定するかmodelを生成するようなことをしないといけなさそう。

**Comment by takaishi** [comment]
フォームの項目を動的生成するのはスコープから外して、1テーブルで項目の値の管理を行うのをやる

**Comment by takaishi** [comment]
うーん、うまくいかん。時間ないしもう他の項目と同じようなやりかたにしてリファクタリングissue積む方がいいんじゃないかなあ

**Comment by jacopen** [comment]
acts-as-taggable-onとかでうまくいかない？
