### ISSUE TITLE
CI/CD CFPページ：スマホで表示すると、ランディングページの画像が引き伸ばされてしまう

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#685]
動作に支障はないので、優先度は低めで良いかと思います

環境：iPhone 11 Pro + Safari, Chromeで確認

![IMG_2178](https://user-images.githubusercontent.com/31978147/120205882-711acf80-c265-11eb-8efc-102097bac7e3.PNG)
![IMG_2177](https://user-images.githubusercontent.com/31978147/120205893-76781a00-c265-11eb-9e05-e851559f29df.PNG)

**Comment by jacopen** [comment]
わーお。これはかっこわるい、直します

**Comment by jacopen** [comment]
開発者ツールで再現しない･･･
![image](https://user-images.githubusercontent.com/79102/120206468-31081c80-c266-11eb-8614-075b200e1482.png)

**Comment by jacopen** [comment]
@nabemasat 
あれ、自分のiPhone実機では再現しないのですが、何かプラグインとか使ってますか？

**Comment by nabemasat** [comment]
@jacopen いえ、特に使っていないです。思い当たることとしては、IOSアップデートしてなかったことぐらい、、アップデート後再度試してみます:bow:

**Comment by nabemasat** [comment]
@jacopen 
アップデートしたら正しく表示されました。お騒がせしてすみません:bow:
![5B1DD9B1-42AC-478C-95F8-3534A524E5F1](https://user-images.githubusercontent.com/31978147/120242517-fe7b1580-c29f-11eb-9c0f-b52c3c94af76.png)
