### ISSUE TITLE
CI/CD CFPフォーム：資料URL・ビデオファイル登録ボタンを削除したほうが良いかも

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#686]
CFP申込の段階で、資料URLやビデオのアップロード項目があると混乱を招くので、できれば削除したほうが良いかと思います
（既に対応予定でしたら、見落とし申し訳ないです:bow:)

<img src="https://user-images.githubusercontent.com/31978147/120206273-f43c2580-c265-11eb-9e2e-d0c1c264bf97.PNG" width="25%">
<img src="https://user-images.githubusercontent.com/31978147/120206284-f8684300-c265-11eb-931d-47bf0e94a7b6.PNG" width="25%">

**Comment by jacopen** [comment]
あぁ～、そうですね、今の段階では不要ですね・・・フラグ使ってCFP段階では表示しないようにします

**Comment by jacopen** [comment]
僕も今日HIITやって足がプルプルです
