### ISSUE TITLE
CFP落選の場合の処理を追加

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#687]
現状落選の概念がなかったCNDO向けのままなので、落選した際になにをどう応募者に見せるかの機能が必要

**Comment by takaishi** [comment]
メモ：CFP周りは https://github.com/cloudnativedaysjp/dreamkast-kanban/issues/32 のEpicで進める。

**Comment by takaishi** [comment]
https://app.zenhub.com/workspaces/dreamkast-606334299078c100130630da/issues/cloudnativedaysjp/dreamkast/687#issuecomment-855370494 の通り別EpicでやるのでこのIssueは閉じる
