### ISSUE TITLE
セッションの表示画面の実装

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#7]
これが一番時間かかりそうな気がする

**Comment by takaishi** [comment]
セッションとスピーカーの表示の実装が形になってきた。

セッション一覧：

![image](https://user-images.githubusercontent.com/107187/85734004-a22a8000-b737-11ea-8445-662913dfd58b.png)

セッション個別ページ：
![image](https://user-images.githubusercontent.com/107187/85734032-a6ef3400-b737-11ea-8ce0-ea5c42bc5534.png)

スピーカー一覧：
![image](https://user-images.githubusercontent.com/107187/85734055-ac4c7e80-b737-11ea-8921-ee514565cf61.png)

**Comment by takaishi** [comment]
セッション登録・編集の画面を実装する場合はは権限を持つユーザでなければできない、という風にしないといけないか。
最悪表示だけにして、DBに流し込めば公開には間に合う？

**Comment by jacopen** [comment]
あーそうか、ロールの設定機能が必要なんだなぁ。
今回は表示だけでいいかも

**Comment by takaishi** [comment]
表示の実装はできた

**Comment by takaishi** [comment]
v0.1.0の時点でタイムテーブルの表示は必須なんだっけ？

**Comment by jacopen** [comment]
申し込みページまで必要なので必要、、、

**Comment by takaishi** [comment]
- 単純にタイムテーブルを表示する画面の実装
- 申し込み時にどのセッションを聞くかを選択する画面の実装

の2つが追加で必要という感じかなあ。別にissue立ててやるか

**Comment by jacopen** [comment]
#75 #76

**Comment by takaishi** [comment]
あざっす

**Comment by takaishi** [comment]
トーク、スピーカーなどの登録は https://github.com/cloudnativedaysjp/dreamkast/pull/70 でCSVから実行できるようになっている

**Comment by takaishi** [comment]
これはクローズでいいか
