### ISSUE TITLE
「参加申し込み受け付けました」メールの配送

### ISSUE THREAD

**Issue by oshiro3** [cloudnativedaysjp/dreamkast#707]
視聴セッションの登録でメールを送信する

**Comment by jacopen** [comment]
ここらへんでメールを送信する処理を入れるとよさそう
https://github.com/cloudnativedaysjp/dreamkast/blob/main/app/controllers/profiles_controller.rb#L32-L33

現時点ではタイムテーブルにリダイレクトされたときにエラーが起きるけどこのIssueでは気にせず進める
