### ISSUE TITLE
登壇者のアイコンを登録・表示できるようにする

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast#71]
画像ファイルをどう扱うか決めないといけない

ref: https://github.com/cloudnativedaysjp/dreamkast/issues/7

**Comment by takaishi** [comment]
ActiveStorageでS3にアップロードする、のが手軽？Herokuだと何か使えるのかな

**Comment by jacopen** [comment]
ActiveStorageかなぁ。ただ、どのアカウントのバケットに上げるか調整しないといけない

**Comment by takaishi** [comment]
ActiveStorage + LocalDiskで表示部分の実装をします

**Comment by takaishi** [comment]
これ、誰がアップロードする想定にするのがいいかな。最終的にはスピーカーが自分で登録する、だけどv0.1.0だと運営サイドでやる形かな

**Comment by jacopen** [comment]
そうねえ、0.1.0だと運営サイドでいいかも

**Comment by takaishi** [comment]
できた。
