### ISSUE TITLE
セルフサービスによるスポンサーセッション登録機能

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#713]
スポンサーが何社か決まってきましたので、スポンサーセッションのエントリーフォームを作成頂けないでしょうか。

イメージ
- CFPエントリーフォームを流用
- 登録後は、一般セッションとスポンサーセッションが一元的に管理できるイメージ
- スポンサーセッションであることが管理画面などで分かるようになっていると助かります

関連？：
https://github.com/cloudnativedaysjp/dreamkast-kanban/issues/32

**Comment by takaishi** [comment]
なるほど確かに。

**Comment by takaishi** [comment]
* スポンサー側の人を表すためのモデルとテーブルを追加
* スポンサーとしてログインを許可するためのカラムをスポンサーテーブルに追加する。ここにはメールアドレスを格納してその人がスポンサーの人であることを判別する（メールアドレスはauth0でのログインに使うメールアドレスを指す）
* スポンサーとしてログインした場合、スポンサーダッシュボードを表示する。スポンサー関連の情報やスポンサーセッションの登録・更新を行えるようにする
* Talkにスポンサーと紐づけるためのカラムを追加する。スポンサーIDを格納。

**Comment by takaishi** [comment]
> スポンサー側の人を表すためのモデルとテーブルを追加

TalksがSpeakerとスポンサー側の人の2つと紐付くのでややこしい気もするが…

**Comment by takaishi** [comment]
スポンサーダッシュボードからスピーカーとトークを作成・編集できるようにするのがよさそう。スポンサーダッシュボードから作成した場合はスピーカー・トークともにスポンサーに関連づけるようにする。

**Comment by takaishi** [comment]
https://github.com/cloudnativedaysjp/dreamkast/pull/718 で実装中

**Comment by jacopen** [comment]
これは終了で良いかな？

**Comment by takaishi** [comment]
https://github.com/cloudnativedaysjp/dreamkast/issues/713 をマージしたら閉じる
