### ISSUE TITLE
申込フォームへのIBM専用項目の実装

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#72]
申込フォームに下記の項目の実装をお願いします。

<del>掲載イメージは添付ファイルを参照してください。</del>すみません！若干変更が入り、画像差し替えました

チェックボックス（任意回答）

項目名：
IBMおよびIBMの⼦会社、関連会社からの情報提供

選択肢：
e-メールを希望する
電話を希望する
郵便を希望する
(デフォルトではチェックは全て空欄、
オーディエンス側が能動的に✔を入れる形にする)
![3611A3F1-2062-43EA-A372-C50850A2C4F3](https://user-images.githubusercontent.com/31978147/86191632-7fa6c580-bb82-11ea-8d4e-72230a41acda.jpeg)

説明書き：

IBMおよびIBMの⼦会社、関連会社から、製品、サービス、オファリングに関する情報をお送りさせていただく場合があります。 マーケティングに関する同意は、netsupp@us.ibm.com にEメールを送信していつでも取り消すことができます。また、該当のEメール内の、購読を中⽌するためのリンクをクリックすることで、マーケティングに関するEメールの受信を中⽌することができます。 処理に関する詳しい情報は、IBMプライバシー・ステートメントをご覧ください。このフォームを送信することで、私はIBMプライバシー・ステートメントを読み、これを理解したものとします。
![014057FF-5C5B-40EF-B447-9CD35850C41D](https://user-images.githubusercontent.com/31978147/86191654-90efd200-bb82-11ea-97bf-0d62c1e00c2e.jpeg)

**Comment by jacopen** [comment]
ぐえ、Yes/Noだけでなくチェックボックスもありなのか

**Comment by nabemasat** [comment]
すみません🙇‍♂️文言に若干変更が必要とのことで、本文更新しました🙇‍♂️

**Comment by jacopen** [comment]
@nabemasat 文中に**IBMプライバシー・ステートメントをご覧ください**　とありますが、そのプライバシーステートメントはどうしましょう。リンクとかありますか？それとも文章うめこみ？

**Comment by takaishi** [comment]
プライバシーステートメントの話がまだ解決していない状況かな

**Comment by jacopen** [comment]
そうれす

**Comment by nabemasat** [comment]
@jacopen @takaishi 
遅くなりすみません！
プライバシー・ステートメントのリンクです　→ https://www.ibm.com/privacy/jp/ja/

**Comment by nabemasat** [comment]
@jacopen 

IBM文言の実装ありがとうございます。
早速IBM担当者の確認を取ったのですが、以下のように差し替えてほしいとのことです:bow:
お手数をおかけしますがよろしくお願い致します。

説明書き：

IBMおよびIBMの[⼦会社、関連会社](https://www.ibm.com/ibm/jp/ja/keireki.pdf#subsidiaries)から、製品、サービス、オファリングに関する情報をお送りさせていただく場合があります。 マーケティングに関する同意は、[opt-out request](https://www.ibm.com/account/reg/jp-ja/signup?formid=urx-42537)を送信することにより、いつでも取り消すことができます。また、該当のEメール内の、購読を中⽌するためのリンクをクリックすることで、マーケティングに関するEメールの受信を中⽌することができます。 処理に関する詳しい情報は、[IBMプライバシー・ステートメント](https://www.ibm.com/privacy/jp/ja/
)をご覧ください。このフォームを送信することで、私はIBMプライバシー・ステートメントを読み、これを理解したものとします。

リンク先：
opt-out request : https://www.ibm.com/account/reg/jp-ja/signup?formid=urx-42537

IBMプライバシー・ステートメント：https://www.ibm.com/privacy/jp/ja/

子会社/関連会社：https://www.ibm.com/ibm/jp/ja/keireki.pdf#subsidiaries

**Comment by nabemasat** [comment]
@jacopen ご対応ありがとうございました！IBMにも確認取れ、OKとのことでした！
