### ISSUE TITLE
申込フォームへのプライバシーポリシー文面の追加

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#73]
申込フォームに、下記の文面の掲載をお願いします。スポンサーに関する記載は、視聴時のオプトインで良いかと思ったのですが、確認したところ、文面掲載の必要しないとダメとのことでした。

------------------------
ご登録頂きました個人情報はイベントの運営会社である株式会社インプレスが管理し、電話/電子メール/郵送等による、各種サービスやセミナー開催情報などの情報提供に利用させて頂きます。インプレス社の詳しいプライバシーポリシーに関しましてはこちらをご覧下さい。 
https://www.impress.co.jp/privacy.html

また、スポンサーセッションに関しては当該セッションのご登録者の個人情報を本セミナー協賛企業（各種スポンサー）へ提供いたします。以下に記載の協賛企業からご登録者の皆様に、直接電子メールや郵送でご案内をさせていただく場合がございます。

 ≪協賛企業≫
リスト提供企業社名一覧
 （随時増えていくことが予想されるため、運営スタッフで書き換えられるとありがたいです）
 
 業務委託先または提携先へ業務預託する場合がございますが、個人情報をお客様の承諾なしに目的外利用すること、及び第三者に提供することはございません。なお、開催日までに協賛企業（各種スポンサー）、講演提供企業が追加となりました場合は、セミナーWebサイトに公開しますとともに、追加となりました協賛企業ともご登録情報を共有させていただきます。あらかじめご了承の上、お申し込みをお願いいたします。

**Comment by takaishi** [comment]
マージ済みなのでクローズしておきます
