### ISSUE TITLE
8/1締切 CNDT2021 CFP open

### ISSUE THREAD

**Issue by MasayaAoyama** [cloudnativedaysjp/dreamkast#730]
7/30 金曜日までにコメント追加がなければこれで確定

CFPページ
https://docs.google.com/document/d/1CMHNvurrmcVX8shgxkbIj3kBLTNBnckxsVHjhzhuOeI/edit#

フォーム
https://docs.google.com/forms/d/1Ua468ziCUbUFCxonPBIHn3EAHefHVq4qDfLNzZ1MiZY/edit

```
変更点
　[廃止] Orchesteration
　[追加] Application / Development
　[修正] ML / GPGPU / HPC > ML / HPC
```

**Comment by MasayaAoyama** [comment]
コメント無いのでこれで確定で。

**Comment by takaishi** [comment]
- speaker profile
  - 現状のnameカラムを英語表記で使って、新しくname_kanjiカラムを追加する（kanji というよりは母語の表記という表現にしたいがいい名前は思いつかない）
  - その他質問事項 - Question to the organizer をどうやるのがいいか
- session
  - カテゴリーを追加しないといけない
  - スライドと動画の公開可否 を追加しないといけない
  - 必要とする講演時間を追加しないといけない
  - 講演言語を追加しないといけない

**Comment by jacopen** [comment]
@MasayaAoyama 講演者氏名が英語表記と漢字に分かれているんだけど、これ二つ必要かな？(CNDO, CICDでは分かれていなかった)　もし強い要望がなければ従来通りに行きたいです

あと『その他質問事項』についても、是が非でも欲しいというわけでなければ無しがよいです

**Comment by MasayaAoyama** [comment]
@jacopen 

> 講演者氏名が英語表記と漢字に分かれているんだけど、これ二つ必要かな？(CNDO, CICDでは分かれていなかった)　もし強い要望がなければ従来通りに行きたいです

CNDT2020をベースに策定しましたが、CNDO・CICDでは英語表記とってなかったんですね。
英語表記・漢字が必須というわけではありませんが、名前と漢字の場合は可能であれば読み方も入力しておいていただきたいです。
（活かせてませんでしたがCNDT2020でも、紹介するときに名前のよみがなググったりしてたので）

> あと『その他質問事項』についても、是が非でも欲しいというわけでなければ無しがよいです

削除しました。

**Comment by takaishi** [comment]
漢字用フィールドの追加はローコストなんで問題ないです。
