### ISSUE TITLE
8/上旬締切 ハンズオン紹介ページの追加

### ISSUE THREAD

**Issue by MasayaAoyama** [cloudnativedaysjp/dreamkast#732]
discussion boardページと同じような形式でハンズオン紹介ページの作成をお願いしたいです。

* ハンズオン紹介ページ
https://docs.google.com/document/d/1fwnV2h89nb_nE9oHDiQr-1-gevVZFudTdDdF_pZ6isg/edit#

**Comment by MasayaAoyama** [comment]
可能であればサイトオープンと同時が良かったですが、手配が遅れてしまったため上旬目安で手配頂けると助かります 🙇🏻 🙇🏻 🙇🏻

**Comment by takaishi** [comment]
yarimasu
