### ISSUE TITLE
スポンサー追加・修正のお願い（CI/CD)

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#754]
@jacopen @takaishi
すみません。お手すきのタイミングで下記二点ご対応をお願いいたします🙇
CMスポンサー追加：LegalForce様
スポンサーランク修正：サイバーエージェント様・LINE様 PLATINUM→GOLD

ロゴファイル・リンク先：
https://docs.google.com/spreadsheets/d/1EVJdFaA_WRgIyrgN8R0EDJy8KSNNRQzoIKuMDwxZrsA/edit?usp=sharing

**Comment by takaishi** [comment]
yarimasu

**Comment by takaishi** [comment]
ロゴ画像の背景が透過じゃないけどこれはいいんでしたっけ

**Comment by nabemasat** [comment]
@takaishi 
すみません。ロゴデータ、透過pngありましたので、こちらでお願いします
（前回の流用）
https://docs.google.com/spreadsheets/d/1EVJdFaA_WRgIyrgN8R0EDJy8KSNNRQzoIKuMDwxZrsA/edit#gid=0
