### ISSUE TITLE
CFPが終わったので speaker_entry_button を消す (cicd2021)

### ISSUE THREAD

**Issue by suzukin** [cloudnativedaysjp/dreamkast#755]
コード読んでPR出そうと思ったんですが時間かかりそうなのでひとまずissue立てます

**Comment by takaishi** [comment]
管理画面から非表示にできるのでやっておきました

**Comment by takaishi** [comment]
`Edit` を押して編集画面に遷移して、 `Speaker Entry Status` をdisabledに変更すればOKです

![image](https://user-images.githubusercontent.com/107187/128354155-4920cf8d-99ff-4b5d-b781-301f8e58cd23.png)

**Comment by suzukin** [comment]
なるほど管理画面で機能として実装済みなんですね、対応ありがとうございます！
