### ISSUE TITLE
CI/CD:スピーカーダッシュボードの動画アップロード機能の有効化

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#771]
@jacopen @takaishi 
そろそろ動画の提出期限が近づいてきたので、
スピーカーダッシュボードの動画アップロード機能を有効化をお願いします:bow:
8/15（日）までに対応頂けると助かります！

※厳しい場合は、フォームでの収集など別の方法で実施します

**Comment by takaishi** [comment]
既に動画アップロード機能は使える状態のはずです（今ｈ動画をダウンロード可能なURLを貼るフォームになっています）
