### ISSUE TITLE
Ask the speaker を oVice に変更

### ISSUE THREAD

**Issue by suzukin** [cloudnativedaysjp/dreamkast#781]
ダッシュボードの運営からのお知らせの部分です、以下に変更いただけると！

Ask the speaker (oVice)

https://cnd.ovice.in/

![Screen Shot 2021-08-17 at 14 11 38](https://user-images.githubusercontent.com/5789999/129667215-8e8393b4-8355-4623-94ff-6a64a8220010.png)

**Comment by suzukin** [comment]
視聴画面のほうにもボタンがありそう

**Comment by suzukin** [comment]
サービスロゴはこちら
https://ovice.in/wp-content/uploads/2015/12/textLogo_drakBlue_192x60Size.png

**Comment by jacopen** [comment]
サービスロゴ、透過のものが欲しいですね・・・
