### ISSUE TITLE
CICD2021: 登壇者だけどスピーカーダッシュボードに入れない

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#782]
内容：
複数の登壇者から、ログインしても、右上のメニューからスピーカーダッシュボードへの導線が表示されない（一般参加者のダッシュボードのみ）と報告あり。そのため、動画のアップロードができない

![image](https://user-images.githubusercontent.com/31978147/129695034-9778e61d-317f-487f-902b-c2d216c1e201.png)

報告があった登壇者のID：
下記のスプレッドシートに記載しています
https://docs.google.com/spreadsheets/d/1OLQJfGdtmGqh4jEUXiCzhjVoMfG2fzanwy7uS0TLfXY/edit?usp=sharing

推測：
ダッシュボードが表示されなかった登壇者は一般参加者としても登録済み（登録できた登壇者は未申込）
そのため、申込時に権限が上書きされてしまったのではないか

**Comment by takaishi** [comment]
表示・非表示の制御ロジック側の問題だったので修正します。権限の問題ではないです。

**Comment by takaishi** [comment]
@nabemasat 修正されたので導線見えるようになっているはずです
