### ISSUE TITLE
要望 CNDT2021：参加者登録フォームの項目変更

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#787]
インプレスからの要望で、社内リストへの登録作業の都合、参加者登録フォームを下記のように変更してほしいとのことですが、対応可能でしょうか。

・勤務先住所部分、都道府県部分の入力を必須にしてほしい
・プルダウン式で別枠で入力できるようにするなど

理由：都道府県の記入漏れ・省略が多いため

![スライド1](https://user-images.githubusercontent.com/31978147/129834106-422bd04e-a1f9-4179-8e68-d20ef5ff5b11.jpeg)

**Comment by jacopen** [comment]
そこまで難しくはないので対応します。CICDは対応不要でCNDT向けということでいいですよね？

**Comment by nabemasat** [comment]
@jacopen 
すっかり遅くなってしまい申し訳ありません:bow:
もちろんCNDTからです！

**Comment by takaishi** [comment]
勤務先住所が日本じゃない可能性もあると思うのですが、そういうケースは考慮しなくてもよいのでしょうか？

**Comment by jacopen** [comment]
@nabemasat ↑の件について方針決めお願いしますー

**Comment by nabemasat** [comment]
@takaishi @jacopen 
遅くなりました。
一旦、都道府県で「国外」の項目を追加して頂けますか？
勤務先住所は、「市町村から」の記載を削除してください
