### ISSUE TITLE
スポンサー向け情報提供画面の実装

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#8]

**Comment by nabemasat** [comment]
希望する機能：
・CSV形式でダウンロード
・各ユーザーと紐付いて、申込時の個人情報（同意済みのもの）、どのセッションに登録したか、どのセッションを視聴したか、どのPDF資料（ブース）をダウンロードしたかを取得する
・できれば各スポンサーごとに別々に取得できると助かります

・サンプル
https://docs.google.com/spreadsheets/d/1ijKebszhVHn1R2NgyiGvIF8WzUtwFbjcrfAj0lyEbbY/edit#gid=0

**Comment by takaishi** [comment]
これもKarteでトラッキングできるのかな

ref: https://github.com/cloudnativedaysjp/dreamkast/issues/248

**Comment by jacopen** [comment]
これらはDreamkastのDBから
- 申込時の個人情報（同意済みのもの）
- どのセッションに登録したか

これはKarteから
- どのセッションを視聴したか

これはどうするか悩ましいなー。でも、Rails側で取った方が楽なような気はしてる
- どのPDF資料（ブース）をダウンロードしたかを取得する

**Comment by jacopen** [comment]
@nabemasat 
ちなみにスポンサー向けの情報提供って、イベント終了後にデータまとめて渡せばそれで終わり、という認識なんですけど、それで合ってますかね？

リアルタイムにスポンサーが情報を取得できるようにってなると難易度途端に跳ね上がるので

**Comment by MasayaAoyama** [comment]
資料ダウンロードはJS発火しないので、普通にアクセスログから取ったほうが楽そうですねぇ

**Comment by nabemasat** [comment]
@jacopen 

>ちなみにスポンサー向けの情報提供って、イベント終了後にデータまとめて渡せばそれで終わり、という認識なんですけど、それで合ってますかね？

ありがとうございます。終了後にまとめて渡す仕様でOKです。リアルタイムな情報取得はナシでお願いします。

**Comment by jacopen** [comment]
メモ: 残りはPDFダウンロードログの実装

**Comment by takaishi** [comment]
PDF、普通にS3上のファイルのURLなのでdreamkast側で検知できないのでは…？

**Comment by takaishi** [comment]
Railsにダウンロード用のルートを生やせばいける気がするので試そう

**Comment by takaishi** [comment]
ルート生やしてPDFダウンロード時にフックしてLoggingモジュールのログ機能を使えた

**Comment by takaishi** [comment]
Loggingモジュール、アクセ視した人の名前だけ保持してるけどこれはProfile.idを保持するほうがいいのでは…？

**Comment by jacopen** [comment]
最初のプロトタイプ版で作ったやつで、たぶんProfileって概念が無いときにつくったやつだ・・・ 今なら間違いなくprofile.idのほうがいいね

**Comment by takaishi** [comment]
両方とも取得できるようになっているので完了

```
Masato Nabeshima  2:08 PM
@r_takaishi
はい、ブース画面でトラッキングする必要があるのは、
- スポンサーセッションの資料のダウンロード履歴

Masato Nabeshima  2:08 PM
- 動画の視聴履歴
2:08
の二点です
```
