### ISSUE TITLE
CI/CD Conference の Twitter シェア時のタグが公式のものと異なる

### ISSUE THREAD

**Issue by y-taka-23** [cloudnativedaysjp/dreamkast#816]
CI/CD Conference の公式のタグは `#CND_CICD2021` であるとアナウンスされているが、現在の実装では `hash_tag` として `conference.abbr.upcase` を指定しており、この値は `CICD2021` となる。

- https://twitter.com/cloudnativedays/status/1431908921501896705
- https://github.com/cloudnativedaysjp/dreamkast/blob/65af50d65643880405735ebfabdf16f5e1555da5/app/views/talks/partial_show/_col_main_pane.html.erb

**Comment by jacopen** [comment]
こちら `#CICD2021`  が正となったのでissueは閉じます。ご連絡ありがとうございました！
