### ISSUE TITLE
外部システムからAPIを呼べるように認証の仕組みを用意したい

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast#828]
dkチーム以外の人もdkのAPIを活用できるようにしたい。

**Comment by jacopen** [comment]
例えば #1247 あたりの機能に欲しいやつ

**Comment by jacopen** [comment]
https://auth0.com/docs/quickstart/backend/rails
あたりを参考に追加実装していけばいけるかな
