### ISSUE TITLE
https://cloudnativedays.jp/のリンク貼り替え

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#829]
CI/CD Conference から CNDT2021にリンクを貼り替えをお願いします:bow:
https://cloudnativedays.jp/

もしくは毎回作業がお手間だと思うので、
https://event.cloudnativedays.jp/
へのリンク、またはリダイレクトでも良いかと。

**Comment by jacopen** [comment]
こちらはDreamkastではなくてwebsiteのほうになるので一旦Issue閉じますね
