### ISSUE TITLE
CNDT2021スポンサー セッション情報登録エラー

### ISSUE THREAD

**Issue by TomikoTerayama** [cloudnativedaysjp/dreamkast#837]
NTTデータさん（id74）で、アカウント登録後に設定したパスワードでログインしようとすると、エラーとなってしまうようです。
以下のようにご連絡いただいておりますので、ご確認いただけますでしょうか。
```
Windows上のChrome, Edge, iPad上のChrome, Safariで試したのですが、同様のERR_TOO_MANY_REDIRECTSが出てしまうようです。
ChromeのCookieを削除して試してみましたが同様でした。
URLを見ていると、
https://event.cloudnativedays.jp/cndt2021/sponsor_dashboards/login
から
https://event.cloudnativedays.jp/cndt2021/sponsor_dashboards/74/sponsor_profiles/new
にリダイレクトされまして、
https://event.cloudnativedays.jp/cndt2021/sponsor_dashboards/login
にさらに戻るように見えています。
アカウント番号74でなにか中途半端な状態が起こっているような気もしますので、
ご確認いただけないでしょうか？
![NTT](https://user-images.githubusercontent.com/30485520/133219000-60805827-edc7-4114-9d9c-90ba7ecf8239.png)
```

**Comment by takaishi** [comment]
調査します！

**Comment by jacopen** [comment]
@TomikoTerayama 

## 現状

こちら、現在は解消していると思われますので再確認するよう先方にご連絡ください

## もう一つ確認したいこと

今回の問題なのですが、dreamkastに手入力されたメールアドレスは先頭が大文字で登録されています。しかし、実際にログインを試みたアカウントは小文字になっているようで、その違いによりDreamkastにより異なるメールアドレスと判断され今回の問題が発生していました。

Dreamkast側の変更により問題は解消していると思われますが、今後のトラブルを防ぐため、登録された先頭が大文字のメールアドレスが正しいものか、ご確認頂ければと思います。

## ちょっと細かい話(時間がなければ読み飛ばして頂いても大丈夫です)

メールアドレスの仕様としては、大文字と小文字は区別すると定義されているようです。つまり、仕様に従うと `Jacopen@example.com` と `jacopen@example.com` は別のアドレスとして扱うのが正しいということになり、メールアドレスを別物と判断したDreamkastの動きは正しいものなります。

しかしながら、上記のような仕様がある一方で、世の中の多くのシステムは大文字を小文字を区別しない慣習になっているようです。うっかり入力ミスによる誤送信を防ぐためこのような運用になっているとのことです。これは自分もDreamkastチームメンバーも初めて知った内容でした。
システムの連携ということを考えるとDreamkastも慣習に従うべきと考え、不具合として修正対応を行いました。

https://www.istartips.com/ja/are-emails-case-sensitive.html

ですが、ユーザー情報の登録的にはやはり大文字小文字は一致しておいた方が今後も不要なトラブルを回避する意味でも好ましいと思われますので、先方から頂いたメールアドレス情報と正しいかどうか確認をお願いします。

**Comment by TomikoTerayama** [comment]
@jacopen 遅くまでご対応いただきありがとうございました。メールアドレス含め先方に確認の依頼をしました。
事務局からは、先頭大文字のメールアドレスで設定したことを共有し、先方からも大文字の` Yuji.Ito@nttdata.com`をアカウントとして利用したという共有を受けておりましたが、実際には小文字になっていたとうことですね。。。
諸々確認が取れましたらご報告いたします。

**Comment by jacopen** [comment]
@TomikoTerayama ご確認ありがとうございます！ 
> 先方からも大文字の Yuji.Ito@nttdata.comをアカウントとして利用したという共有を受けておりましたが

なるほど、となると中間に入る認証用のサービスがありまして、そこが↑にあったような大文字小文字を区別せずにDkに送ってきているという可能性がありそうですね。いずれにせよDk側の修正は避けられなかったですね。。

お手数おかけしました

**Comment by TomikoTerayama** [comment]
@jacopen こちら、ログインできたとのご報告を受けました。
メールアドレスについては、正式には先頭を大文字にしたメールアドレスが正となりますが、実際は@以前は大文字小文字区別せずに配送されるとご報告がありました。
アカウント登録する際に、小文字で誤って入力してしまったようですとのこと。
ご対応ありがとうございました。

**Comment by jacopen** [comment]
承知しました、ありがとうございますー

ではこちらのIssueはクローズしますね
