### ISSUE TITLE
CNDT2021スポンサー セッション追加ボタンが表示されない

### ISSUE THREAD

**Issue by TomikoTerayama** [cloudnativedaysjp/dreamkast#840]
Splunk Services Japan合同会社（id64）より、以下の2点をご確認いただけますでしょうか。
１．スピーカー情報を入れてセッション情報を入れようとしているが「セッションを追加する」ボタンが見当たらない。
２．最初のログインの際に、仮で入れた名前を講演者の名前に変更する方法を教えて欲しい。
現状「横山勇さんのスピーカープロフィール」となっているところを「大谷 和紀」に変更したい。

**Comment by jacopen** [comment]
@TomikoTerayama 
1点目に関してはそのスポンサーだけがセッション追加できないというのはおそらく考えづらいので、ボタンを見つけられてないだけかと思っています。
スピーカー情報を入力して保存した状態であれば、再度editボタンを押しそのページ内にセッションを追加するボタンがあるはずです。

2点目に関してですが、現時点ではそこを修正する機能を考えていなかったため、こちらで修正しますね

**Comment by TomikoTerayama** [comment]
ありがとうございます。先方に確認してみます！

**Comment by TomikoTerayama** [comment]
@jacopen 先方に確認をいただきましたが、セッション追加ボタンが表示されないということです。
スピーカー情報の入力フォーム出ますが、画像のようになっているそうです。
こちらご確認いただけますでしょうか。
![Splunk](https://user-images.githubusercontent.com/30485520/133405280-0b8d1abc-2e27-40d2-99cf-0f2c7dc74f3e.png)

**Comment by jacopen** [comment]
@TomikoTerayama 
はい、その見切れているところにEditボタンがあって、そのボタンを押すと編集画面に飛び、その下の方にセッション追加があるはずなんですよね。

**Comment by jacopen** [comment]
画面全体のスクリーンショットが欲しいですねー

**Comment by TomikoTerayama** [comment]
画像の再送を依頼します

**Comment by jacopen** [comment]
@TomikoTerayama あ、すみません、ちょっと他のパターンで確認してみたところ、確かに登録ボタンが出ないケースを見つけました。恐らくSplunkさん以外でも同様に発生しうる可能性があります。

先方に問題が確認できた、かつ調査して修正が終わったら再度連絡すると、ごめんなさいメール送っていただけますか？ 

あと問題の解消までに他のスポンサー様から連絡があった場合も、対処中と連絡して頂ければと思います

**Comment by TomikoTerayama** [comment]
@jacopen 承知しました！
引き続き、ご対応よろしくお願いいたします。

**Comment by jacopen** [comment]
@TomikoTerayama こちら対応完了しました！ 先方に再確認依頼お願いします

**Comment by TomikoTerayama** [comment]
ご対応いただきありがとうございました！
先方に確認をしておりますので、また後ほどご報告いたします。

**Comment by TomikoTerayama** [comment]
@jacopen セッション情報の登録ができたこと確認いたしました。
ご対応いただきありがとうございました！

**Comment by jacopen** [comment]
よかったです、お手数おかけしましたー
