### ISSUE TITLE
CNDT2021スポンサー セッション情報が登録できない

### ISSUE THREAD

**Issue by TomikoTerayama** [cloudnativedaysjp/dreamkast#847]
CircleCI合同会社(id61)さんで、以下の報告を受けましたのでご確認いただけますでしょうか。
----------
スピーカープロファイルは登録できたのですが、セッション情報が登録できない(登録用のボタンが表示されない)です。
何度かに一度表示されるかされないかを繰り返しております。
----------

**Comment by takaishi** [comment]
@TomikoTerayama こちら調査開始しています。その上で、何点かスポンサー担当者の方に確認をお願いしたいです。確認事項は以下の4点です。

1. 表示されない登録用のボタンとは以下画像内の `セッションを追加する` ボタンのことであっていますか。

![image](https://user-images.githubusercontent.com/107187/133759035-c7742913-a45f-4d9e-a9e1-f0978a0a93ba.png)

2. `何度かに一度表示されるかされないかを繰り返しております。` とのことですが、表示されている時とされていない時のキャプチャをもらうことは可能でしょうか。
3. `何度かに一度表示されるかされないかを繰り返しております。` とのことですが、表示されている際にボタンを押した際にどのような挙動をするか教えていただきたいです。また、その際のキャプチャをもらうことは可能でしょうか。
4. 利用しているブラウザーは何でしょうか。

**Comment by TomikoTerayama** [comment]
@takaishi ご対応いただきありがとうございます。先方に確認いたします。

**Comment by TomikoTerayama** [comment]
@takaishi @jacopen お待たせしました。回答いただきましたので、ご確認いただけますでしょうか。
１．はい、セッション情報を追加するボタンです。
２．添付にて表示されていない時を共有します。一度のみしか表示されず、その後も表示されていない状態です。
３．スピーカー情報を登録するような入力欄が表示されました。
４．Version 93.0.4577.82 (Official Build) (x86_64)
<img width="1792" alt="circleci" src="https://user-images.githubusercontent.com/30485520/134093848-aab5ec2d-1ab7-4c42-baae-229dfa586254.png">

**Comment by takaishi** [comment]
@TomikoTerayama 確認ありがとうございます。解決策と原因は下記の通りと思われますので、回答をお願いします。

まず、結論としてはアクセスするページが異なっているためセッション情報を追加するボタンが表示されていません。https://event.cloudnativedays.jp/cndt2021/sponsor_dashboards/login からスポンサーセッション登録画面に進んでもらうと、セッションの登録が可能なはずです。

いただいたキャプチャですと https://event.cloudnativedays.jp/cndt2021/speaker_dashboard にアクセスしていますが、このページはスポンサー以外のスピーカーがセッション情報を管理するページです。CFPを締め切ったためセッション情報の追加が今はできなくなっています。
スポンサーの方はsponsor_dashboardsからアクセスすることでCFPを締め切った後でもセッションを登録可能となっています。
ここは導線が分かりにくいので、今後改善していきます。

**Comment by TomikoTerayama** [comment]
@takaishi ありがとうございました。先方にご連絡いたします。

**Comment by TomikoTerayama** [comment]
@takaishi 上記の方法で無事に表示されたとのご連絡がありました。
ご対応いただきありがとうございました。
