### ISSUE TITLE
DreamkastからIVSの枠を作成・削除できるようにしたい

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#849]
Amazon IVS化することでAPIを叩きやすくなる。

DreamkastのAdminページからIVSの枠を作成したり削除できるようにすると、個別に作成する作業が不要になるため運用が楽になると思われる。
また、作成と同時にstream urlも設定出来れば、コピペも不要になる

**Comment by takaishi** [comment]
- API: https://docs.aws.amazon.com/ivs/latest/APIReference/Welcome.html
- Ruby SDK: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/IVS/Client.html

**Comment by takaishi** [comment]
@jacopen 前に一度聞いた気がするけど、アーカイブ配信もIVSでやるんだっけ？

**Comment by takaishi** [comment]
要確認メモ

- [ ] authorizedは必要かどうか

**Comment by takaishi** [comment]
- トラック毎にチャンネルが必要（録画のため）
- 録画設定が必要で、その設定はトラック毎のチャンネルに設定する必要がある
- 録画された映像はS3上に保存されるのでそれをアーカイブ画面に表示できる必要がある
- ストリームキーのリセットは今のところ不要層

**Comment by takaishi** [comment]
現在のブロッカーは、録画設定リソースを作成すると作成中にエラーが発生して使えないというもの。エラーの内容がわからずどうしたものか…となっている。

![image](https://user-images.githubusercontent.com/107187/135746622-4389ea9d-4dc1-4a98-8856-a102e2d3ecc7.png)

**Comment by takaishi** [comment]
- トラック毎のチャンネルの作成やチャンネル情報のダウンロードなどは https://github.com/cloudnativedaysjp/dreamkast/pull/894 で実装中
- アーカイブ動画の自動録画対応はIVSのRrcordingConfigurationリソースの作成が不安定で必要なリソースを作れていない状況。

**Comment by takaishi** [comment]
さっき試したら作れたので環境毎の設定を作っておいた。不安定だ…

![image](https://user-images.githubusercontent.com/107187/136691649-11416738-3440-4019-9b48-9e6e364bee46.png)
