### ISSUE TITLE
参加申込時メールの文面を決める

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#851]
CNDT2021から参加申込時にメールを送るようにするが、その文面をどうするか決める

**Comment by jacopen** [comment]
@nabemasat こちらなのですが、登録した段階で参加者にメールを送ります。
その文面をどうしようか決める必要があります。

現時点では極めてシンプルに

```
subject: "CloudNative Days Tokyo 2021への登録ありがとうございます"

こんにちは、山田 太郎 さん。

CloudNative Days Tokyo 2021にご登録いただきありがとうございます。

----------------------------
CloudNative Days Tokyo 2021運営事務局
Twitter: @cloudnativedays
E-mail: cndt2021@impress.co.jp
```

という形になっています。
- この本文について何か他に載せるべき情報はあるか
- 連絡先メールアドレスをどうするか

の2点について意見いただきたいです。
来週の一般申し込み開始までには必要になりますので、ちょっと急ぎめな感じです

**Comment by nabemasat** [comment]
@jacopen 遅くなりすみません。
連絡先アドレスはcndt2021@impress.co.jpで良いと思います。

このままでも良いと思うのですが、多少おもてなし感が出ると良いなと感じたので
文面案を書き起こしてみました。いかがでしょうか。
（たまにダッシュボードにログインしてね、ぐらいのことしか書いてませんが）
https://docs.google.com/document/d/1knHMrsbQ0jPLPjTkIjRFXJMpQBu7tfeK5cQeeaZYTPc/edit?usp=sharing

**Comment by jacopen** [comment]
ありがとうございます！！！めっちゃいいと思います。

@oshiro3 この文面でPRのほうに実装お願いしますー

**Comment by oshiro3** [comment]
了解です！
お二方ありがとうございます！
