### ISSUE TITLE
CNDT2021スポンサー　スポンサーセッションのチェック箇所がない

### ISSUE THREAD

**Issue by TomikoTerayama** [cloudnativedaysjp/dreamkast#857]
LINE（id73）のスポンサー情報登録で、スポンサーセッションにチェックが入っていないため修正依頼をしたところ、チェック箇所が見当たらないとご連絡を受けました。
カサレアル、ピュア・ストレージ、GMOの3社にも同様の修正依頼をしましたが、こちらの3社は修正できております。
間違ったところを見ているのでしょうか．．．ご確認をお願いいたします。
<img width="775" alt="LINE" src="https://user-images.githubusercontent.com/30485520/134144234-bb31dd98-c884-44ab-b7f2-58a3b1149b0d.png">

**Comment by jacopen** [comment]
こちらも以下のIssueと同じく、ログイン先が違っているのではないかと推測しています。
https://github.com/cloudnativedaysjp/dreamkast/issues/847#issuecomment-923487282

以下のリンクからログインをするよう連絡して頂き、チェックボックスの有無の確認をお願いします
https://event.cloudnativedays.jp/cndt2021/sponsor_dashboards/login

**Comment by TomikoTerayama** [comment]
@jacopen ありがとうございました。
ご指摘の通りでスポンサーセッションにチェックできたとのことです。
また、先方より以下について仕様の検討をお願いしたいとのコメントをいただきました。
-----------
登録時、ちょっと困ったのですが「セッションを追加する」を誤って押してしまったのですが
登録セッションが1つなのでどうすることもできず入力した内容を破棄して再入力したということがありました。
-----------

**Comment by jacopen** [comment]
なるほど、了解です。いただいたフィードバックはちょっと考えてみますね、ありがとうございます。
問題なさそうなのでこちらについてはクローズします
