### ISSUE TITLE
ActiveStorageで利用するクラウドストレージと、アカウントを何にするか決定する

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast#86]
ref: https://github.com/cloudnativedaysjp/dreamkast/issues/71

**Comment by jacopen** [comment]
Herokuにいくつかアドオンあり。
https://elements.heroku.com/addons/bucketeer
https://elements.heroku.com/addons/cloudcube

これをつかってバケット作ってあげるのがいいかも。そうすると料金周りをHerokuにまとめられる

**Comment by nabemasat** [comment]
>Consolidated Billing

>One less account to manage. Pay your S3 bill with your Heroku bill.

料金や管理を全部Herokuにまとめられちゃうのは良いですね。
@Kondoさん、いかがでしょうか？もちろん超過料金は別途ご請求頂くということで。

**Comment by jacopen** [comment]
価格的には$5/monthくらいいけそうです

**Comment by takaishi** [comment]
CloudCubeでできそうなのでクローズします
