### ISSUE TITLE
タイムテーブルの入力

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#865]
このタスクでタイムテーブルが決まる
https://github.com/cloudnativedaysjp/cndt2021/issues/30

決まったタイムテーブルに従って、各セッションの時間をDkに入力していく

due: 2021/09/28

**Comment by nabemasat** [comment]
Done

**Comment by nabemasat** [comment]
@jacopen @takaishi 
現時点で登録済みセッションのタイムテーブル登録完了しました。
サイトオープンOKになりましたらSlack等でお知らせください！
https://event.cloudnativedays.jp/cndt2021/talks
