### ISSUE TITLE
採択されたセッションリストが表示されない

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#878]
以下概要です
--------

Proposals > 採択結果を公開する
Admin Top > Proposal Result Visible Status > Visible
にしても、https://event.cloudnativedays.jp/cndt2021/talks に何もセッションが表示されていない
操作 or 設定ミス？

**Comment by takaishi** [comment]
ありゃ、調べます。夜になると思います。
adminのtalksもエラー吐いてるな

**Comment by takaishi** [comment]
あー、これはセッションの日付をまだ指定してないからですね。
