### ISSUE TITLE
スポンサーロゴの確認依頼

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#883]
@TomikoTerayama 
スポンサーロゴデータを貰いましたが、以下の2社については確認が必要なので連絡お願いします

- LegalForce 

いただいたロゴは縦配置になっています。Dreamkastのレイアウト的に横配置のほうが収まりが良く、ロゴが大きめに見えるため横配置をお勧めします。

過去のイベントでは横配置のデータを頂いているので、もし過去のものと同じであれば、それをそのまま利用します。
https://event.cloudnativedays.jp/cicd2021

- ビズリーチ

JPGのデータしかないようです。 PNGのデータをあわせて頂けると助かります

**Comment by TomikoTerayama** [comment]
確認いたします！

**Comment by TomikoTerayama** [comment]
@jacopen お待たせいたしました。
- LegalForce
横配置のものを利用して掲載をお願いできますか。
- ビズリーチ
PNGデータいただいたので、こちらでお願いします。
https://drive.google.com/file/d/1_zvp2GB9BSLHhYRxkPeE7eenL4X8W3s-/view?usp=sharing
