### ISSUE TITLE
sponsor_dashboardからの登録の際は、スポンサーセッションのフラグが常に立つようにしてほしい

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#886]
優先度は高くないのですが、担当者がスポンサーセッションのチェック入れ忘れが結構多くて、セッションの確認がやや手間です（特にキーノート周り）

sponsor_dashboardからの登録の際は、スポンサーセッションのフラグが常に立つようになっていると、事務局としては便利です（チェックボックスなくしてもいいかも）

**Comment by jacopen** [comment]
確かに～

チェックボックスをデフォルトONにするのはそんなに難しくないので、一般公開終わったらさくっとやっちゃいますね
