### ISSUE TITLE
参加登録をするとスピーカーダッシュボードに入れなくなる？

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#901]
Taichi Nakashima さん( @deeeet )から問い合わせ
参加登録後、スピーカーダッシュボードに入れないとのこと

スピーカー情報：
https://event.cloudnativedays.jp/cndt2021/admin/speakers/1169

Sub
google-oauth2\|114563355793830186020

------

以下、別の現象かもしれませんが関連して不具合が確認されたので報告します。

Nakashimaさんから依頼を受け、管理側でスピーカー情報（セッション内容）を編集しようとしたところ、
Successfully Updatedと表示されるのに、更新が反映されない。
また、スピーカーの漢字名表記が必ず空欄になってしまう。入れ直しても反映されない。

**Comment by jacopen** [comment]
@nabemasat 
推測ですけどスピーカーとして登録したアカウントと一般参加者として登録したアカウントが異なるんじゃないかなぁと思っています。裏付けのためにDB確認します。

後者に関しては、その画面からの編集に関しては今のところ想定していない(CFP機能が無かったCNDT2020向けの機能で今は使われていない)ので、仕様といえば仕様です。今はスピーカー本人が自分で書くことしか想定していないです

**Comment by jacopen** [comment]
ちなみにセッション内容編集ってどうやりました？ 今CSVでの編集をやるとあちこちぶっ壊れてもおかしくないので・・・

**Comment by jacopen** [comment]
CSVじゃなくて登壇者修正のところからの編集か。
ここもメンテしてない気が。漢字表記に未対応な気がする&修正はそんなに時間がかからないと思うので、直せるならサクッと直した方が良いかも

**Comment by nabemasat** [comment]
ご確認ありがとうございます:bow:
修正の方は、上に書かれている通りSpeakers>Editからです。
