### ISSUE TITLE
スクエアじゃないアイコンを使うと圧縮されてしまう

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#903]
いい感じに表示されるようにしたい
![image](https://user-images.githubusercontent.com/79102/136551158-75d64263-aed6-4e98-853d-876d3cc5acbb.png)

理想: アイコン登録時に範囲選択できるやつ
妥協点: 比率を崩さず切り取る

**Comment by oshiro3** [comment]
とりあえず cloudinary を試してみました。
開発環境上ではサクッと直せましたけど、画像アップロードについて何点か懸念点があったので(導入するとしても)導入方針についてはちょっと考えたいです。
詳細については一旦この issue につなげていきます。

結果として、before after についてはこのようになりましたというのを先に出しておきます。
![スクリーンショット 2021-12-04 173138](https://user-images.githubusercontent.com/40717789/144703235-e88060b1-ecd5-47e8-9ec4-6a284788844f.png)
![スクリーンショット 2021-12-04 173225](https://user-images.githubusercontent.com/40717789/144703238-116569a2-d715-48e2-aa63-74c08dc4ed9a.png)

**Comment by oshiro3** [comment]
画像周りについて cloudinary いくつか試した結果、懸念点として下記が挙げられるかと思いました。

1.  `Shrine` に結合させる形で使うと、`Shrine::store` が S3 と共存できなさそう
2. Rails の `image_tag` でなく `cl_image_tag` を使用するので、dev/test/prod の分離が難しそう（依存性をがっつりみえるところで持ってしまう）
3. リッチUIはダイレクトアップロードを行うので server で途中処理が挟めなくなる/作業を完了しなくても画像だけアップロードされる
4. リッチUI をつかうとトリミングしても元画像が保存されてしまう(詳細は未調査)

上記踏まえると以下の方針がとれるかと思います。

1-a. `Shrine::store` が画像周りしか使われていなければ `Shrine::store` を Cloudinary に統一する

- 最もシンプルな対応ですが、影響範囲をよく調べる必要があります

1-b. Cloudinary では `Shrine` を使わずに ActiveRecord にインテグレートする / Cloudinary でダイレクトアップロードする

- ActiveRecord にインテグレートする方法は他にも多数ありそう
- S3と管理方法が混在することになる
- ダイレクトアップロードするとサーバーでロールバックなどを制御できない
- ダイレクトアップロードでは Cloudinary ができないことはできない

2-a. mock-cloudinary という gem があるので、それらを運用してモックする

- 個人メンテで2019 からアップデートされてないのが気になる
- 開発用モックを管理/運用しないといけない

2-b. helper method でラップして環境ごとにタグを切り替えるように実装する

- helper の実装は複雑になりがち
- なんとなく(言語化できないですが)力技感を感じます

3. 対応が既出の課題に重複
4. JavaScript 側の調査をしないとなんとも言えないです

- Cloudinary の思想的に元データを crop するものではあまりなさそうというのを感じます。上の修正などは元データから AI によって自動抽出しており、多くの API が元画像を加工して表示する方向にエンパワメントされているようです。

-

**Comment by oshiro3** [comment]
#1042
