### ISSUE TITLE
MediaLiveとIVSそれぞれアーカイブ機能について調べる

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#908]
こちらのチケットから引き継ぎ
https://github.com/cloudnativedaysjp/dreamkast-broadcast/issues/41

IVSでアーカイブやれるかなと思ったが、どうもAPI周りの挙動が怪しい。
本番このまま進んでいいものか分からない。AWSにはElemental Mediaうんたらというシリーズのサービスがあり、そっちを使うのも手ではないか

ということで、調べる

**Comment by jacopen** [comment]
General settingsからいろいろ設定できるが、高度すぎてよくわからない。デフォでよさそう
![image](https://user-images.githubusercontent.com/79102/136704657-a702b91e-bc67-4c1c-a905-3e133470ede3.png)

## Inputの設定
Channelに流し込むInputは、MediaLiveのトップページから作成可能。
![image](https://user-images.githubusercontent.com/79102/136704733-3936bf16-bc8a-4bd7-b445-f4ee9801b3ae.png)

input typeにはRTMP(push)を指定。

Network modeはpublic

Input security groupで既存のものか新規作成か指定可能。RTMP配信元のグローバルIPが何になるのか今回は分からないため、全開けしたSGを作っておいてそれをアタッチするのがよさそう。
![image](https://user-images.githubusercontent.com/79102/136704802-a5cd4aec-cd42-4d82-84a4-9aba1c7b69d2.png)

Input destinationsのInput classについてはまたよくわからず使っている。要調査。ただChannel側と合わせる必要があるようだ。

DestinationのApplication name and instanceは、RTMPのURLになる。

Application nameが `test` , Application instanceが `instance` だとすると、RTMPのURLが
`rtmp://13.230.164.1:1935/test/instance` って感じになる。
![image](https://user-images.githubusercontent.com/79102/136704886-2ce81138-220d-4259-ac17-be0f61b18a4a.png)

**Comment by jacopen** [comment]
## Outputの設定

OutputはChannel作成画面から作成可能。APIの場合は分からないが

![image](https://user-images.githubusercontent.com/79102/136704983-92f85c2a-c46e-4226-a364-39ac4274298e.png)

今回はS3に保存するので Archiveを指定

![image](https://user-images.githubusercontent.com/79102/136705136-188b785e-24ed-4598-a73c-260183865d17.png)

Archive group destinationのURLには保存したいBucketとフォルダを指定。

Archive settingsにはOutputの名称を任意で。

CDN SettingsにはCFの設定ができるのか？ ここは調べられていない。

Additional settingsにはファイルのロールオーバーのための秒数が設定可能。今回の場合、セッション時間より長くしないとファイルが分割されてしまうため、3600 (=1h) くらいを設定しておく必要がありそう。

Archive outputsの Name modifieerには、バケットに保存されるファイル名を指定。Settingsを押すと詳細を設定できるが、今のところよくわからないのでデフォルトで・・。


以上でchannelとinput/outputの設定は終わり。

**Comment by jacopen** [comment]
配信するときはchannelのStartを押すと、数十秒後に稼働状態になる。思ったよりは時間がかかる。
StopするとS3側にファイルが作成されていることがわかる。

**Comment by takaishi** [comment]
📝 IVSとMediaLiveのどちらでもdk側でS3上のアーカイブを見えるように変更が必要

**Comment by takaishi** [comment]
CNDT2021はMediaLiveで録画機能を実装済み。クローズしておく。
