### ISSUE TITLE
スピーカーダッシュボードからビデオファイル登録リンクを押下するとエラーになる

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#923]
> スピーカーダッシュボードからビデオファイル登録リンクを押下すると添付したキャプチャのエラーが出てしまうのですが、原因わかりますでしょうか？
> 利用しているブラウザはChrome（シークレットモードでも発生）になります。

引用元：
https://cloudnativedays.slack.com/archives/C027V31GSJW/p1634463982089900

画像：
![image](https://user-images.githubusercontent.com/31978147/137621722-4294aeee-5027-42e0-9d32-c8b4ea43b98d.png)

**Comment by jacopen** [comment]
これ、バグでした。早急に直して確認中なので、Stagingで動作確認取れたら急ぎリリースします

**Comment by jacopen** [comment]
@nabemasat こちら修正完了しました
