### ISSUE TITLE
登壇者向けに通知を送れる機能がほしい

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#967]
特定の登壇者に対して、例えばZoomのアドレスを送るなど通知したいケースがある。

現時点ではメールを送っているが、これだとZoomアドレスを変更する必要があった場合再度編集しなくてはいけない。

登壇者ダッシュボードに運営からのメッセージを送れるような機能があると嬉しい

**Comment by takaishi** [comment]
連絡パターンとしては以下がある。

- 全登壇者に同じ内容を連絡
- 全登壇者に異なる内容を連絡
- 個別の登壇者に異なる内容を連絡
