### ISSUE TITLE
配信・録画まわりのアーキテクチャ見直し

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast#989]
CNDT2021の後にやる。

https://github.com/cloudnativedaysjp/dreamkast/issues/981 とか、IVSを止めてMedia〜＊だけで完結させるようにする、とか。

# 新アーキテクチャ

- 配信：配信オペレーター=>MediaLive=>IVS Channel=>視聴者 に変更 ( https://github.com/cloudnativedaysjp/dreamkast/pull/1094 )
  - 遅延は手元で試した限りは5秒程度
  - MediaPackage Channelは起動しっぱなしにする
- 録画：配信オペレーター=>MediaLive=>MediaPackage=>S3 に変更
  - MediaPackageのタイムシフト機能とHarvestJobを使って、セッション終了後に配信オペレーターがアーカイブ動画として切り出す
  - MediaLive ChannelからMediaPackage Channelに流す https://github.com/cloudnativedaysjp/dreamkast/pull/1096
  - MediaLive HarvestJobを使ってアーカイブ動画の切り出しを行えるようにする ( https://github.com/cloudnativedaysjp/dreamkast/pull/1100 )
    - DreamkastにタイムシフトプレビューとHarvestJobの作成画面を用意する。デフォルトの開始時間と終了時間はセッションの開始時間と終了時間だが、フォーム上から時間を変更してプレビューし直して微調整できる。
    - MediaPackage Channelの起動・終了の職人技が不要になる
    - HarvestJobの実行完了待ちはRakeTaskでPolingすることを検討中

**Comment by takaishi** [comment]
MediaLive経由でどの程度遅延するか調べた。

- OBS->MediaLive->IVS->手元 で5秒の遅延
- OBS->MediaLive->MediaStore->手元 で15秒の遅延
- OBS->IVS->手元 でも遅延は5秒くらい。MediaLive挟むのと変わらんのはなぜだ？

**Comment by takaishi** [comment]
Kaigi on Railsは MediaLive -> IVS の構成

https://aws.amazon.com/jp/blogs/business-productivity/how-rubykaigi-built-an-event-site-in-days-with-the-amazon-chime-sdk-and-amazon-ivs/

**Comment by takaishi** [comment]
このハンズオン資料よい

https://aws-mediaservices-jp.workshop.aws/handson1.html

**Comment by takaishi** [comment]
前に考えていたこの構成でいくのがいいかなあっと。VODパッケージ化のオペレーションをどうやるか。

![image](https://user-images.githubusercontent.com/107187/147642903-10dd198e-0da4-48a2-9faf-549fecabc767.png)

**Comment by takaishi** [comment]
タイムラグ調べたがMediaPackageでよさそうだな、という感じだった。HarvestJobの作成を自動化するかどうかは課題。


```
r_takaishi  2 hours ago
14:56:00~15:01:00 でHarvest Jobを作って

r_takaishi  2 hours ago
VODの開始時刻が14:55:49、終了時刻が15:00:55

r_takaishi  2 hours ago
5秒〜10秒ほど前にずれる

r_takaishi  2 hours ago
でもこのくらいなら問題なさそうだな

r_takaishi  2 hours ago
セッション開始前にはカウントダウンがあるので、セッションの開始時刻を指定すればOK

r_takaishi  2 hours ago
終了時刻は実際の終了時刻より1分ほど後を指定すればまず大丈夫じゃないか
```

**Comment by takaishi** [comment]
こんな感じで、開始時刻と終了時刻を指定できる。なのでセッション開始時刻と終了時刻をデフォルト値としてプレビューして、オペレーターが微調整した値でHarvestJobを作ってアーカイブ化することができるはず。

```
https://XXXXXXXXXXXXXXXXXXXXX/index.m3u8?start=2022-01-01T18:35:00+09:00&end=2022-01-01T18:37:00+09:00
```

**Comment by takaishi** [comment]
遅延が5分くらいあるから、アーカイブの作成も5分くらい待たないとだめか？

**Comment by takaishi** [comment]
start/endを指定してタイムシフト再生しつつ開始時刻と終了時刻を調整するモーダル、作れそう。
![image](https://user-images.githubusercontent.com/107187/148675077-986d9703-5230-43e4-90a1-f96282511f18.png)

**Comment by takaishi** [comment]
- MediaPackageのバッファ保持期間をどのくらいにするか（長くしたい）
- HarvestJob完了時にSlack通知したい
- 作る順番、消す順番をadminにかく
- ReviewAppでHarvestJob作ろうとするとなんかエラーになった

```
F, [2022-01-29T07:30:35.840379 #123] FATAL -- : [fa7226d7-6452-4a8e-a7b6-b1d403989171]
[fa7226d7-6452-4a8e-a7b6-b1d403989171] TypeError (can't dump hash with default proc):
[fa7226d7-6452-4a8e-a7b6-b1d403989171]
[fa7226d7-6452-4a8e-a7b6-b1d403989171] redis-store (1.9.0) lib/redis/store/serialization.rb:40:in `dump'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] redis-store (1.9.0) lib/redis/store/serialization.rb:40:in `_marshal'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] redis-store (1.9.0) lib/redis/store/serialization.rb:5:in `set'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] redis-store (1.9.0) lib/redis/store/namespace.rb:7:in `block in set'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] redis-store (1.9.0) lib/redis/store/namespace.rb:188:in `namespace'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] redis-store (1.9.0) lib/redis/store/namespace.rb:7:in `set'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] redis-rack (2.1.2) lib/rack/session/redis.rb:49:in `block (2 levels) in write_session'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] redis-rack (2.1.2) lib/redis/rack/connection.rb:22:in `with'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] redis-rack (2.1.2) lib/rack/session/redis.rb:82:in `with'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] redis-rack (2.1.2) lib/rack/session/redis.rb:49:in `block in write_session'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] redis-rack (2.1.2) lib/rack/session/redis.rb:70:in `with_lock'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] redis-rack (2.1.2) lib/rack/session/redis.rb:48:in `write_session'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] rack (2.2.3) lib/rack/session/abstract/id.rb:388:in `commit_session'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] rack (2.2.3) lib/rack/session/abstract/id.rb:268:in `context'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] actionpack (6.0.4.1) lib/action_dispatch/middleware/cookies.rb:654:in `call'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] actionpack (6.0.4.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] activesupport (6.0.4.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] actionpack (6.0.4.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] actionpack (6.0.4.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
[fa7226d7-6452-4a8e-a7b6-b1d403989171] sentry-rails (4.8.0) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'
```

**Comment by jacopen** [comment]
ほぼ完了かな？

**Comment by takaishi** [comment]
後はcronjobを用意すればクローズできるはず。
