### ISSUE TITLE
ステージングのDreamkastにnoindexを追加したい

### ISSUE THREAD

**Issue by inductor** [cloudnativedaysjp/dreamkast#996]
![image](https://user-images.githubusercontent.com/20236173/140018500-10cf3129-e62c-4706-aae7-5df118de1379.png)

![image](https://user-images.githubusercontent.com/20236173/140018538-b84490c2-472c-410e-a47e-4ec8d036fc39.png)

Chromeの検索結果から偶発的にこういうのが取れてしまう

**Comment by jacopen** [comment]
おーたしかに。これは対応しないとだめだ

**Comment by inductor** [comment]
偶発的だったのでStagingだけで書いてますが実際にはreview appsも同じですね

**Comment by jacopen** [comment]
そうねー。
Review appsもStagingもダミーデータ使ってたから問題になってなかったけど、stagingのデータをProductionに同期した結果顕在化してしまった。
なるべく早めに直したほうが良さそう
