### ISSUE TITLE
CNDT2021スポンサー パスワード変更

### ISSUE THREAD

**Issue by TomikoTerayama** [cloudnativedaysjp/dreamkast#998]
お忙しいところすみません。
レッドハットの担当から、以下の連絡がありました。
```
パスワードを変更しようとしましたが、ログイン後にパスワードを変更するメニューはなく、
一旦ログオフして、パスワードを忘れた体で再設定、というメニューでリセット用のメールを飛ばしてもプロセスできたように見えますが、メールが届きません。システム上から私のパスワードを再設定するための案内いただけないでしょうか。
```
セッション情報を登録した担当者のアカウント<mamorita@redhat.com>です。 
パスワード再設定について、ご確認いただけないでしょうか。

**Comment by takaishi** [comment]
Slackで対応済み、先方の返事待ちです

**Comment by TomikoTerayama** [comment]
@takaishi 先方の確認が取れて、やはりGoogleログインを使っていたとのことです。現在は、問題なくログインできているとのことです。
ご確認いただきありがとうございました。
